// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Globalization;
using System.Text;
using System.Text.Json.Nodes;
using Aspire.Cli.Resources;

namespace Aspire.Cli.Agents.Configuration;

/// <summary>
/// Native OpenCode catalogs and MCP entries, using one coherent schema across applicable scopes.
/// </summary>
internal sealed class OpenCodeConfigurationHandler(AgentConfigurationPaths paths, IEnvironment environment) : IAgentConfigurationHandler
{
    // Contract generated by scripts/build-opencode-catalog.mjs in aspire-skills PR #69.
    // These are catalog base URLs (the client appends index.json), not skill directories.
    // Shipping is gated on the released-main endpoints in microsoft/aspire-skills#72.
    // Never probe or download them from agent init.
    internal const string V1Catalog = "https://raw.githubusercontent.com/microsoft/aspire-skills/main/opencode/v1/";
    internal const string V2Catalog = "https://raw.githubusercontent.com/microsoft/aspire-skills/main/opencode/v2/";
    internal const string MinimumV1CatalogVersion = "1.18.31";
    private static readonly Version s_minimumV1CatalogVersion = Version.Parse(MinimumV1CatalogVersion);

    public IEnumerable<AgentConfigurationTarget> GetTargets(AgentInitRequest request)
    {
        if (!request.Clients.Contains(AgentClientKind.OpenCode) || (!request.Assets.AspireSkills && !request.Assets.Mcp))
        {
            yield break;
        }

        var project = FindLocation(request.WorkspaceRoot.FullName, AgentConfigurationScope.Project, includeNested: true);
        var user = paths.Override("OPENCODE_CONFIG") is { } customFile
            ? new OpenCodeLocation(customFile, AgentConfigurationScope.User, [customFile])
            : FindLocation(paths.OpenCodeDirectory, AgentConfigurationScope.User, includeNested: false);
        var locations = new List<OpenCodeLocation> { project, user };
        if (paths.Override("OPENCODE_CONFIG_DIR") is { } customDirectory)
        {
            locations.Add(FindLocation(customDirectory, AgentConfigurationScope.User, includeNested: false));
        }

        foreach (var location in locations)
        {
            if (request.Assets.AspireSkills)
            {
                yield return Target(location, AgentAssetKind.AspireSkills);
            }

            if (request.Assets.Mcp)
            {
                yield return Target(location, AgentAssetKind.Mcp);
            }
        }

        AgentConfigurationTarget Target(OpenCodeLocation location, AgentAssetKind asset)
            => new(location.Path, location.Scope, asset, [AgentClientKind.OpenCode], asset is AgentAssetKind.AspireSkills ? "catalog:aspire" : "mcp:aspire",
                async (root, context, cancellationToken) =>
                {
                    var documents = new Dictionary<string, JsonObject>(AgentConfigurationPath.Comparer);
                    var candidates = locations.SelectMany(item => item.Candidates)
                        .Concat(ConfigFiles(paths.OpenCodeDirectory))
                        .Concat(ConfigFiles(ManagedDirectory()));
                    foreach (var path in candidates.Distinct(AgentConfigurationPath.Comparer))
                    {
                        if (await context.ReadOptionalAsync(path, cancellationToken) is { } config)
                        {
                            documents[path] = config;
                        }
                    }

                    var present = location.Candidates.Where(documents.ContainsKey).ToArray();
                    var active = present.Length > 0 ? present[^1] : location.Candidates[0];
                    if (present.GroupBy(Path.GetDirectoryName, AgentConfigurationPath.Comparer).Any(group => group.Count() > 1))
                    {
                        return AgentConfigurationEdit.Blocked(AgentConfigurationStrings.OpenCodeMultipleFiles);
                    }

                    if (!AgentConfigurationPath.Comparer.Equals(active, location.Path))
                    {
                        return AgentConfigurationEdit.Blocked(AgentConfigurationStrings.ConcurrentChange);
                    }

                    var configs = documents.Values.Append(root).ToList();
                    if (environment.GetEnvironmentVariable("OPENCODE_CONFIG_CONTENT") is { Length: > 0 } inline)
                    {
                        var inlineConfig = AgentConfigurationJson.ParseObject(Encoding.UTF8.GetBytes(inline));
                        configs.Add(inlineConfig);
                        if (inlineConfig.ContainsKey(asset is AgentAssetKind.AspireSkills ? "skills" : "mcp"))
                        {
                            return AgentConfigurationEdit.Blocked(AgentConfigurationStrings.PolicyBlocked);
                        }
                    }

                    var schema = ResolveSchema(request.Detections, configs);
                    if (asset is AgentAssetKind.AspireSkills)
                    {
                        if (schema == 1 && GetUnsupportedCatalogVersion(request.Detections) is { } unsupportedVersion)
                        {
                            // The upstream V1 contract requires 1.18.31+ for skills.urls.
                            // Keep this capability check on the catalog mutation, not schema
                            // resolution: older clients still support native V1 MCP entries.
                            // https://github.com/microsoft/aspire-skills/pull/69
                            return AgentConfigurationEdit.Blocked(string.Format(CultureInfo.CurrentCulture,
                                AgentConfigurationStrings.OpenCodeCatalogVersionUnsupported, unsupportedVersion, MinimumV1CatalogVersion));
                        }

                        return ApplySkills(root, configs, schema);
                    }

                    foreach (var config in configs)
                    {
                        var container = AgentConfigurationJson.OptionalObject(config, "mcp");
                        var servers = schema == 2 && container is not null ? AgentConfigurationJson.OptionalObject(container, "servers") : container;
                        if (servers?.ContainsKey(McpConfiguration.ServerName) is true)
                        {
                            var existing = McpConfiguration.Apply(servers, "", commandArray: true, "local", copilot: false, bare: true);
                            if (existing.Status is AgentConfigurationStatus.Blocked or AgentConfigurationStatus.Skipped)
                            {
                                return existing;
                            }

                            var ownMcp = AgentConfigurationJson.OptionalObject(root, "mcp");
                            var ownServers = schema == 2 && ownMcp is not null ? AgentConfigurationJson.OptionalObject(ownMcp, "servers") : ownMcp;
                            if (ownServers?.ContainsKey(McpConfiguration.ServerName) is not true &&
                                !McpConfiguration.IsDefaultEntry(servers[McpConfiguration.ServerName]!.AsObject(), commandArray: true))
                            {
                                return AgentConfigurationEdit.Skipped(AgentConfigurationStrings.ExistingMcpCustomization);
                            }
                        }
                    }

                    var mcp = AgentConfigurationJson.Object(root, "mcp");
                    return McpConfiguration.Apply(mcp, "servers", commandArray: true, "local", copilot: false, bare: schema == 1);
                });
    }

    internal static int ResolveSchema(IReadOnlyList<AgentClientDetection> detections, IEnumerable<JsonObject> configs)
    {
        var versions = new HashSet<int>();
        foreach (var detection in detections.Where(detection => detection.Client is AgentClientKind.OpenCode && detection.Version is not null))
        {
            if (ParseVersion(detection.Version) is { } version)
            {
                if (version.Number.Major > 2)
                {
                    throw new AgentConfigurationException(AgentConfigurationStrings.OpenCodeSchemaConflict);
                }

                versions.Add(version.Number.Major < 2 ? 1 : 2);
            }
        }

        foreach (var config in configs)
        {
            if (config.TryGetPropertyValue("skills", out var skills))
            {
                switch (skills)
                {
                    case JsonObject v1:
                        AgentConfigurationJson.OptionalStrings(v1, "paths");
                        CheckCatalogs(AgentConfigurationJson.OptionalStrings(v1, "urls"), 1);
                        versions.Add(1);
                        break;
                    case JsonArray v2 when v2.All(value => AgentConfigurationJson.String(value) is not null):
                        CheckCatalogs(v2, 2);
                        versions.Add(2);
                        break;
                    default:
                        throw AgentConfigurationJson.Shape("skills");
                }
            }

            if (AgentConfigurationJson.OptionalObject(config, "mcp") is { Count: > 0 } mcp)
            {
                if (mcp.ContainsKey("servers") || IsV2Timeout(mcp["timeout"]))
                {
                    if (mcp.Any(property => property.Key is not ("servers" or "timeout")))
                    {
                        throw new AgentConfigurationException(AgentConfigurationStrings.OpenCodeSchemaConflict);
                    }

                    if (mcp.ContainsKey("timeout") &&
                        (!IsV2Timeout(mcp["timeout"]) || mcp["timeout"]!.AsObject().Any(property =>
                            property.Value is not JsonValue value || !value.TryGetValue<int>(out var timeout) || timeout <= 0)))
                    {
                        throw AgentConfigurationJson.Shape("mcp.timeout");
                    }

                    CheckServerShapes(AgentConfigurationJson.OptionalObject(mcp, "servers"), 2);
                    versions.Add(2);
                }
                else
                {
                    CheckServerShapes(mcp, 1);
                    versions.Add(1);
                }
            }
        }

        if (versions.Count > 1)
        {
            throw new AgentConfigurationException(AgentConfigurationStrings.OpenCodeSchemaConflict);
        }

        // An explicitly selected, undetected client with no schema evidence uses stable V1.
        return versions.SingleOrDefault(1);
    }

    private static string? GetUnsupportedCatalogVersion(IReadOnlyList<AgentClientDetection> detections)
    {
        foreach (var detection in detections.Where(detection => detection.Client is AgentClientKind.OpenCode))
        {
            if (ParseVersion(detection.Version) is { } version)
            {
                var comparison = version.Number.CompareTo(s_minimumV1CatalogVersion);
                if (comparison < 0 || (comparison == 0 && version.IsPrerelease))
                {
                    return detection.Version;
                }
            }
        }

        return null;
    }

    private static OpenCodeVersion? ParseVersion(string? text)
    {
        if (text is null)
        {
            return null;
        }

        // Probes can return "1.18.31+build", "v2.0.0-preview.1", or "opencode 2.0.0".
        // Build metadata does not lower precedence; 1.18.31-preview is below 1.18.31.
        // A shared $schema URL is not version evidence for either generation.
        foreach (var token in text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries))
        {
            var withoutMetadata = token.TrimStart('v').Split('+')[0];
            var parts = withoutMetadata.Split('-', 2);
            if (Version.TryParse(parts[0], out var version))
            {
                return new OpenCodeVersion(version, IsPrerelease: parts.Length > 1);
            }
        }

        return null;
    }

    private static AgentConfigurationEdit ApplySkills(JsonObject root, IReadOnlyList<JsonObject> configs, int schema)
    {
        var preferred = schema == 1 ? V1Catalog : V2Catalog;
        foreach (var config in configs)
        {
            var sources = schema == 1
                ? AgentConfigurationJson.OptionalObject(config, "skills") is { } skills ? AgentConfigurationJson.OptionalStrings(skills, "urls") : null
                : config["skills"] as JsonArray;
            if (sources?.Select(AgentConfigurationJson.String).FirstOrDefault(value => CatalogSchema(value) == schema) is { } existing)
            {
                preferred = existing;
                if (!existing.Contains("/main/opencode/", StringComparison.Ordinal))
                {
                    break;
                }
            }
        }

        JsonArray target;
        if (schema == 1)
        {
            var skills = AgentConfigurationJson.Object(root, "skills");
            target = AgentConfigurationJson.OptionalStrings(skills, "urls") ?? new JsonArray();
            if (!skills.ContainsKey("urls"))
            {
                skills["urls"] = target;
            }
        }
        else
        {
            target = root["skills"] as JsonArray ?? new JsonArray();
            if (!root.ContainsKey("skills"))
            {
                root["skills"] = target;
            }
        }

        if (!target.Any(value => CatalogSchema(AgentConfigurationJson.String(value)) == schema))
        {
            target.Add((JsonNode?)preferred);
        }

        return AgentConfigurationEdit.Applied(AgentConfigurationStrings.Registered);
    }

    private static void CheckCatalogs(JsonArray? sources, int schema)
    {
        if (sources is not null && sources.Any(value => CatalogSchema(AgentConfigurationJson.String(value)) is { } declared && declared != schema))
        {
            throw new AgentConfigurationException(AgentConfigurationStrings.OpenCodeSchemaConflict);
        }
    }

    private static int? CatalogSchema(string? source)
    {
        if (!Uri.TryCreate(source, UriKind.Absolute, out var uri) || uri.Scheme != Uri.UriSchemeHttps ||
            !uri.Host.Equals("raw.githubusercontent.com", StringComparison.OrdinalIgnoreCase) ||
            !uri.AbsolutePath.StartsWith("/microsoft/aspire-skills/", StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        var path = uri.AbsolutePath.TrimEnd('/');
        return path.EndsWith("/opencode/v1", StringComparison.Ordinal) ? 1
            : path.EndsWith("/opencode/v2", StringComparison.Ordinal) ? 2
            : null;
    }

    private static void CheckServerShapes(JsonObject? servers, int schema)
    {
        if (servers is null)
        {
            return;
        }

        foreach (var (_, node) in servers)
        {
            if (node is not JsonObject server)
            {
                throw AgentConfigurationJson.Shape("mcp");
            }

            if (server.ContainsKey(schema == 1 ? "disabled" : "enabled"))
            {
                throw new AgentConfigurationException(AgentConfigurationStrings.OpenCodeSchemaConflict);
            }
        }
    }

    private static bool IsV2Timeout(JsonNode? node)
        => node is JsonObject timeout && timeout.All(property => property.Key is "startup" or "catalog" or "execution");

    private string ManagedDirectory()
    {
        // https://opencode.ai/docs/config/#managed-settings
        if (environment.IsWindows())
        {
            return Path.Combine(paths.Override("ProgramData") ?? Path.Combine(Path.GetPathRoot(paths.Home)!, "ProgramData"), "opencode");
        }

        return environment.IsMacOS()
            ? Path.Combine(Path.DirectorySeparatorChar.ToString(), "Library", "Application Support", "opencode")
            : Path.Combine(Path.DirectorySeparatorChar.ToString(), "etc", "opencode");
    }

    private static OpenCodeLocation FindLocation(string directory, AgentConfigurationScope scope, bool includeNested)
    {
        var candidates = ConfigFiles(directory).ToList();
        if (includeNested)
        {
            candidates.AddRange(ConfigFiles(Path.Combine(directory, ".opencode")));
        }

        return new OpenCodeLocation(candidates.LastOrDefault(File.Exists) ?? candidates[0], scope, candidates);
    }

    private static IEnumerable<string> ConfigFiles(string directory)
    {
        yield return Path.Combine(directory, "opencode.json");
        yield return Path.Combine(directory, "opencode.jsonc");
    }

    private readonly record struct OpenCodeVersion(Version Number, bool IsPrerelease);

    private sealed record OpenCodeLocation(string Path, AgentConfigurationScope Scope, IReadOnlyList<string> Candidates);
}
