<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>f87b300e-ffab-45ef-9916-1fd30b401b33</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <AspireProjectOrPackageReference Include="Aspire.Hosting.AppHost" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Azure.ApiManagement" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Azure.KeyVault" />
    <ProjectReference Include="..\AzureApiManagement.ApiService\AzureApiManagement.ApiService.csproj" />
  </ItemGroup>

</Project>
