// <copyright file="Program.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>

using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using ChaosProxy.Container;
using ChaosProxy.Container.Middleware;
using ChaosProxy.Container.Policy;
using ChaosProxy.Container.Telemetry;
using OpenTelemetry.Metrics;
using OpenTelemetry.Trace;

// Build-time dev-cert bake (see container/Dockerfile). `--generate-dev-cert <path>` writes the
// self-signed HTTPS cert to <path> and exits WITHOUT starting the web host. The Dockerfile runs
// this during `docker build` so the cert is baked into the image and every container START loads
// it (cheap) instead of doing an RSA-2048 keygen per start — which, across a mesh of N proxy
// containers, was N keygens on every bring-up. Generated by the app itself so it's guaranteed
// loadable at runtime. Dev-only: the https listener is accept-any-cert; never use this in prod.
if (args is ["--generate-dev-cert", var certOutputPath])
{
    using var bakedCert = CreateSelfSignedCertificate();
    File.WriteAllBytes(certOutputPath, bakedCert.Export(X509ContentType.Pfx));
    return;
}

var builder = WebApplication.CreateBuilder(args);

// Dual-listen: HTTP on 8080 (the /chaos control plane + plain-HTTP mesh edges) AND
// HTTPS on 8443 (for clients that REQUIRE https to their target — notably the
// Microsoft.Azure.Cosmos SDK in Gateway mode, which won't talk to an http endpoint).
// The HTTPS listener uses the dev cert baked into the image at build time (loaded from
// /app/devcert.pfx); if that's absent (non-container / test runs) it falls back to an
// in-memory self-signed cert generated once at startup. Dev-only chaos infra; consumers
// that route through the https endpoint must accept any server cert (e.g. GW's CosmosClient
// sets ServerCertificateCustomValidationCallback => true in Development).
//
// ConfigureKestrel (not ASPNETCORE_URLS) owns the ports so we can attach the cert to
// the https listener; the Dockerfile no longer sets ASPNETCORE_URLS.
builder.WebHost.ConfigureKestrel(kestrel =>
{
    kestrel.ListenAnyIP(8080);
    kestrel.ListenAnyIP(8443, listen => listen.UseHttps(LoadDevCertificate()));
});

// YARP-as-library: route + cluster config comes from ReverseProxy__* env vars
// (set by Aspire.Hosting.Chaos's WithTarget<T>() extension at AppHost startup).
builder.Services.AddReverseProxy()
    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"))
    // Accept any UPSTREAM server cert when forwarding. The chaos proxy forwards to
    // local-dev Azure emulators (e.g. the Cosmos preview emulator) that present
    // self-signed certs. This is the proxy→upstream leg; dev-only chaos infra.
    .ConfigureHttpClient((_, handler) =>
        handler.SslOptions.RemoteCertificateValidationCallback = (_, _, _, _) => true);

// HttpClient used by ChaosReplayDuplicateMiddleware to fire background duplicate requests
// directly at the upstream URL (bypassing YARP to avoid recursive chaos).
builder.Services.AddHttpClient();

// Policy infrastructure: thread-safe store of installed chaos policies plus a background
// service that sweeps expired policies (TTL safety net per D6).
builder.Services.AddSingleton<ActivePolicyStore>();
builder.Services.AddHostedService<PolicyExpirationService>();

// Fault-profile registry (resource-aware random chaos): loads the embedded profiles
// (service.http + azure.*) once at startup so ChaosRandomFaultMiddleware can sample them.
builder.Services.AddSingleton(ChaosProxy.Container.Policy.Profiles.FaultProfileRegistry.CreateDefault());

// OpenTelemetry tracing + metrics. Aspire injects OTEL_EXPORTER_OTLP_* env vars when
// the resource builder calls .WithOtlpExporter(); the OTLP exporter reads those
// automatically. Adding the ChaosActivitySource means chaos.proxy.* span tags written
// by middleware show up on the ASP.NET Core request span in the Aspire dashboard's
// traces tab. Adding the ChaosMeter source means chaos.proxy.fires + .policies.active
// metrics show up on the Metrics tab.
builder.Services.AddOpenTelemetry()
    .WithTracing(tracing => tracing
        .AddAspNetCoreInstrumentation()
        .AddSource(ChaosActivitySource.Name)
        .AddOtlpExporter())
    .WithMetrics(metrics => metrics
        .AddAspNetCoreInstrumentation()
        .AddMeter(ChaosMeter.Name)
        .AddOtlpExporter());

var app = builder.Build();

// Bootstrap policy: translate CHAOS_* env vars set by the AppHost fluent extensions
// (WithLatency, WithError, WithReplayDuplicate, When) into a single ActivePolicy added
// to the store at startup. Preserves the existing AppHost API even as runtime policy
// installation lands. Bootstrap policy has no TTL (lives for the container's lifetime).
var store = app.Services.GetRequiredService<ActivePolicyStore>();

// Observable gauge for the current installed-policy count. Aspire's Metrics tab
// polls this once per export interval (default 60s) and graphs it. Lets dashboard
// viewers spot "did the policy slip past TTL?" at a glance.
ChaosMeter.Source.CreateObservableGauge(
    "chaos.proxy.policies.active",
    () => (long)store.GetActive().Count,
    unit: "{policy}",
    description: "Number of currently-installed (non-expired) chaos policies.");

var bootstrap = EnvironmentPolicyLoader.LoadBootstrap(app.Configuration);
if (bootstrap is not null)
{
    store.Add(bootstrap);
    app.Logger.LogInformation("Loaded bootstrap chaos policy from environment: matcher={Matcher} latency={Latency} error={Error} replay={Replay} drop={Drop} rateLimit={RateLimit} forwardThenFail={ForwardThenFail}",
        bootstrap.Matcher is not null, bootstrap.Latency is not null, bootstrap.Error is not null, bootstrap.ReplayDuplicate is not null, bootstrap.DropResponse is not null, bootstrap.RateLimit is not null, bootstrap.ForwardThenFail is not null);
}

// Declared policies installed at AppHost build time via WithPolicy(...). Loaded
// AFTER the bootstrap so install order matches author intent (bootstrap fluent chain
// runs first, then any explicit WithPolicy calls). D12 first-installed-wins on matcher
// overlap respects this order.
foreach (var declared in EnvironmentPolicyLoader.LoadDeclaredPolicies(app.Configuration, app.Logger))
{
    store.Add(declared);
    app.Logger.LogInformation("Loaded declared chaos policy {PolicyId}: matcher={Matcher} latency={Latency} error={Error} replay={Replay} drop={Drop} rateLimit={RateLimit} forwardThenFail={ForwardThenFail}",
        declared.Id, declared.Matcher is not null, declared.Latency is not null, declared.Error is not null, declared.ReplayDuplicate is not null, declared.DropResponse is not null, declared.RateLimit is not null, declared.ForwardThenFail is not null);
}


// All /chaos/* control-plane endpoints (healthz, policies CRUD, state, fire-once, etc)
// are defined in ChaosEndpoints.MapChaosEndpoints so tests can wire just the endpoints
// against a TestServer without spinning up YARP / OTel / chaos middleware.
app.MapChaosEndpoints(app.Logger);

// Pipeline: body-buffering (opt-in per active policy) -> latency -> header-tamper ->
// idempotency-collision -> error -> rate-limit -> partial-response -> slow-response ->
// drop-response -> replay-duplicate -> forward-then-fail -> YARP. Slow-response sits
// after partial-response (which aborts mid-stream) and before drop (which never writes
// anything) - the failure modes go from "delivers complete response slowly" to
// "delivers partial then aborts" to "delivers nothing at all". Forward-then-fail sits
// LAST (right before YARP) - it actually contacts upstream itself, so anything that
// would short-circuit upstream (error, drop, etc.) needs first crack at the request.
// Body buffering runs first so every downstream matcher can consult the buffered body
// via HttpContext.Items - and so forward-then-fail can re-read Body to forward it.
app.UseMiddleware<ChaosRequestBodyBufferingMiddleware>();
app.UseMiddleware<ChaosRandomFaultMiddleware>();
app.UseMiddleware<ChaosLatencyMiddleware>();
app.UseMiddleware<ChaosHeaderTamperMiddleware>();
app.UseMiddleware<ChaosIdempotencyCollisionMiddleware>();
app.UseMiddleware<ChaosErrorMiddleware>();
app.UseMiddleware<ChaosRateLimitMiddleware>();
app.UseMiddleware<ChaosPartialResponseMiddleware>();
app.UseMiddleware<ChaosSlowResponseMiddleware>();
app.UseMiddleware<ChaosDropResponseMiddleware>();
app.UseMiddleware<ChaosReplayDuplicateMiddleware>();
app.UseMiddleware<ChaosForwardThenFailMiddleware>();
app.MapReverseProxy();

app.Run();

// Loads the dev HTTPS cert for the 8443 listener. Prefers the cert baked into the image at
// build time (see the Dockerfile's --generate-dev-cert step) so each container start just reads
// a file instead of doing an RSA-2048 keygen — which mattered because the mesh runs many proxy
// containers and every start used to regenerate a key. Falls back to generating one in-memory
// for non-container / test runs where no baked cert is present. Dev-only; consumers routed
// through the https listener accept any server cert, so the cert identity is never pinned.
static X509Certificate2 LoadDevCertificate()
{
    var bakedCertPath = Environment.GetEnvironmentVariable("CHAOS_PROXY_DEV_CERT_PATH")
        ?? "/app/devcert.pfx";
    if (File.Exists(bakedCertPath))
    {
        // Baked PFX is exported with no password (X509ContentType.Pfx); load with empty password.
        return new X509Certificate2(bakedCertPath);
    }

    return CreateSelfSignedCertificate();
}

// Generates an in-memory self-signed cert. Used at image-build time to bake the dev cert into
// the image (see --generate-dev-cert) AND as the runtime fallback in LoadDevCertificate when no
// baked cert is present (non-container / test runs). Exported + reimported as PKCS#12 so Kestrel
// gets a cert with a usable private key on Linux. SANs cover the common names a consumer might
// dial the proxy by (localhost + the Aspire resource name pattern); cert validation is skipped by
// consumers anyway (dev-only chaos infra), so the SANs are belt-and-suspenders. Never pinned.
static X509Certificate2 CreateSelfSignedCertificate()
{
    using var rsa = RSA.Create(2048);
    var request = new CertificateRequest("CN=chaos-proxy", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
    request.CertificateExtensions.Add(new X509BasicConstraintsExtension(false, false, 0, false));
    request.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.DigitalSignature | X509KeyUsageFlags.KeyEncipherment, false));
    request.CertificateExtensions.Add(new X509EnhancedKeyUsageExtension(new OidCollection { new Oid("1.3.6.1.5.5.7.3.1") }, false)); // serverAuth

    var sanBuilder = new SubjectAlternativeNameBuilder();
    sanBuilder.AddDnsName("localhost");
    sanBuilder.AddDnsName("chaos-proxy");
    sanBuilder.AddIpAddress(System.Net.IPAddress.Loopback);
    request.CertificateExtensions.Add(sanBuilder.Build());

    using var cert = request.CreateSelfSigned(DateTimeOffset.UtcNow.AddDays(-1), DateTimeOffset.UtcNow.AddYears(5));
    // Export+reimport so the private key is persisted in a form Kestrel can use on Linux.
    return new X509Certificate2(cert.Export(X509ContentType.Pfx));
}
