<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsShipping>false</IsShipping>
    <IsAotCompatible>true</IsAotCompatible>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <EnableAspireIntegrationAnalyzers>true</EnableAspireIntegrationAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NativeHosting.AtsServer" />
    <Compile Include="../../../src/Aspire.Hosting/Ats/AspireExportAttribute.cs" Link="Attributes/AspireExportAttribute.cs" />
    <Compile Include="../../../src/Aspire.Hosting/Ats/AspireDtoAttribute.cs" Link="Attributes/AspireDtoAttribute.cs" />
    <Compile Include="../../../src/Aspire.Hosting/Ats/AspireUnionAttribute.cs" Link="Attributes/AspireUnionAttribute.cs" />
    <Compile Include="../../../src/Aspire.Hosting/Ats/AspireExportIgnoreAttribute.cs" Link="Attributes/AspireExportIgnoreAttribute.cs" />
    <Compile Include="../Core/NativeModel.cs" Link="NativeModel.cs" />
    <Compile Include="../Core/NativeCustomResources.cs" Link="NativeCustomResources.cs" />
    <Compile Include="../Core/NativeDcp.cs" Link="NativeDcp.cs" />
    <Compile Include="../RpcPeer.cs" Link="RpcPeer.cs" />
    <Compile Include="../../../src/Shared/DcpKubeconfigData.cs" Link="DcpKubeconfigData.cs" />
    <ProjectReference Include="../../../src/Aspire.Hosting.Integration.Analyzers/Aspire.Hosting.Integration.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" GlobalPropertiesToRemove="PublishAot;RuntimeIdentifier;SelfContained" />
  </ItemGroup>
</Project>
