//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public static partial class AzureSandboxesExtensions
    {
        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayResource> AddAzureConnectorGateway(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> AddAzureSandboxGroup(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> AddConnection(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayResource> builder, string name, string connectorName, Azure.AzureConnectorGatewayConnectionOptions? options = null) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayMcpServerConfigResource> AddMcpServerConfig(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayResource> builder, string name, Azure.AzureConnectorGatewayMcpServerConfigOptions? options = null) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayTriggerConfigResource> AddTriggerConfig(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> builder, string name, string operationName, ApplicationModel.EndpointReference callbackEndpoint, Azure.AzureConnectorGatewayTriggerOptions? options = null) { throw null; }

        [AspireExport("asExistingConnectorGatewayConnection", MethodName = "asExisting")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> AsExisting(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> builder) { throw null; }

        [AspireExport("asExistingConnectorGatewayMcpServerConfig", MethodName = "asExisting")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayMcpServerConfigResource> AsExisting(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayMcpServerConfigResource> builder) { throw null; }

        [AspireExport("publishComputeResourceAsAzureSandbox", MethodName = "publishAsAzureSandbox")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<T> PublishAsAzureSandbox<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> sandboxGroup, Azure.AzureSandboxOptions? options = null)
            where T : ApplicationModel.IResource, ApplicationModel.IComputeResource { throw null; }

        [AspireExportIgnore(Reason = "Use the AzureSandboxOptions overload from ATS.")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<T> PublishAsAzureSandbox<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> sandboxGroup, System.Action<Azure.AzureSandboxOptions> configure)
            where T : ApplicationModel.IResource, ApplicationModel.IComputeResource { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> WithAccessPolicy(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> builder, string name, Azure.AzureConnectorGatewayAccessPolicyOptions options) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayMcpServerConfigResource> WithConnector(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayMcpServerConfigResource> builder, string connectorName, ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> connection, Azure.AzureConnectorGatewayMcpConnectorOptions options) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> WithIdentityAccessPolicy(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorGatewayConnectionResource> builder, string name, ApplicationModel.IResourceBuilder<Azure.AzureUserAssignedIdentityResource> identity, string? policyName = null) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> WithNoManagedIdentity(this ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> builder) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> WithSystemAssignedIdentity(this ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> builder) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> WithUserAssignedIdentity(this ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> builder, ApplicationModel.IResourceBuilder<Azure.AzureUserAssignedIdentityResource> identity) { throw null; }
    }
}

namespace Aspire.Hosting.Azure
{
    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayAccessPolicyOptions
    {
        public required string ObjectId { get { throw null; } set { } }

        public string? PolicyName { get { throw null; } set { } }

        public required string TenantId { get { throw null; } set { } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayConnectionOptions
    {
        public string? ConnectionName { get { throw null; } set { } }

        public string? DisplayName { get { throw null; } set { } }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayConnectionResource : ApplicationModel.Resource, ApplicationModel.IResourceWithParent<AzureConnectorGatewayResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource, ApplicationModel.IResourceWithoutLifetime
    {
        public AzureConnectorGatewayConnectionResource(string name, string connectionName, string connectorName, string? displayName, AzureConnectorGatewayResource parent) : base(default!) { }

        public string ConnectionName { get { throw null; } }

        public string ConnectorName { get { throw null; } }

        public string? DisplayName { get { throw null; } }

        public AzureConnectorGatewayResource Parent { get { throw null; } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayMcpConnectorOptions
    {
        public string? Description { get { throw null; } set { } }

        public string? DisplayName { get { throw null; } set { } }

        public AzureConnectorGatewayMcpOperationOptions[] Operations { get { throw null; } set { } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayMcpOperationOptions
    {
        public string? Description { get { throw null; } set { } }

        public string? DisplayName { get { throw null; } set { } }

        public required string Name { get { throw null; } set { } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayMcpServerConfigOptions
    {
        public string? ConfigName { get { throw null; } set { } }

        public string? Description { get { throw null; } set { } }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayMcpServerConfigResource : ApplicationModel.Resource, ApplicationModel.IResourceWithParent<AzureConnectorGatewayResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource, ApplicationModel.IResourceWithoutLifetime
    {
        public AzureConnectorGatewayMcpServerConfigResource(string name, string configName, string? description, AzureConnectorGatewayResource parent) : base(default!) { }

        public string ConfigName { get { throw null; } }

        public string? Description { get { throw null; } }

        public AzureConnectorGatewayResource Parent { get { throw null; } }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayResource : AzureProvisioningResource
    {
        public AzureConnectorGatewayResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public BicepOutputReference PrincipalId { get { throw null; } }

        public BicepOutputReference TenantId { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayTriggerConfigResource : AzureProvisioningResource, ApplicationModel.IResourceWithParent<AzureConnectorGatewayResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource, ApplicationModel.IResourceWithoutLifetime
    {
        public AzureConnectorGatewayTriggerConfigResource(string name, string triggerName, string operationName, ApplicationModel.EndpointReference callbackEndpoint, string? callbackPath, string? description, AzureConnectorGatewayConnectionResource connection, System.Collections.Generic.IReadOnlyList<AzureConnectorGatewayTriggerParameter> triggerParameters) : base(default!, default!) { }

        public ApplicationModel.EndpointReference CallbackEndpoint { get { throw null; } }

        public string? CallbackPath { get { throw null; } }

        public AzureConnectorGatewayConnectionResource Connection { get { throw null; } }

        public string? Description { get { throw null; } }

        public string OperationName { get { throw null; } }

        public AzureConnectorGatewayResource Parent { get { throw null; } }

        public string TriggerName { get { throw null; } }

        public System.Collections.Generic.IReadOnlyList<AzureConnectorGatewayTriggerParameter> TriggerParameters { get { throw null; } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayTriggerOptions
    {
        public string? CallbackPath { get { throw null; } set { } }

        public string? Description { get { throw null; } set { } }

        public AzureConnectorGatewayTriggerParameter[] Parameters { get { throw null; } set { } }

        public string? TriggerName { get { throw null; } set { } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorGatewayTriggerParameter
    {
        public required string Name { get { throw null; } set { } }

        public required string Value { get { throw null; } set { } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureSandboxEndpointOptions
    {
        public bool? Anonymous { get { throw null; } set { } }

        public string? Name { get { throw null; } set { } }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureSandboxGroupResource : AzureProvisioningResource, IAzureComputeEnvironmentResource, ApplicationModel.IComputeEnvironmentResource, ApplicationModel.IResource
    {
        public AzureSandboxGroupResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        IAzureContainerRegistryResource? IAzureComputeEnvironmentResource.ContainerRegistry { get { throw null; } }

        public AzureContainerRegistryResource? ContainerRegistry { get { throw null; } }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRECOMPUTE002", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public ApplicationModel.ReferenceExpression GetEndpointPropertyExpression(ApplicationModel.EndpointReferenceExpression endpointReferenceExpression) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRECOMPUTE002", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public ApplicationModel.ReferenceExpression GetHostAddressExpression(ApplicationModel.EndpointReference endpointReference) { throw null; }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureSandboxOptions
    {
        public bool? AutoDeleteEnabled { get { throw null; } set { } }

        public int? AutoDeleteIntervalInDays { get { throw null; } set { } }

        public long? AutoDeleteIntervalInSeconds { get { throw null; } set { } }

        public string? AutoDeleteTrigger { get { throw null; } set { } }

        public bool? AutoSuspendEnabled { get { throw null; } set { } }

        public int? AutoSuspendInterval { get { throw null; } set { } }

        public string? AutoSuspendMode { get { throw null; } set { } }

        public AzureSandboxEndpointOptions[]? Endpoints { get { throw null; } set { } }

        public int? PublicEndpointReadyTimeoutSeconds { get { throw null; } set { } }

        public AzureSandboxTier Tier { get { throw null; } set { } }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public enum AzureSandboxTier
    {
        ExtraSmall = 0,
        Small = 1,
        Medium = 2,
        Large = 3,
        ExtraLarge = 4
    }
}