//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public static partial class AzureSandboxesExtensions
    {
        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceResource> AddAzureConnectorNamespace(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> AddAzureSandboxGroup(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceConnectionResource> AddConnection(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceResource> builder, string name, string connectorName, Azure.AzureConnectorNamespaceConnectionOptions? options = null) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceMcpServerConfigResource> AddMcpServerConfig(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceResource> builder, string name, Azure.AzureConnectorNamespaceMcpServerConfigOptions? options = null) { throw null; }

        [AspireExport("asExistingConnectorNamespaceConnection", MethodName = "asExisting")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceConnectionResource> AsExisting(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceConnectionResource> builder) { throw null; }

        [AspireExport("asExistingConnectorNamespaceMcpServerConfig", MethodName = "asExisting")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceMcpServerConfigResource> AsExisting(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceMcpServerConfigResource> builder) { throw null; }

        [AspireExport("publishComputeResourceAsAzureSandbox", MethodName = "publishAsAzureSandbox")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<T> PublishAsAzureSandbox<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> sandboxGroup, Azure.AzureSandboxOptions? options = null)
            where T : ApplicationModel.IComputeResource { throw null; }

        [AspireExportIgnore(Reason = "Use the AzureSandboxOptions overload from ATS.")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<T> PublishAsAzureSandbox<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> sandboxGroup, System.Action<Azure.AzureSandboxOptions> configure)
            where T : ApplicationModel.IComputeResource { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceConnectionResource> WithAccessPolicy(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceConnectionResource> builder, string name, Azure.AzureConnectorNamespaceAccessPolicyOptions options) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> WithAcrPullIdentity(this ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> builder, ApplicationModel.IResourceBuilder<Azure.AzureUserAssignedIdentityResource> identity) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceMcpServerConfigResource> WithConnector(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceMcpServerConfigResource> builder, string connectorName, ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceConnectionResource> connection, Azure.AzureConnectorNamespaceMcpConnectorOptions options) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceConnectionResource> WithIdentityAccessPolicy(this ApplicationModel.IResourceBuilder<Azure.AzureConnectorNamespaceConnectionResource> builder, string name, ApplicationModel.IResourceBuilder<Azure.AzureUserAssignedIdentityResource> identity, string? policyName = null) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> WithNoManagedIdentity(this ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> builder) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> WithSystemAssignedIdentity(this ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> builder) { throw null; }

        [AspireExport]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> WithUserAssignedIdentity(this ApplicationModel.IResourceBuilder<Azure.AzureSandboxGroupResource> builder, ApplicationModel.IResourceBuilder<Azure.AzureUserAssignedIdentityResource> identity) { throw null; }
    }
}

namespace Aspire.Hosting.Azure
{
    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorNamespaceAccessPolicyOptions
    {
        public required string ObjectId { get { throw null; } set { } }

        public string? PolicyName { get { throw null; } set { } }

        public required string TenantId { get { throw null; } set { } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorNamespaceConnectionOptions
    {
        public string? ConnectionName { get { throw null; } set { } }

        public string? DisplayName { get { throw null; } set { } }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorNamespaceConnectionResource : ApplicationModel.Resource, ApplicationModel.IResourceWithParent<AzureConnectorNamespaceResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource, ApplicationModel.IResourceWithoutLifetime
    {
        public AzureConnectorNamespaceConnectionResource(string name, string connectionName, string connectorName, string? displayName, AzureConnectorNamespaceResource parent) : base(default!) { }

        public string ConnectionName { get { throw null; } }

        public string ConnectorName { get { throw null; } }

        public string? DisplayName { get { throw null; } }

        public AzureConnectorNamespaceResource Parent { get { throw null; } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorNamespaceMcpConnectorOptions
    {
        public string? Description { get { throw null; } set { } }

        public string? DisplayName { get { throw null; } set { } }

        public AzureConnectorNamespaceMcpOperationOptions[] Operations { get { throw null; } set { } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorNamespaceMcpOperationOptions
    {
        public string? Description { get { throw null; } set { } }

        public string? DisplayName { get { throw null; } set { } }

        public required string Name { get { throw null; } set { } }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorNamespaceMcpServerConfigOptions
    {
        public string? ConfigName { get { throw null; } set { } }

        public string? Description { get { throw null; } set { } }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorNamespaceMcpServerConfigResource : ApplicationModel.Resource, ApplicationModel.IResourceWithParent<AzureConnectorNamespaceResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource, ApplicationModel.IResourceWithoutLifetime
    {
        public AzureConnectorNamespaceMcpServerConfigResource(string name, string configName, string? description, AzureConnectorNamespaceResource parent) : base(default!) { }

        public string ConfigName { get { throw null; } }

        public string? Description { get { throw null; } }

        public AzureConnectorNamespaceResource Parent { get { throw null; } }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureConnectorNamespaceResource : AzureProvisioningResource
    {
        public AzureConnectorNamespaceResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference Id { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public BicepOutputReference PrincipalId { get { throw null; } }

        public BicepOutputReference TenantId { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public enum AzureSandboxAutoDeleteTrigger
    {
        AfterSuspend = 0,
        AfterCreation = 1
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public enum AzureSandboxAutoSuspendMode
    {
        None = 0,
        Memory = 1,
        Disk = 2
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureSandboxEndpointOptions
    {
        public bool? Anonymous { get { throw null; } set { } }

        public string? Name { get { throw null; } set { } }
    }

    [AspireExport]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureSandboxGroupResource : AzureProvisioningResource, IAzureComputeEnvironmentResource, ApplicationModel.IComputeEnvironmentResource, ApplicationModel.IResource
    {
        public AzureSandboxGroupResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        IAzureContainerRegistryResource? IAzureComputeEnvironmentResource.ContainerRegistry { get { throw null; } }

        public AzureContainerRegistryResource? ContainerRegistry { get { throw null; } }

        public BicepOutputReference IdOutputReference { get { throw null; } }

        public BicepOutputReference LocationOutputReference { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRECOMPUTE002", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public ApplicationModel.ReferenceExpression GetEndpointPropertyExpression(ApplicationModel.EndpointReferenceExpression endpointReferenceExpression) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRECOMPUTE002", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public ApplicationModel.ReferenceExpression GetHostAddressExpression(ApplicationModel.EndpointReference endpointReference) { throw null; }
    }

    [AspireDto]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class AzureSandboxOptions
    {
        public bool? AutoDeleteEnabled { get { throw null; } set { } }

        public System.TimeSpan? AutoDeleteInterval { get { throw null; } set { } }

        public AzureSandboxAutoDeleteTrigger? AutoDeleteTrigger { get { throw null; } set { } }

        public bool? AutoSuspendEnabled { get { throw null; } set { } }

        public System.TimeSpan? AutoSuspendInterval { get { throw null; } set { } }

        public AzureSandboxAutoSuspendMode? AutoSuspendMode { get { throw null; } set { } }

        public AzureSandboxEndpointOptions[]? Endpoints { get { throw null; } set { } }

        public System.TimeSpan? PublicEndpointReadyTimeout { get { throw null; } set { } }

        public AzureSandboxTier Tier { get { throw null; } set { } }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREAZURE001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public enum AzureSandboxTier
    {
        ExtraSmall = 0,
        Small = 1,
        Medium = 2,
        Large = 3,
        ExtraLarge = 4
    }
}