// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Aspire.Hosting.ApplicationModel;

/// <summary>
/// Represents an annotation that overrides the default project launch arguments
/// generated by DCP for a <see cref="ProjectResource"/>.
/// </summary>
/// <remarks>
/// <para>
/// When this annotation is present on a <see cref="ProjectResource"/>, DCP will use the provided
/// arguments as the base command (e.g., <c>build /t:Run</c>) instead of the default <c>run</c> verb.
/// DCP still appends the project path and <c>--configuration</c> automatically; only the verb and
/// its options are overridden. The <c>--no-launch-profile</c> flag is omitted when this annotation
/// is present.
/// </para>
/// </remarks>
/// <example>
/// Override DCP's default launch to use <c>dotnet build /t:Run</c>:
/// <code>
/// builder.WithAnnotation(new ProjectLaunchArgsOverrideAnnotation(["build", "/t:Run"]));
/// </code>
/// </example>
[Experimental("ASPIREMAUI001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
[DebuggerDisplay("Type = {GetType().Name,nq}, Args = {string.Join(\" \", Args)}")]
public sealed class ProjectLaunchArgsOverrideAnnotation(IReadOnlyList<string> args) : IResourceAnnotation
{
    /// <summary>
    /// Gets the custom launch arguments to use instead of the default project args.
    /// </summary>
    public IReadOnlyList<string> Args { get; } = ValidateArgs(args);

    private static IReadOnlyList<string> ValidateArgs(IReadOnlyList<string> args)
    {
        ArgumentNullException.ThrowIfNull(args);

        if (args.Count == 0)
        {
            throw new ArgumentException("Launch arguments must contain at least one entry.", nameof(args));
        }

        return args;
    }
}
