//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgentCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.AgentCommandStrings", typeof(AgentCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage AI agent environment configuration..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start the MCP (Model Context Protocol) server..
        /// </summary>
        internal static string McpCommand_Description {
            get {
                return ResourceManager.GetString("McpCommand_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure independent assets for selected agent clients at project and user level.
        /// </summary>
        internal static string InitCommand_Description {
            get {
                return ResourceManager.GetString("InitCommand_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} config uses deprecated 'mcp start' command.
        /// </summary>
        internal static string DeprecatedConfigWarning {
            get {
                return ResourceManager.GetString("DeprecatedConfigWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run 'aspire agent init --mcp' and select the affected clients to update configuration.
        /// </summary>
        internal static string DeprecatedConfigFix {
            get {
                return ResourceManager.GetString("DeprecatedConfigFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration completed with errors. Please fix the reported issues and re-run the command..
        /// </summary>
        internal static string ConfigurationCompletedWithErrors {
            get {
                return ResourceManager.GetString("ConfigurationCompletedWithErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure the Aspire MCP server for the selected clients?.
        /// </summary>
        internal static string InitCommand_ConfigureMcpServerPrompt {
            get {
                return ResourceManager.GetString("InitCommand_ConfigureMcpServerPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Playwright CLI..
        /// </summary>
        internal static string InitCommand_InstalledPlaywrightCli {
            get {
                return ResourceManager.GetString("InitCommand_InstalledPlaywrightCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playwright CLI requires npm, which was not found on PATH. Skipping installation..
        /// </summary>
        internal static string InitCommand_PlaywrightCliSkipped {
            get {
                return ResourceManager.GetString("InitCommand_PlaywrightCliSkipped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0} skill at {1}: {2}..
        /// </summary>
        internal static string InitCommand_FailedToInstallSkill {
            get {
                return ResourceManager.GetString("InitCommand_FailedToInstallSkill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browser automation and functional testing.
        /// </summary>
        internal static string SkillDescription_PlaywrightCli {
            get {
                return ResourceManager.GetString("SkillDescription_PlaywrightCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installing Playwright CLI....
        /// </summary>
        internal static string PlaywrightCliInstaller_InstallingStatus {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InstallingStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve {0} from the npm registry..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToResolvePackage {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToResolvePackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value of configuration setting &apos;{0}&apos; (&apos;{1}&apos;) is not a valid SemVer 2.0 version..
        /// </summary>
        internal static string PlaywrightCliInstaller_InvalidVersionOverride {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InvalidVersionOverride", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provenance verification failed for {0}: {1}.
        /// </summary>
        internal static string PlaywrightCliInstaller_ProvenanceVerificationFailed {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_ProvenanceVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to download {0}..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToDownload {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integrity verification failed for {0}. The downloaded package may have been tampered with..
        /// </summary>
        internal static string PlaywrightCliInstaller_IntegrityVerificationFailed {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_IntegrityVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0} globally via npm..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToInstallGlobally {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToInstallGlobally", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to generate Playwright CLI skill files..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToGenerateSkillFiles {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToGenerateSkillFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Playwright CLI (some locations failed to mirror)..
        /// </summary>
        internal static string PlaywrightCliInstaller_InstalledWithMirrorWarnings {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InstalledWithMirrorWarnings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path to the workspace root directory.
        /// </summary>
        internal static string InitCommand_WorkspaceRootOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_WorkspaceRootOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure the Aspire MCP server for selected clients (y/n or true/false; default: no).
        /// </summary>
        internal static string InitCommand_McpOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_McpOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record AI agent skill and tool usage telemetry. Invoked by the Aspire agent telemetry hook scripts; not intended to be run directly..
        /// </summary>
        internal static string AgentTelemetryCommand_Description {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The telemetry event type (skill_invocation, tool_invocation, or reference_file_read).
        /// </summary>
        internal static string AgentTelemetryCommand_EventTypeDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_EventTypeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The AI agent client that produced the event (for example copilot-cli, claude-code, or vscode).
        /// </summary>
        internal static string AgentTelemetryCommand_ClientNameDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_ClientNameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The opaque AI agent session identifier.
        /// </summary>
        internal static string AgentTelemetryCommand_SessionIdDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_SessionIdDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire skill name for a skill_invocation event.
        /// </summary>
        internal static string AgentTelemetryCommand_SkillNameDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_SkillNameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire MCP tool name for a tool_invocation event.
        /// </summary>
        internal static string AgentTelemetryCommand_ToolNameDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_ToolNameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire skills-relative reference file path for a reference_file_read event.
        /// </summary>
        internal static string AgentTelemetryCommand_FileReferenceDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_FileReferenceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The timestamp recorded for the event.
        /// </summary>
        internal static string AgentTelemetryCommand_TimestampDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_TimestampDescription", resourceCulture);
            }
        }
    }
}
