//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgentSkillInstallerStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentSkillInstallerStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.AgentSkillInstallerStrings", typeof(AgentSkillInstallerStrings).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install Playwright CLI or generate its skill files: {0}.
        /// </summary>
        internal static string PlaywrightInstallationFailed {
            get {
                return ResourceManager.GetString("PlaywrightInstallationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The generated Playwright CLI skill contains a symbolic link: {0}.
        /// </summary>
        internal static string PlaywrightLinkedSkillEntry {
            get {
                return ResourceManager.GetString("PlaywrightLinkedSkillEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playwright CLI reported success, but did not generate a non-empty SKILL.md.
        /// </summary>
        internal static string PlaywrightMissingSkill {
            get {
                return ResourceManager.GetString("PlaywrightMissingSkill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playwright CLI requires npm, which was not found on PATH. Install npm and run agent init again.
        /// </summary>
        internal static string PlaywrightNpmRequired {
            get {
                return ResourceManager.GetString("PlaywrightNpmRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The skill file resolves outside the selected skill directory: {0}.
        /// </summary>
        internal static string SkillFileOutsideTarget {
            get {
                return ResourceManager.GetString("SkillFileOutsideTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The skill directory could not be resolved. Check for inaccessible paths or broken symbolic links.
        /// </summary>
        internal static string SkillTargetUnresolved {
            get {
                return ResourceManager.GetString("SkillTargetUnresolved", resourceCulture);
            }
        }
    }
}
