//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Aspire.Cli.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal static class AgentConfigurationStrings
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new global::System.Resources.ResourceManager("Aspire.Cli.Resources.AgentConfigurationStrings", typeof(AgentConfigurationStrings).Assembly);

    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static string Registered => ResourceManager.GetString("Registered", resourceCulture)!;
    internal static string McpConfigured => ResourceManager.GetString("McpConfigured", resourceCulture)!;
    internal static string Disabled => ResourceManager.GetString("Disabled", resourceCulture)!;
    internal static string Conflict => ResourceManager.GetString("Conflict", resourceCulture)!;
    internal static string ExistingMcpCustomization => ResourceManager.GetString("ExistingMcpCustomization", resourceCulture)!;
    internal static string UnexpectedShape => ResourceManager.GetString("UnexpectedShape", resourceCulture)!;
    internal static string ObjectRequired => ResourceManager.GetString("ObjectRequired", resourceCulture)!;
    internal static string MalformedJson => ResourceManager.GetString("MalformedJson", resourceCulture)!;
    internal static string ReadWriteFailed => ResourceManager.GetString("ReadWriteFailed", resourceCulture)!;
    internal static string ConcurrentChange => ResourceManager.GetString("ConcurrentChange", resourceCulture)!;
    internal static string UnsafeLink => ResourceManager.GetString("UnsafeLink", resourceCulture)!;
    internal static string PolicyBlocked => ResourceManager.GetString("PolicyBlocked", resourceCulture)!;
    internal static string OpenCodeSchemaConflict => ResourceManager.GetString("OpenCodeSchemaConflict", resourceCulture)!;
    internal static string OpenCodeCatalogVersionUnsupported => ResourceManager.GetString("OpenCodeCatalogVersionUnsupported", resourceCulture)!;
    internal static string OpenCodeMultipleFiles => ResourceManager.GetString("OpenCodeMultipleFiles", resourceCulture)!;
    internal static string UnsupportedOverride => ResourceManager.GetString("UnsupportedOverride", resourceCulture)!;
    internal static string HookConfigured => ResourceManager.GetString("HookConfigured", resourceCulture)!;
    internal static string HookNotApplicable => ResourceManager.GetString("HookNotApplicable", resourceCulture)!;
    internal static string HookInstallationFailed => ResourceManager.GetString("HookInstallationFailed", resourceCulture)!;
    internal static string ExistingProjectHook => ResourceManager.GetString("ExistingProjectHook", resourceCulture)!;
    internal static string ProfileLimitations => ResourceManager.GetString("ProfileLimitations", resourceCulture)!;
}
