//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgentCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.AgentCommandStrings", typeof(AgentCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage AI agent environment configuration..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start the MCP (Model Context Protocol) server..
        /// </summary>
        internal static string McpCommand_Description {
            get {
                return ResourceManager.GetString("McpCommand_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure independent assets for selected client environments at project and user level.
        /// </summary>
        internal static string InitCommand_Description {
            get {
                return ResourceManager.GetString("InitCommand_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} config uses deprecated 'mcp start' command.
        /// </summary>
        internal static string DeprecatedConfigWarning {
            get {
                return ResourceManager.GetString("DeprecatedConfigWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run 'aspire agent init --mcp' and select the affected client environments to update configuration.
        /// </summary>
        internal static string DeprecatedConfigFix {
            get {
                return ResourceManager.GetString("DeprecatedConfigFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration completed with errors. Please fix the reported issues and re-run the command..
        /// </summary>
        internal static string ConfigurationCompletedWithErrors {
            get {
                return ResourceManager.GetString("ConfigurationCompletedWithErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure the Aspire MCP server for the selected client environments?.
        /// </summary>
        internal static string InitCommand_ConfigureMcpServerPrompt {
            get {
                return ResourceManager.GetString("InitCommand_ConfigureMcpServerPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Playwright CLI..
        /// </summary>
        internal static string InitCommand_InstalledPlaywrightCli {
            get {
                return ResourceManager.GetString("InitCommand_InstalledPlaywrightCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playwright CLI requires npm, which was not found on PATH. Skipping installation..
        /// </summary>
        internal static string InitCommand_PlaywrightCliSkipped {
            get {
                return ResourceManager.GetString("InitCommand_PlaywrightCliSkipped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0} skill at {1}: {2}..
        /// </summary>
        internal static string InitCommand_FailedToInstallSkill {
            get {
                return ResourceManager.GetString("InitCommand_FailedToInstallSkill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browser automation and functional testing.
        /// </summary>
        internal static string SkillDescription_PlaywrightCli {
            get {
                return ResourceManager.GetString("SkillDescription_PlaywrightCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installing Playwright CLI....
        /// </summary>
        internal static string PlaywrightCliInstaller_InstallingStatus {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InstallingStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve {0} from the npm registry..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToResolvePackage {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToResolvePackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value of configuration setting &apos;{0}&apos; (&apos;{1}&apos;) is not a valid SemVer 2.0 version..
        /// </summary>
        internal static string PlaywrightCliInstaller_InvalidVersionOverride {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InvalidVersionOverride", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provenance verification failed for {0}: {1}.
        /// </summary>
        internal static string PlaywrightCliInstaller_ProvenanceVerificationFailed {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_ProvenanceVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to download {0}..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToDownload {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integrity verification failed for {0}. The downloaded package may have been tampered with..
        /// </summary>
        internal static string PlaywrightCliInstaller_IntegrityVerificationFailed {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_IntegrityVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0} globally via npm..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToInstallGlobally {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToInstallGlobally", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to generate Playwright CLI skill files..
        /// </summary>
        internal static string PlaywrightCliInstaller_FailedToGenerateSkillFiles {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_FailedToGenerateSkillFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Playwright CLI (some locations failed to mirror)..
        /// </summary>
        internal static string PlaywrightCliInstaller_InstalledWithMirrorWarnings {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InstalledWithMirrorWarnings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path to the workspace root directory.
        /// </summary>
        internal static string InitCommand_WorkspaceRootOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_WorkspaceRootOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure the Aspire MCP server for selected client environments (y/n or true/false; default: no).
        /// </summary>
        internal static string InitCommand_McpOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_McpOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record AI agent skill and tool usage telemetry. Invoked by the Aspire agent telemetry hook scripts; not intended to be run directly..
        /// </summary>
        internal static string AgentTelemetryCommand_Description {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The telemetry event type (skill_invocation, tool_invocation, or reference_file_read).
        /// </summary>
        internal static string AgentTelemetryCommand_EventTypeDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_EventTypeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The AI agent client that produced the event (for example copilot-cli, claude-code, or vscode).
        /// </summary>
        internal static string AgentTelemetryCommand_ClientNameDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_ClientNameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The opaque AI agent session identifier.
        /// </summary>
        internal static string AgentTelemetryCommand_SessionIdDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_SessionIdDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire skill name for a skill_invocation event.
        /// </summary>
        internal static string AgentTelemetryCommand_SkillNameDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_SkillNameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire MCP tool name for a tool_invocation event.
        /// </summary>
        internal static string AgentTelemetryCommand_ToolNameDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_ToolNameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire skills-relative reference file path for a reference_file_read event.
        /// </summary>
        internal static string AgentTelemetryCommand_FileReferenceDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_FileReferenceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The timestamp recorded for the event.
        /// </summary>
        internal static string AgentTelemetryCommand_TimestampDescription {
            get {
                return ResourceManager.GetString("AgentTelemetryCommand_TimestampDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install Playwright CLI and its skills for the selected client environments (y/n or true/false; default: no).
        /// </summary>
        internal static string InitCommand_PlaywrightOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_PlaywrightOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install the dotnet-inspect bootstrap skill for the selected client environments (y/n or true/false; default: no).
        /// </summary>
        internal static string InitCommand_DotnetInspectOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_DotnetInspectOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register native Aspire skills and supported canvases for the selected client environments (y/n or true/false; default: yes).
        /// </summary>
        internal static string InitCommand_AspireSkillsOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_AspireSkillsOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comma-separated client environments ({0}), '{1}', or '{2}'. Defaults to detected environments.
        /// </summary>
        internal static string InitCommand_EnvironmentsOptionDescription {
            get {
                return ResourceManager.GetString("InitCommand_EnvironmentsOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid value '{1}' for '{0}'. Use y/n or true/false..
        /// </summary>
        internal static string InitCommand_InvalidAssetValue {
            get {
                return ResourceManager.GetString("InitCommand_InvalidAssetValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid client environment selection '{0}'. Use {1}, '{2}', or '{3}'..
        /// </summary>
        internal static string InitCommand_InvalidEnvironments {
            get {
                return ResourceManager.GetString("InitCommand_InvalidEnvironments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install the dotnet-inspect bootstrap skill?.
        /// </summary>
        internal static string InitCommand_ConfigureDotnetInspectPrompt {
            get {
                return ResourceManager.GetString("InitCommand_ConfigureDotnetInspectPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register Aspire skills and supported canvases?.
        /// </summary>
        internal static string InitCommand_ConfigureAspireSkillsPrompt {
            get {
                return ResourceManager.GetString("InitCommand_ConfigureAspireSkillsPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No agent configuration selected. Existing configuration was left unchanged..
        /// </summary>
        internal static string InitCommand_NoConfigurationSelected {
            get {
                return ResourceManager.GetString("InitCommand_NoConfigurationSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to project.
        /// </summary>
        internal static string InitCommand_ProjectScope {
            get {
                return ResourceManager.GetString("InitCommand_ProjectScope", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string InitCommand_UserScope {
            get {
                return ResourceManager.GetString("InitCommand_UserScope", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire MCP server.
        /// </summary>
        internal static string InitCommand_McpAsset {
            get {
                return ResourceManager.GetString("InitCommand_McpAsset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playwright CLI skill.
        /// </summary>
        internal static string InitCommand_PlaywrightAsset {
            get {
                return ResourceManager.GetString("InitCommand_PlaywrightAsset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dotnet-inspect skill.
        /// </summary>
        internal static string InitCommand_DotnetInspectAsset {
            get {
                return ResourceManager.GetString("InitCommand_DotnetInspectAsset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire source.
        /// </summary>
        internal static string InitCommand_AspireSkillsAsset {
            get {
                return ResourceManager.GetString("InitCommand_AspireSkillsAsset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire usage telemetry hooks.
        /// </summary>
        internal static string InitCommand_TelemetryHooksAsset {
            get {
                return ResourceManager.GetString("InitCommand_TelemetryHooksAsset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registered {0} for {1} ({2}): {3}.
        /// </summary>
        internal static string InitCommand_RegisteredTarget {
            get {
                return ResourceManager.GetString("InitCommand_RegisteredTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed {0} for {1} ({2}): {3}.
        /// </summary>
        internal static string InitCommand_InstalledTarget {
            get {
                return ResourceManager.GetString("InitCommand_InstalledTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configured {0} for {1} ({2}): {3}.
        /// </summary>
        internal static string InitCommand_ConfiguredTarget {
            get {
                return ResourceManager.GetString("InitCommand_ConfiguredTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already configured {0} for {1} ({2}): {3}.
        /// </summary>
        internal static string InitCommand_UnchangedTarget {
            get {
                return ResourceManager.GetString("InitCommand_UnchangedTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipped {0} for {1} ({2}): {3}.
        /// </summary>
        internal static string InitCommand_SkippedTarget {
            get {
                return ResourceManager.GetString("InitCommand_SkippedTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blocked {0} for {1} ({2}): {3}.
        /// </summary>
        internal static string InitCommand_BlockedTarget {
            get {
                return ResourceManager.GetString("InitCommand_BlockedTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to configure {0} for {1} ({2}): {3}.
        /// </summary>
        internal static string InitCommand_FailedTarget {
            get {
                return ResourceManager.GetString("InitCommand_FailedTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The selected clients acquire and load the registered Aspire content. Client trust or activation may still be required; registration does not mean the content is installed or loaded..
        /// </summary>
        internal static string InitCommand_ClientAcquisitionNotice {
            get {
                return ResourceManager.GetString("InitCommand_ClientAcquisitionNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agent configuration completed with warnings. Review the skipped or unavailable targets above..
        /// </summary>
        internal static string ConfigurationCompletedWithWarnings {
            get {
                return ResourceManager.GetString("ConfigurationCompletedWithWarnings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire AppHost created! Open this project in {0}. After the client acquires the Aspire content, ask it to run the aspireify skill to complete setup..
        /// </summary>
        internal static string InitCommand_AspireifyHandoff {
            get {
                return ResourceManager.GetString("InitCommand_AspireifyHandoff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Native source registered. The client owns acquisition, trust, and loading; managed policy and runtime overrides are not fully verifiable offline..
        /// </summary>
        internal static string Configuration_Registered {
            get {
                return ResourceManager.GetString("Configuration_Registered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire MCP configuration is present. The client controls trust, policy, and server startup..
        /// </summary>
        internal static string Configuration_McpConfigured {
            get {
                return ResourceManager.GetString("Configuration_McpConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An existing disabled choice was preserved; this entry was not enabled..
        /// </summary>
        internal static string Configuration_Disabled {
            get {
                return ResourceManager.GetString("Configuration_Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An existing Aspire entry has a different source or command; it was not replaced..
        /// </summary>
        internal static string Configuration_Conflict {
            get {
                return ResourceManager.GetString("Configuration_Conflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Existing Aspire MCP settings in another applicable scope were preserved. No default entry was added that could override or broaden those customizations..
        /// </summary>
        internal static string Configuration_ExistingMcpCustomization {
            get {
                return ResourceManager.GetString("Configuration_ExistingMcpCustomization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A pinned Aspire plugin source was preserved. No unpinned source was added to another configuration scope.
        /// </summary>
        internal static string Configuration_ExistingPluginPin {
            get {
                return ResourceManager.GetString("Configuration_ExistingPluginPin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration has an unsupported JSON shape at '{0}'; this entry was left unchanged..
        /// </summary>
        internal static string Configuration_UnexpectedShape {
            get {
                return ResourceManager.GetString("Configuration_UnexpectedShape", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration is not valid JSON/JSONC; the file was left unchanged..
        /// </summary>
        internal static string Configuration_MalformedJson {
            get {
                return ResourceManager.GetString("Configuration_MalformedJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read or write the configuration: {0}.
        /// </summary>
        internal static string Configuration_ReadWriteFailed {
            get {
                return ResourceManager.GetString("Configuration_ReadWriteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration or one of its overrides changed during setup. Retry after the other writer has finished..
        /// </summary>
        internal static string Configuration_ConcurrentChange {
            get {
                return ResourceManager.GetString("Configuration_ConcurrentChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration link '{0}' could not be resolved safely; it was left unchanged..
        /// </summary>
        internal static string Configuration_UnsafeLink {
            get {
                return ResourceManager.GetString("Configuration_UnsafeLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An existing policy or higher-precedence override controls this entry. It was preserved; review it in the client before enabling Aspire..
        /// </summary>
        internal static string Configuration_PolicyBlocked {
            get {
                return ResourceManager.GetString("Configuration_PolicyBlocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OpenCode version and configuration evidence do not establish one compatible V1 or V2 schema. Existing files were not converted..
        /// </summary>
        internal static string Configuration_OpenCodeSchemaConflict {
            get {
                return ResourceManager.GetString("Configuration_OpenCodeSchemaConflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The detected OpenCode version ({0}) does not support skills.urls catalogs. Upgrade to OpenCode {1} or later; the catalog configuration was left unchanged..
        /// </summary>
        internal static string Configuration_OpenCodeCatalogVersionUnsupported {
            get {
                return ResourceManager.GetString("Configuration_OpenCodeCatalogVersionUnsupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple OpenCode configuration files apply at this scope. Consolidate them before configuring Aspire..
        /// </summary>
        internal static string Configuration_OpenCodeMultipleFiles {
            get {
                return ResourceManager.GetString("Configuration_OpenCodeMultipleFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user-level Aspire usage hook is configured. Telemetry opt-out settings still apply..
        /// </summary>
        internal static string Configuration_HookConfigured {
            get {
                return ResourceManager.GetString("Configuration_HookConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not prepare the embedded usage hook scripts: {0}.
        /// </summary>
        internal static string Configuration_HookInstallationFailed {
            get {
                return ResourceManager.GetString("Configuration_HookInstallationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An existing project-level Aspire usage hook was preserved. No additional user hook was added, to avoid duplicate events..
        /// </summary>
        internal static string Configuration_ExistingProjectHook {
            get {
                return ResourceManager.GetString("Configuration_ExistingProjectHook", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire MCP configuration is present for this VS Code profile. Session-only --user-data-dir overrides and remote profiles must be configured in VS Code..
        /// </summary>
        internal static string Configuration_ProfileLimitations {
            get {
                return ResourceManager.GetString("Configuration_ProfileLimitations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install Playwright CLI or generate its skill files: {0}.
        /// </summary>
        internal static string PlaywrightCliInstaller_InstallationFailed {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_InstallationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The generated Playwright CLI skill contains a symbolic link: {0}.
        /// </summary>
        internal static string PlaywrightCliInstaller_LinkedSkillEntry {
            get {
                return ResourceManager.GetString("PlaywrightCliInstaller_LinkedSkillEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The skill file resolves outside the selected skill directory: {0}.
        /// </summary>
        internal static string InitCommand_SkillFileOutsideTarget {
            get {
                return ResourceManager.GetString("InitCommand_SkillFileOutsideTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Describes shared locations and separately detected usage hooks.
        /// </summary>
        internal static string InitCommand_EnvironmentSelectionNotice {
            get {
                return ResourceManager.GetString("InitCommand_EnvironmentSelectionNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string InitCommand_EnvironmentLocationDescription {
            get {
                return ResourceManager.GetString("InitCommand_EnvironmentLocationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} (including shared alternatives).
        /// </summary>
        internal static string InitCommand_ScopeWithSharedAlternatives {
            get {
                return ResourceManager.GetString("InitCommand_ScopeWithSharedAlternatives", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub Copilot (CLI and App).
        /// </summary>
        internal static string Environment_Copilot {
            get {
                return ResourceManager.GetString("Environment_Copilot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VS Code (native settings).
        /// </summary>
        internal static string Environment_VsCode {
            get {
                return ResourceManager.GetString("Environment_VsCode", resourceCulture);
            }
        }
    }
}
