//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgentInitStrings {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal AgentInitStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.AgentInitStrings", typeof(AgentInitStrings).Assembly);
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string PlaywrightOptionDescription {
            get { return ResourceManager.GetString("PlaywrightOptionDescription", resourceCulture); }
        }

        internal static string DotnetInspectOptionDescription {
            get { return ResourceManager.GetString("DotnetInspectOptionDescription", resourceCulture); }
        }

        internal static string AspireSkillsOptionDescription {
            get { return ResourceManager.GetString("AspireSkillsOptionDescription", resourceCulture); }
        }

        internal static string ClientsOptionDescription {
            get { return ResourceManager.GetString("ClientsOptionDescription", resourceCulture); }
        }

        internal static string InvalidAssetValue {
            get { return ResourceManager.GetString("InvalidAssetValue", resourceCulture); }
        }

        internal static string InvalidClients {
            get { return ResourceManager.GetString("InvalidClients", resourceCulture); }
        }

        internal static string ConfigurePlaywrightPrompt {
            get { return ResourceManager.GetString("ConfigurePlaywrightPrompt", resourceCulture); }
        }

        internal static string ConfigureDotnetInspectPrompt {
            get { return ResourceManager.GetString("ConfigureDotnetInspectPrompt", resourceCulture); }
        }

        internal static string ConfigureAspireSkillsPrompt {
            get { return ResourceManager.GetString("ConfigureAspireSkillsPrompt", resourceCulture); }
        }

        internal static string SelectClients {
            get { return ResourceManager.GetString("SelectClients", resourceCulture); }
        }

        internal static string NoAssetsSelected {
            get { return ResourceManager.GetString("NoAssetsSelected", resourceCulture); }
        }

        internal static string NoClientsSelected {
            get { return ResourceManager.GetString("NoClientsSelected", resourceCulture); }
        }

        internal static string ProjectScope {
            get { return ResourceManager.GetString("ProjectScope", resourceCulture); }
        }

        internal static string UserScope {
            get { return ResourceManager.GetString("UserScope", resourceCulture); }
        }

        internal static string McpAsset {
            get { return ResourceManager.GetString("McpAsset", resourceCulture); }
        }

        internal static string PlaywrightAsset {
            get { return ResourceManager.GetString("PlaywrightAsset", resourceCulture); }
        }

        internal static string DotnetInspectAsset {
            get { return ResourceManager.GetString("DotnetInspectAsset", resourceCulture); }
        }

        internal static string AspireSkillsAsset {
            get { return ResourceManager.GetString("AspireSkillsAsset", resourceCulture); }
        }

        internal static string TelemetryHooksAsset {
            get { return ResourceManager.GetString("TelemetryHooksAsset", resourceCulture); }
        }

        internal static string RegisteredTarget {
            get { return ResourceManager.GetString("RegisteredTarget", resourceCulture); }
        }

        internal static string InstalledTarget {
            get { return ResourceManager.GetString("InstalledTarget", resourceCulture); }
        }

        internal static string ConfiguredTarget {
            get { return ResourceManager.GetString("ConfiguredTarget", resourceCulture); }
        }

        internal static string UnchangedTarget {
            get { return ResourceManager.GetString("UnchangedTarget", resourceCulture); }
        }

        internal static string SkippedTarget {
            get { return ResourceManager.GetString("SkippedTarget", resourceCulture); }
        }

        internal static string BlockedTarget {
            get { return ResourceManager.GetString("BlockedTarget", resourceCulture); }
        }

        internal static string FailedTarget {
            get { return ResourceManager.GetString("FailedTarget", resourceCulture); }
        }

        internal static string ClientAcquisitionNotice {
            get { return ResourceManager.GetString("ClientAcquisitionNotice", resourceCulture); }
        }

        internal static string ConfigurationCompletedWithWarnings {
            get { return ResourceManager.GetString("ConfigurationCompletedWithWarnings", resourceCulture); }
        }

        internal static string AspireifyHandoff {
            get { return ResourceManager.GetString("AspireifyHandoff", resourceCulture); }
        }
    }
}
