//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeckCommandStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeckCommandStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.DeckCommandStrings", typeof(DeckCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        public static string OtlpGrpcUrlOptionDescription {
            get {
                return ResourceManager.GetString("OtlpGrpcUrlOptionDescription", resourceCulture);
            }
        }

        public static string OtlpHttpUrlOptionDescription {
            get {
                return ResourceManager.GetString("OtlpHttpUrlOptionDescription", resourceCulture);
            }
        }

        public static string ResourceServiceUrlOptionDescription {
            get {
                return ResourceManager.GetString("ResourceServiceUrlOptionDescription", resourceCulture);
            }
        }

        public static string DeckPathOptionDescription {
            get {
                return ResourceManager.GetString("DeckPathOptionDescription", resourceCulture);
            }
        }

        public static string DeckExecutableNotFound {
            get {
                return ResourceManager.GetString("DeckExecutableNotFound", resourceCulture);
            }
        }

        public static string DeckFailedToStart {
            get {
                return ResourceManager.GetString("DeckFailedToStart", resourceCulture);
            }
        }

        public static string DeckExitedWithError {
            get {
                return ResourceManager.GetString("DeckExitedWithError", resourceCulture);
            }
        }

        public static string StoppingDeck {
            get {
                return ResourceManager.GetString("StoppingDeck", resourceCulture);
            }
        }

        public static string OtlpGrpcLabel {
            get {
                return ResourceManager.GetString("OtlpGrpcLabel", resourceCulture);
            }
        }

        public static string OtlpHttpLabel {
            get {
                return ResourceManager.GetString("OtlpHttpLabel", resourceCulture);
            }
        }

        public static string ResourceServiceLabel {
            get {
                return ResourceManager.GetString("ResourceServiceLabel", resourceCulture);
            }
        }

        public static string ResourceServiceNotConfigured {
            get {
                return ResourceManager.GetString("ResourceServiceNotConfigured", resourceCulture);
            }
        }

        public static string LogsLabel {
            get {
                return ResourceManager.GetString("LogsLabel", resourceCulture);
            }
        }

        public static string DeckLaunched {
            get {
                return ResourceManager.GetString("DeckLaunched", resourceCulture);
            }
        }

        public static string DeckAttached {
            get {
                return ResourceManager.GetString("DeckAttached", resourceCulture);
            }
        }

        public static string DeckAttachFailed {
            get {
                return ResourceManager.GetString("DeckAttachFailed", resourceCulture);
            }
        }

        public static string DeckAlreadyRunning {
            get {
                return ResourceManager.GetString("DeckAlreadyRunning", resourceCulture);
            }
        }
    }
}
