//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DoctorCommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DoctorCommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.DoctorCommandStrings", typeof(DoctorCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Aspire prerequisites and environment setup.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output results as JSON for tooling integration.
        /// </summary>
        public static string JsonOptionDescription {
            get {
                return ResourceManager.GetString("JsonOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspire Environment Check.
        /// </summary>
        public static string EnvironmentCheckHeader {
            get {
                return ResourceManager.GetString("EnvironmentCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET SDK.
        /// </summary>
        public static string SdkCategoryHeader {
            get {
                return ResourceManager.GetString("SdkCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Runtime.
        /// </summary>
        public static string ContainerCategoryHeader {
            get {
                return ResourceManager.GetString("ContainerCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string EnvironmentCategoryHeader {
            get {
                return ResourceManager.GetString("EnvironmentCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary: {0} passed, {1} warnings, {2} failed.
        /// </summary>
        public static string SummaryFormat {
            get {
                return ResourceManager.GetString("SummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For detailed prerequisites: https://aka.ms/aspire-prerequisites.
        /// </summary>
        public static string DetailedPrerequisitesLink {
            get {
                return ResourceManager.GetString("DetailedPrerequisitesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Aspire prerequisites....
        /// </summary>
        public static string CheckingPrerequisites {
            get {
                return ResourceManager.GetString("CheckingPrerequisites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Polyglot AppHost.
        /// </summary>
        public static string PolyglotCategoryHeader {
            get {
                return ResourceManager.GetString("PolyglotCategoryHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is installed.
        /// </summary>
        public static string PackageManagerInstalled {
            get {
                return ResourceManager.GetString("PackageManagerInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is installed.
        /// </summary>
        public static string PackageManagerInstalledNoVersion {
            get {
                return ResourceManager.GetString("PackageManagerInstalledNoVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} not found but required by this TypeScript AppHost.
        /// </summary>
        public static string PackageManagerMissing {
            get {
                return ResourceManager.GetString("PackageManagerMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install {0} to run this TypeScript AppHost..
        /// </summary>
        public static string PackageManagerMissingFix {
            get {
                return ResourceManager.GetString("PackageManagerMissingFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to npx not found but required by npm-managed TypeScript AppHosts.
        /// </summary>
        public static string NpxMissing {
            get {
                return ResourceManager.GetString("NpxMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to npx ships with Node.js; ensure your Node.js installation is on PATH..
        /// </summary>
        public static string NpxMissingFix {
            get {
                return ResourceManager.GetString("NpxMissingFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yarn Classic (v1) detected; Aspire supports Yarn 4 or later.
        /// </summary>
        public static string YarnClassicUnsupported {
            get {
                return ResourceManager.GetString("YarnClassicUnsupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Yarn 4+ via 'corepack prepare yarn@stable --activate' or follow the Yarn install guide..
        /// </summary>
        public static string YarnClassicUnsupportedFix {
            get {
                return ResourceManager.GetString("YarnClassicUnsupportedFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Node.js not found but required by this TypeScript AppHost.
        /// </summary>
        public static string NodeJsMissing {
            get {
                return ResourceManager.GetString("NodeJsMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install Node.js 20.19+ or 22.13+ from https://nodejs.org/..
        /// </summary>
        public static string NodeJsMissingFix {
            get {
                return ResourceManager.GetString("NodeJsMissingFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Node.js {0} is below the supported version (20.19+ or 22.13+).
        /// </summary>
        public static string NodeJsOutdated {
            get {
                return ResourceManager.GetString("NodeJsOutdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upgrade Node.js to 20.19+ or 22.13+ from https://nodejs.org/..
        /// </summary>
        public static string NodeJsOutdatedFix {
            get {
                return ResourceManager.GetString("NodeJsOutdatedFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Node.js {0} is installed.
        /// </summary>
        public static string NodeJsInstalled {
            get {
                return ResourceManager.GetString("NodeJsInstalled", resourceCulture);
            }
        }
    }
}
