//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.InfoCommandStrings", typeof(InfoCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Description => ResourceManager.GetString("Description", resourceCulture);

        internal static string SelfOptionDescription => ResourceManager.GetString("SelfOptionDescription", resourceCulture);

        internal static string AllOptionDescription => ResourceManager.GetString("AllOptionDescription", resourceCulture);

        internal static string FormatOptionDescription => ResourceManager.GetString("FormatOptionDescription", resourceCulture);

        internal static string HeaderInstallations => ResourceManager.GetString("HeaderInstallations", resourceCulture);

        internal static string ColumnPath => ResourceManager.GetString("ColumnPath", resourceCulture);

        internal static string ColumnVersion => ResourceManager.GetString("ColumnVersion", resourceCulture);

        internal static string ColumnChannel => ResourceManager.GetString("ColumnChannel", resourceCulture);

        internal static string ColumnRoute => ResourceManager.GetString("ColumnRoute", resourceCulture);

        internal static string ColumnOnPath => ResourceManager.GetString("ColumnOnPath", resourceCulture);

        internal static string ValueCurrentMarker => ResourceManager.GetString("ValueCurrentMarker", resourceCulture);

        internal static string ValueUnknown => ResourceManager.GetString("ValueUnknown", resourceCulture);

        internal static string ValueNotProbed => ResourceManager.GetString("ValueNotProbed", resourceCulture);

        internal static string ValueYes => ResourceManager.GetString("ValueYes", resourceCulture);

        internal static string ValueNo => ResourceManager.GetString("ValueNo", resourceCulture);
    }
}
