//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MigrateCommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MigrateCommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.MigrateCommandStrings", typeof(MigrateCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate a legacy TypeScript AppHost (apphost.ts) to the recommended apphost.mts format..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform the migration without prompting for confirmation..
        /// </summary>
        internal static string YesOptionDescription {
            get {
                return ResourceManager.GetString("YesOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No legacy 'apphost.ts' AppHost was found in the current project. Nothing to migrate..
        /// </summary>
        internal static string NothingToMigrate {
            get {
                return ResourceManager.GetString("NothingToMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate '{0}' to '{1}'? This rewrites SDK imports and updates aspire.config.json and tsconfig.apphost.json..
        /// </summary>
        internal static string ConfirmPromptFormat {
            get {
                return ResourceManager.GetString("ConfirmPromptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration cancelled. No changes were made..
        /// </summary>
        internal static string MigrationCancelled {
            get {
                return ResourceManager.GetString("MigrationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating to apphost.mts.
        /// </summary>
        internal static string MigratingStatus {
            get {
                return ResourceManager.GetString("MigratingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerating SDK code.
        /// </summary>
        internal static string RegeneratingStatus {
            get {
                return ResourceManager.GetString("RegeneratingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrated '{0}' to '{1}'..
        /// </summary>
        internal static string MigrationSucceededFormat {
            get {
                return ResourceManager.GetString("MigrationSucceededFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed, but regenerating the SDK code failed. Run 'aspire restore' to regenerate it..
        /// </summary>
        internal static string RegenerateFailedWarning {
            get {
                return ResourceManager.GetString("RegenerateFailedWarning", resourceCulture);
            }
        }
    }
}
