//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PublishCommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublishCommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.PublishCommandStrings", typeof(PublishCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates deployment artifacts for an Aspire apphost.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating artifacts....
        /// </summary>
        public static string GeneratingArtifacts {
            get {
                return ResourceManager.GetString("GeneratingArtifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string InputPromptLoading {
            get {
                return ResourceManager.GetString("InputPromptLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not build or restore the project before running..
        /// </summary>
        public static string NoBuildArgumentDescription {
            get {
                return ResourceManager.GetString("NoBuildArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PUBLISHING COMPLETED.
        /// </summary>
        public static string OperationCompletedPrefix {
            get {
                return ResourceManager.GetString("OperationCompletedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLISHING FAILED.
        /// </summary>
        public static string OperationFailedPrefix {
            get {
                return ResourceManager.GetString("OperationFailedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output path for the generated artifacts. Defaults to the AppHost directory&apos;s &apos;aspire-output&apos; folder if not specified..
        /// </summary>
        public static string OutputPathArgumentDescription {
            get {
                return ResourceManager.GetString("OutputPathArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the Aspire apphost project file..
        /// </summary>
        public static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a publisher:.
        /// </summary>
        public static string SelectAPublisher {
            get {
                return ResourceManager.GetString("SelectAPublisher", resourceCulture);
            }
        }

        public static string VerificationFailed {
            get {
                return ResourceManager.GetString("VerificationFailed", resourceCulture);
            }
        }

        public static string VerificationSucceeded {
            get {
                return ResourceManager.GetString("VerificationSucceeded", resourceCulture);
            }
        }

        public static string VerifyAppHostDirectoryChanged {
            get {
                return ResourceManager.GetString("VerifyAppHostDirectoryChanged", resourceCulture);
            }
        }

        public static string VerifyAppHostDirectoryUnavailable {
            get {
                return ResourceManager.GetString("VerifyAppHostDirectoryUnavailable", resourceCulture);
            }
        }

        public static string VerifyDestinationLinkEscape {
            get {
                return ResourceManager.GetString("VerifyDestinationLinkEscape", resourceCulture);
            }
        }

        public static string VerifyDestinationOutsideRepository {
            get {
                return ResourceManager.GetString("VerifyDestinationOutsideRepository", resourceCulture);
            }
        }

        public static string VerifyDuplicateOutputs {
            get {
                return ResourceManager.GetString("VerifyDuplicateOutputs", resourceCulture);
            }
        }

        public static string VerifyFinalStateUnavailable {
            get {
                return ResourceManager.GetString("VerifyFinalStateUnavailable", resourceCulture);
            }
        }

        public static string VerifyGitQueryFailed {
            get {
                return ResourceManager.GetString("VerifyGitQueryFailed", resourceCulture);
            }
        }

        public static string VerifyGitUnavailable {
            get {
                return ResourceManager.GetString("VerifyGitUnavailable", resourceCulture);
            }
        }

        public static string VerifyHostingIncompatible {
            get {
                return ResourceManager.GetString("VerifyHostingIncompatible", resourceCulture);
            }
        }

        public static string VerifyInvalidDestinationPath {
            get {
                return ResourceManager.GetString("VerifyInvalidDestinationPath", resourceCulture);
            }
        }

        public static string VerifyLinkedOutputPath {
            get {
                return ResourceManager.GetString("VerifyLinkedOutputPath", resourceCulture);
            }
        }

        public static string VerifyListStepsNotSupported {
            get {
                return ResourceManager.GetString("VerifyListStepsNotSupported", resourceCulture);
            }
        }

        public static string VerifyMissingFilesHeader {
            get {
                return ResourceManager.GetString("VerifyMissingFilesHeader", resourceCulture);
            }
        }

        public static string VerifyNestedRepository {
            get {
                return ResourceManager.GetString("VerifyNestedRepository", resourceCulture);
            }
        }

        public static string VerifyOptionDescription {
            get {
                return ResourceManager.GetString("VerifyOptionDescription", resourceCulture);
            }
        }

        public static string VerifyOrphanedFilesHeader {
            get {
                return ResourceManager.GetString("VerifyOrphanedFilesHeader", resourceCulture);
            }
        }

        public static string VerifyOutputPlanChanged {
            get {
                return ResourceManager.GetString("VerifyOutputPlanChanged", resourceCulture);
            }
        }

        public static string VerifyOutputKindMismatch {
            get {
                return ResourceManager.GetString("VerifyOutputKindMismatch", resourceCulture);
            }
        }

        public static string VerifyOutputChangedDuringShutdown {
            get {
                return ResourceManager.GetString("VerifyOutputChangedDuringShutdown", resourceCulture);
            }
        }

        public static string VerifyOverlappingOutputs {
            get {
                return ResourceManager.GetString("VerifyOverlappingOutputs", resourceCulture);
            }
        }

        public static string VerifyPrimaryOutputMismatch {
            get {
                return ResourceManager.GetString("VerifyPrimaryOutputMismatch", resourceCulture);
            }
        }

        public static string VerifyRegenerateCommand {
            get {
                return ResourceManager.GetString("VerifyRegenerateCommand", resourceCulture);
            }
        }

        public static string VerifyStagingCleanupFailed {
            get {
                return ResourceManager.GetString("VerifyStagingCleanupFailed", resourceCulture);
            }
        }

        public static string VerifyStaleFilesHeader {
            get {
                return ResourceManager.GetString("VerifyStaleFilesHeader", resourceCulture);
            }
        }

        public static string VerifyUnexpectedOutputState {
            get {
                return ResourceManager.GetString("VerifyUnexpectedOutputState", resourceCulture);
            }
        }

        public static string VerifyUnknownOutputKind {
            get {
                return ResourceManager.GetString("VerifyUnknownOutputKind", resourceCulture);
            }
        }

        public static string VerifyUnsupportedSteps {
            get {
                return ResourceManager.GetString("VerifyUnsupportedSteps", resourceCulture);
            }
        }

        public static string VerifyWritablePathOutsideStaging {
            get {
                return ResourceManager.GetString("VerifyWritablePathOutsideStaging", resourceCulture);
            }
        }
    }
}
