//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCommandStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCommandStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.ResourceCommandStrings", typeof(ResourceCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string SelectAppHostAction {
            get {
                return ResourceManager.GetString("SelectAppHostAction", resourceCulture);
            }
        }

        internal static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }

        internal static string CommandResourceArgumentDescription {
            get {
                return ResourceManager.GetString("CommandResourceArgumentDescription", resourceCulture);
            }
        }

        internal static string CommandNameArgumentDescription {
            get {
                return ResourceManager.GetString("CommandNameArgumentDescription", resourceCulture);
            }
        }

        internal static string CommandArgumentsArgumentDescription {
            get {
                return ResourceManager.GetString("CommandArgumentsArgumentDescription", resourceCulture);
            }
        }

        internal static string CommandArgumentsOptionDescription {
            get {
                return ResourceManager.GetString("CommandArgumentsOptionDescription", resourceCulture);
            }
        }

        internal static string CommandArgumentsCannotMix {
            get {
                return ResourceManager.GetString("CommandArgumentsCannotMix", resourceCulture);
            }
        }

        internal static string CommandArgumentsJsonInvalid {
            get {
                return ResourceManager.GetString("CommandArgumentsJsonInvalid", resourceCulture);
            }
        }

        internal static string CommandArgumentsJsonInvalidObject {
            get {
                return ResourceManager.GetString("CommandArgumentsJsonInvalidObject", resourceCulture);
            }
        }

        internal static string CommandArgumentsNoMetadata {
            get {
                return ResourceManager.GetString("CommandArgumentsNoMetadata", resourceCulture);
            }
        }

        internal static string CommandArgumentsTooMany {
            get {
                return ResourceManager.GetString("CommandArgumentsTooMany", resourceCulture);
            }
        }

        internal static string CommandArgumentsMissingRequired {
            get {
                return ResourceManager.GetString("CommandArgumentsMissingRequired", resourceCulture);
            }
        }

        internal static string CommandArgumentsInvalidNamed {
            get {
                return ResourceManager.GetString("CommandArgumentsInvalidNamed", resourceCulture);
            }
        }

        internal static string CommandArgumentsUnknownNamed {
            get {
                return ResourceManager.GetString("CommandArgumentsUnknownNamed", resourceCulture);
            }
        }

        internal static string CommandArgumentsInvalidBoolean {
            get {
                return ResourceManager.GetString("CommandArgumentsInvalidBoolean", resourceCulture);
            }
        }

        internal static string CommandArgumentsInvalidNumber {
            get {
                return ResourceManager.GetString("CommandArgumentsInvalidNumber", resourceCulture);
            }
        }

        internal static string CommandArgumentsInvalidChoice {
            get {
                return ResourceManager.GetString("CommandArgumentsInvalidChoice", resourceCulture);
            }
        }

        internal static string CommandArgumentsInvalidTextLength {
            get {
                return ResourceManager.GetString("CommandArgumentsInvalidTextLength", resourceCulture);
            }
        }

    }
}
