//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RootCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RootCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.RootCommandStrings", typeof(RootCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display the animated Aspire CLI welcome banner.
        /// </summary>
        internal static string BannerArgumentDescription {
            get {
                return ResourceManager.GetString("BannerArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CLI — version {0}.
        /// </summary>
        internal static string BannerVersionFormat {
            get {
                return ResourceManager.GetString("BannerVersionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to the.
        /// </summary>
        internal static string BannerWelcomeText {
            get {
                return ResourceManager.GetString("BannerWelcomeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wait for a debugger to attach before executing the command.
        /// </summary>
        internal static string CliWaitForDebuggerArgumentDescription {
            get {
                return ResourceManager.GetString("CliWaitForDebuggerArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a shell completion script to standard output.
        /// </summary>
        internal static string CompletionScriptDescription {
            get {
                return ResourceManager.GetString("CompletionScriptDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate shell completion scripts.
        /// </summary>
        internal static string CompletionsDescription {
            get {
                return ResourceManager.GetString("CompletionsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shell to generate a script for (bash, fish, pwsh, zsh). Defaults to SHELL, or pwsh on Windows..
        /// </summary>
        internal static string CompletionShellDescription {
            get {
                return ResourceManager.GetString("CompletionShellDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not detect a supported shell. Specify bash, fish, pwsh, or zsh: aspire completions script &lt;shell&gt;..
        /// </summary>
        internal static string CompletionShellRequired {
            get {
                return ResourceManager.GetString("CompletionShellRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable debug logging to the console.
        /// </summary>
        internal static string DebugArgumentDescription {
            get {
                return ResourceManager.GetString("DebugArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set the minimum log level for console output (Trace, Debug, Information, Warning, Error, Critical).
        /// </summary>
        internal static string DebugLevelArgumentDescription {
            get {
                return ResourceManager.GetString("DebugLevelArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire CLI can be used to create, run, and publish Aspire-based applications.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telemetry
        ///---------
        ///
        ///The Aspire CLI collects usage data. It is collected by Microsoft and is used to help us improve your experience. You can opt out of telemetry by setting the ASPIRE_CLI_TELEMETRY_OPTOUT environment variable to &apos;1&apos; or &apos;true&apos; using your preferred shell.
        ///
        ///Read more about Aspire CLI telemetry: {0}.
        /// </summary>
        internal static string FirstTimeUseTelemetryNotice {
            get {
                return ResourceManager.GetString("FirstTimeUseTelemetryNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire CLI is emulating identity &apos;{0}&apos; version &apos;{1}&apos;. Behavior may differ from the installed build; identity was overridden via environment variables or the install sidecar..
        /// </summary>
        internal static string IdentityOverrideNotice {
            get {
                return ResourceManager.GetString("IdentityOverrideNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected [suggest] or [suggest:&lt;cursor&gt;] followed by one command-line string, with the cursor inside that string..
        /// </summary>
        internal static string InvalidCompletionRequest {
            get {
                return ResourceManager.GetString("InvalidCompletionRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Suppress the startup banner and telemetry notice.
        /// </summary>
        internal static string NoLogoArgumentDescription {
            get {
                return ResourceManager.GetString("NoLogoArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run the command in non-interactive mode, disabling all interactive prompts and spinners.
        /// </summary>
        internal static string NonInteractiveArgumentDescription {
            get {
                return ResourceManager.GetString("NonInteractiveArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wait for a debugger to attach before executing the command.
        /// </summary>
        internal static string WaitForDebuggerArgumentDescription {
            get {
                return ResourceManager.GetString("WaitForDebuggerArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting for debugger to attach to CLI process ID: {0}.
        /// </summary>
        internal static string WaitingForDebugger {
            get {
                return ResourceManager.GetString("WaitingForDebugger", resourceCulture);
            }
        }
    }
}
