//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TelemetryCommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelemetryCommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.TelemetryCommandStrings", typeof(TelemetryCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View telemetry data (logs, spans, traces) from a running Aspire application..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View structured logs from the Dashboard telemetry API..
        /// </summary>
        internal static string LogsDescription {
            get {
                return ResourceManager.GetString("LogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View spans from the Dashboard telemetry API..
        /// </summary>
        internal static string SpansDescription {
            get {
                return ResourceManager.GetString("SpansDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View traces from the Dashboard telemetry API..
        /// </summary>
        internal static string TracesDescription {
            get {
                return ResourceManager.GetString("TracesDescription", resourceCulture);
            }
        }

        internal static string SummaryDescription {
            get {
                return ResourceManager.GetString("SummaryDescription", resourceCulture);
            }
        }

        internal static string SlowTracesDescription {
            get {
                return ResourceManager.GetString("SlowTracesDescription", resourceCulture);
            }
        }

        internal static string WallTimeDescription {
            get {
                return ResourceManager.GetString("WallTimeDescription", resourceCulture);
            }
        }

        internal static string SpanStatsDescription {
            get {
                return ResourceManager.GetString("SpanStatsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by resource name..
        /// </summary>
        internal static string ResourceArgumentDescription {
            get {
                return ResourceManager.GetString("ResourceArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream telemetry in real-time as it arrives..
        /// </summary>
        internal static string FollowOptionDescription {
            get {
                return ResourceManager.GetString("FollowOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format (Table or Json)..
        /// </summary>
        internal static string FormatOptionDescription {
            get {
                return ResourceManager.GetString("FormatOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of items to return..
        /// </summary>
        internal static string LimitOptionDescription {
            get {
                return ResourceManager.GetString("LimitOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by trace ID..
        /// </summary>
        internal static string TraceIdOptionDescription {
            get {
                return ResourceManager.GetString("TraceIdOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trace ID to view. If not specified, lists all traces..
        /// </summary>
        internal static string TraceIdArgumentDescription {
            get {
                return ResourceManager.GetString("TraceIdArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter logs by minimum severity (Trace, Debug, Information, Warning, Error, Critical)..
        /// </summary>
        internal static string SeverityOptionDescription {
            get {
                return ResourceManager.GetString("SeverityOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by error status (true to show only errors, false to exclude errors)..
        /// </summary>
        internal static string HasErrorOptionDescription {
            get {
                return ResourceManager.GetString("HasErrorOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-text search across telemetry text fields, such as log messages, attribute values, names, source, and IDs.
        /// </summary>
        internal static string SearchOptionDescription {
            get {
                return ResourceManager.GetString("SearchOptionDescription", resourceCulture);
            }
        }

        internal static string TelemetryArchiveOptionDescription {
            get {
                return ResourceManager.GetString("TelemetryArchiveOptionDescription", resourceCulture);
            }
        }

        internal static string TopOptionDescription {
            get {
                return ResourceManager.GetString("TopOptionDescription", resourceCulture);
            }
        }

        internal static string GroupByOptionDescription {
            get {
                return ResourceManager.GetString("GroupByOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The --limit value must be a positive number..
        /// </summary>
        internal static string LimitMustBePositive {
            get {
                return ResourceManager.GetString("LimitMustBePositive", resourceCulture);
            }
        }

        internal static string TopMustBePositive {
            get {
                return ResourceManager.GetString("TopMustBePositive", resourceCulture);
            }
        }

        internal static string FileAndLiveOptionsExclusive {
            get {
                return ResourceManager.GetString("FileAndLiveOptionsExclusive", resourceCulture);
            }
        }

        internal static string TelemetryArchiveNotFound {
            get {
                return ResourceManager.GetString("TelemetryArchiveNotFound", resourceCulture);
            }
        }

        internal static string FailedToReadTelemetryArchive {
            get {
                return ResourceManager.GetString("FailedToReadTelemetryArchive", resourceCulture);
            }
        }

        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard API is not available. Ensure the apphost is running with Dashboard enabled..
        /// </summary>
        internal static string DashboardNotAvailable {
            get {
                return ResourceManager.GetString("DashboardNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch telemetry: {0}.
        /// </summary>
        internal static string FailedToFetchTelemetry {
            get {
                return ResourceManager.GetString("FailedToFetchTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace with ID '{0}' was not found..
        /// </summary>
        internal static string TraceNotFound {
            get {
                return ResourceManager.GetString("TraceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard API returned unexpected content type '{0}'. Expected JSON response..
        /// </summary>
        internal static string UnexpectedContentType {
            get {
                return ResourceManager.GetString("UnexpectedContentType", resourceCulture);
            }
        }

        internal static string SelectAppHostAction {
            get {
                return ResourceManager.GetString("SelectAppHostAction", resourceCulture);
            }
        }

        internal static string HeaderTimestamp {
            get {
                return ResourceManager.GetString("HeaderTimestamp", resourceCulture);
            }
        }

        internal static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }

        internal static string HeaderDuration {
            get {
                return ResourceManager.GetString("HeaderDuration", resourceCulture);
            }
        }

        internal static string HeaderSpans {
            get {
                return ResourceManager.GetString("HeaderSpans", resourceCulture);
            }
        }

        internal static string HeaderStatus {
            get {
                return ResourceManager.GetString("HeaderStatus", resourceCulture);
            }
        }

        internal static string HeaderMetric {
            get {
                return ResourceManager.GetString("HeaderMetric", resourceCulture);
            }
        }

        internal static string HeaderValue {
            get {
                return ResourceManager.GetString("HeaderValue", resourceCulture);
            }
        }

        internal static string HeaderTraceId {
            get {
                return ResourceManager.GetString("HeaderTraceId", resourceCulture);
            }
        }

        internal static string HeaderResource {
            get {
                return ResourceManager.GetString("HeaderResource", resourceCulture);
            }
        }

        internal static string HeaderGroup {
            get {
                return ResourceManager.GetString("HeaderGroup", resourceCulture);
            }
        }

        internal static string HeaderCount {
            get {
                return ResourceManager.GetString("HeaderCount", resourceCulture);
            }
        }

        internal static string HeaderErrors {
            get {
                return ResourceManager.GetString("HeaderErrors", resourceCulture);
            }
        }

        internal static string HeaderAverage {
            get {
                return ResourceManager.GetString("HeaderAverage", resourceCulture);
            }
        }

        internal static string HeaderP95 {
            get {
                return ResourceManager.GetString("HeaderP95", resourceCulture);
            }
        }

        internal static string HeaderMax {
            get {
                return ResourceManager.GetString("HeaderMax", resourceCulture);
            }
        }

        internal static string HeaderTotal {
            get {
                return ResourceManager.GetString("HeaderTotal", resourceCulture);
            }
        }

        internal static string HeaderWallClock {
            get {
                return ResourceManager.GetString("HeaderWallClock", resourceCulture);
            }
        }

        internal static string HeaderSpanSum {
            get {
                return ResourceManager.GetString("HeaderSpanSum", resourceCulture);
            }
        }

        internal static string HeaderCovered {
            get {
                return ResourceManager.GetString("HeaderCovered", resourceCulture);
            }
        }

        internal static string HeaderGap {
            get {
                return ResourceManager.GetString("HeaderGap", resourceCulture);
            }
        }

        internal static string HeaderOverlap {
            get {
                return ResourceManager.GetString("HeaderOverlap", resourceCulture);
            }
        }

        internal static string HeaderRatio {
            get {
                return ResourceManager.GetString("HeaderRatio", resourceCulture);
            }
        }

        internal static string MetricResources {
            get {
                return ResourceManager.GetString("MetricResources", resourceCulture);
            }
        }

        internal static string MetricTraces {
            get {
                return ResourceManager.GetString("MetricTraces", resourceCulture);
            }
        }

        internal static string MetricSpans {
            get {
                return ResourceManager.GetString("MetricSpans", resourceCulture);
            }
        }

        internal static string MetricErrorTraces {
            get {
                return ResourceManager.GetString("MetricErrorTraces", resourceCulture);
            }
        }

        internal static string MetricErrorSpans {
            get {
                return ResourceManager.GetString("MetricErrorSpans", resourceCulture);
            }
        }

        internal static string MetricAverageDuration {
            get {
                return ResourceManager.GetString("MetricAverageDuration", resourceCulture);
            }
        }

        internal static string MetricP50Duration {
            get {
                return ResourceManager.GetString("MetricP50Duration", resourceCulture);
            }
        }

        internal static string MetricP95Duration {
            get {
                return ResourceManager.GetString("MetricP95Duration", resourceCulture);
            }
        }

        internal static string MetricP99Duration {
            get {
                return ResourceManager.GetString("MetricP99Duration", resourceCulture);
            }
        }

        internal static string MetricMaxDuration {
            get {
                return ResourceManager.GetString("MetricMaxDuration", resourceCulture);
            }
        }

        internal static string DashboardUrlOptionDescription {
            get {
                return ResourceManager.GetString("DashboardUrlOptionDescription", resourceCulture);
            }
        }

        internal static string ApiKeyOptionDescription {
            get {
                return ResourceManager.GetString("ApiKeyOptionDescription", resourceCulture);
            }
        }

        internal static string DashboardUrlAndAppHostExclusive {
            get {
                return ResourceManager.GetString("DashboardUrlAndAppHostExclusive", resourceCulture);
            }
        }

        internal static string DashboardAuthFailed {
            get {
                return ResourceManager.GetString("DashboardAuthFailed", resourceCulture);
            }
        }

        internal static string DashboardUrlNotReachable {
            get {
                return ResourceManager.GetString("DashboardUrlNotReachable", resourceCulture);
            }
        }

        internal static string DashboardApiNotEnabled {
            get {
                return ResourceManager.GetString("DashboardApiNotEnabled", resourceCulture);
            }
        }

        internal static string DashboardConnectionFailed {
            get {
                return ResourceManager.GetString("DashboardConnectionFailed", resourceCulture);
            }
        }

        internal static string DashboardConnectionFailedHint {
            get {
                return ResourceManager.GetString("DashboardConnectionFailedHint", resourceCulture);
            }
        }

        internal static string DashboardUrlInvalid {
            get {
                return ResourceManager.GetString("DashboardUrlInvalid", resourceCulture);
            }
        }

        internal static string DashboardUrlInvalidHint {
            get {
                return ResourceManager.GetString("DashboardUrlInvalidHint", resourceCulture);
            }
        }

        internal static string DashboardLoginTokenFailed {
            get {
                return ResourceManager.GetString("DashboardLoginTokenFailed", resourceCulture);
            }
        }

        internal static string DashboardLoginTokenFailedHint {
            get {
                return ResourceManager.GetString("DashboardLoginTokenFailedHint", resourceCulture);
            }
        }

        internal static string DashboardLoginTokenFailedAnonymousHint {
            get {
                return ResourceManager.GetString("DashboardLoginTokenFailedAnonymousHint", resourceCulture);
            }
        }

        internal static string DashboardNotAvailableHint {
            get {
                return ResourceManager.GetString("DashboardNotAvailableHint", resourceCulture);
            }
        }

        internal static string DashboardAuthFailedHint {
            get {
                return ResourceManager.GetString("DashboardAuthFailedHint", resourceCulture);
            }
        }

        internal static string DashboardAuthFailedAnonymousHint {
            get {
                return ResourceManager.GetString("DashboardAuthFailedAnonymousHint", resourceCulture);
            }
        }

        internal static string DashboardUrlNotReachableHint {
            get {
                return ResourceManager.GetString("DashboardUrlNotReachableHint", resourceCulture);
            }
        }

        internal static string DashboardApiNotEnabledHint {
            get {
                return ResourceManager.GetString("DashboardApiNotEnabledHint", resourceCulture);
            }
        }
    }
}
