//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TemplatingStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplatingStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.TemplatingStrings", typeof(TemplatingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppHost.
        /// </summary>
        internal static string AspireAppHost_Description {
            get {
                return ResourceManager.GetString("AspireAppHost_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty AppHost.
        /// </summary>
        internal static string AspireAppHostSingleFile_Description {
            get {
                return ResourceManager.GetString("AspireAppHostSingleFile_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppHost and service defaults.
        /// </summary>
        internal static string AspireEmpty_Description {
            get {
                return ResourceManager.GetString("AspireEmpty_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty (C# AppHost, dotnet template).
        /// </summary>
        internal static string AspireEmptyDotNetTemplate_Description {
            get {
                return ResourceManager.GetString("AspireEmptyDotNetTemplate_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starter App (Java AppHost/Express/React).
        /// </summary>
        internal static string AspireJavaStarter_Description {
            get {
                return ResourceManager.GetString("AspireJavaStarter_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starter App (ASP.NET Core/React, C# AppHost).
        /// </summary>
        internal static string AspireJsFrontendStarter_Description {
            get {
                return ResourceManager.GetString("AspireJsFrontendStarter_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MSTest.
        /// </summary>
        internal static string AspireMSTest_Description {
            get {
                return ResourceManager.GetString("AspireMSTest_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NUnit.
        /// </summary>
        internal static string AspireNUnit_Description {
            get {
                return ResourceManager.GetString("AspireNUnit_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service defaults.
        /// </summary>
        internal static string AspireServiceDefaults_Description {
            get {
                return ResourceManager.GetString("AspireServiceDefaults_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starter App (ASP.NET Core/Blazor).
        /// </summary>
        internal static string AspireStarter_Description {
            get {
                return ResourceManager.GetString("AspireStarter_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to xUnit.
        /// </summary>
        internal static string AspireXUnit_Description {
            get {
                return ResourceManager.GetString("AspireXUnit_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one template factory must be provided..
        /// </summary>
        internal static string AtLeastOneTemplateFactoryMustBeProvided {
            get {
                return ResourceManager.GetString("AtLeastOneTemplateFactoryMustBeProvided", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create NuGet.config for selected channels?.
        /// </summary>
        internal static string CreateNugetConfigConfirmation {
            get {
                return ResourceManager.GetString("CreateNugetConfigConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating new Aspire project....
        /// </summary>
        internal static string CreatingNewProject {
            get {
                return ResourceManager.GetString("CreatingNewProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The version of xUnit.net to use for the test project..
        /// </summary>
        internal static string EnterXUnitVersion_Description {
            get {
                return ResourceManager.GetString("EnterXUnitVersion_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the xUnit.net version to use.
        /// </summary>
        internal static string EnterXUnitVersion_Prompt {
            get {
                return ResourceManager.GetString("EnterXUnitVersion_Prompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Getting templates....
        /// </summary>
        internal static string GettingTemplates {
            get {
                return ResourceManager.GetString("GettingTemplates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integration tests.
        /// </summary>
        internal static string IntegrationTestsTemplate_Description {
            get {
                return ResourceManager.GetString("IntegrationTestsTemplate_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matching local Aspire.ProjectTemplates package was found for Aspire CLI version &apos;{0}&apos;. Build and stage matching packages with localhive.sh (macOS/Linux) or localhive.ps1 (Windows), set ASPIRE_CLI_PACKAGES to a directory containing the package, or explicitly choose feed-backed templates with --channel, --source, or --version..
        /// </summary>
        internal static string NoMatchingLocalTemplatePackage {
            get {
                return ResourceManager.GetString("NoMatchingLocalTemplatePackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No template versions were found. Please check your internet connection or NuGet source configuration..
        /// </summary>
        internal static string NoTemplateVersionsFound {
            get {
                return ResourceManager.GetString("NoTemplateVersionsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created NuGet.config for the selected package channel..
        /// </summary>
        internal static string NuGetConfigCreatedConfirmationMessage {
            get {
                return ResourceManager.GetString("NuGetConfigCreatedConfirmationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created or updated NuGet.config in the project directory with required package sources..
        /// </summary>
        internal static string NuGetConfigCreatedOrUpdatedConfirmationMessage {
            get {
                return ResourceManager.GetString("NuGetConfigCreatedOrUpdatedConfirmationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updated NuGet.config with required package sources..
        /// </summary>
        internal static string NuGetConfigUpdatedConfirmationMessage {
            get {
                return ResourceManager.GetString("NuGetConfigUpdatedConfirmationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The new project cannot be created because it would overwrite existing files in the output folder. Please remove or move the conflicting files, or choose a different location..
        /// </summary>
        internal static string ProjectAlreadyExists {
            get {
                return ResourceManager.GetString("ProjectAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project created successfully in {0}..
        /// </summary>
        internal static string ProjectCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectCreatedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project creation failed with exit code {0}..
        /// </summary>
        internal static string ProjectCreationFailed {
            get {
                return ResourceManager.GetString("ProjectCreationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a test framework.
        /// </summary>
        internal static string PromptForTFM_Prompt {
            get {
                return ResourceManager.GetString("PromptForTFM_Prompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using {0} for testing..
        /// </summary>
        internal static string PromptForTFM_UsingForTesting {
            get {
                return ResourceManager.GetString("PromptForTFM_UsingForTesting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configures whether to create a project for integration tests using MSTest, NUnit, or xUnit.net..
        /// </summary>
        internal static string PromptForTFMOptions_Description {
            get {
                return ResourceManager.GetString("PromptForTFMOptions_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to create a test project?.
        /// </summary>
        internal static string PromptForTFMOptions_Prompt {
            get {
                return ResourceManager.GetString("PromptForTFMOptions_Prompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run &apos;aspire run&apos; to start your AppHost..
        /// </summary>
        internal static string RunAspireRun {
            get {
                return ResourceManager.GetString("RunAspireRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run &apos;cd &quot;{0}&quot;&apos; and then &apos;aspire run&apos; to start your AppHost..
        /// </summary>
        internal static string RunCdThenAspireRun {
            get {
                return ResourceManager.GetString("RunCdThenAspireRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching for available project template versions....
        /// </summary>
        internal static string SearchingForAvailableTemplateVersions {
            get {
                return ResourceManager.GetString("SearchingForAvailableTemplateVersions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [yellow]--source was used for the initial scaffold restore only and is not persisted. Later &apos;aspire restore&apos; / &apos;aspire add&apos; will use the channel feeds configured for this project.[/].
        /// </summary>
        internal static string SourceOverrideNotPersistedWarning {
            get {
                return ResourceManager.GetString("SourceOverrideNotPersistedWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The template installation failed with exit code {0}..
        /// </summary>
        internal static string TemplateInstallationFailed {
            get {
                return ResourceManager.GetString("TemplateInstallationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Template version &apos;{0}&apos; was not found..
        /// </summary>
        internal static string TemplateVersionNotFound {
            get {
                return ResourceManager.GetString("TemplateVersionNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update NuGet.config to add missing package sources for the selected channel?.
        /// </summary>
        internal static string UpdateNuGetConfigConfirmation {
            get {
                return ResourceManager.GetString("UpdateNuGetConfigConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configures whether to use *.dev.localhost URLs for local development..
        /// </summary>
        internal static string UseLocalhostTld_Description {
            get {
                return ResourceManager.GetString("UseLocalhostTld_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use *.dev.localhost URLs.
        /// </summary>
        internal static string UseLocalhostTld_Prompt {
            get {
                return ResourceManager.GetString("UseLocalhostTld_Prompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected choice for *.dev.localhost option.
        /// </summary>
        internal static string UseLocalhostTld_UnexpectedChoice {
            get {
                return ResourceManager.GetString("UseLocalhostTld_UnexpectedChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using *.dev.localhost URLs for local development..
        /// </summary>
        internal static string UseLocalhostTld_UsingLocalhostTld {
            get {
                return ResourceManager.GetString("UseLocalhostTld_UsingLocalhostTld", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configures whether to setup the application to use Redis for caching..
        /// </summary>
        internal static string UseRedisCache_Description {
            get {
                return ResourceManager.GetString("UseRedisCache_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Redis Cache.
        /// </summary>
        internal static string UseRedisCache_Prompt {
            get {
                return ResourceManager.GetString("UseRedisCache_Prompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected choice for Redis Cache option.
        /// </summary>
        internal static string UseRedisCache_UnexpectedChoice {
            get {
                return ResourceManager.GetString("UseRedisCache_UnexpectedChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using Redis Cache for caching..
        /// </summary>
        internal static string UseRedisCache_UsingRedisCache {
            get {
                return ResourceManager.GetString("UseRedisCache_UsingRedisCache", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using project templates version: {0}.
        /// </summary>
        internal static string UsingProjectTemplatesVersion {
            get {
                return ResourceManager.GetString("UsingProjectTemplatesVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
