//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting.Azure.Provisioning
{
    [AspireExport]
    public sealed partial class BicepValueProxy
    {
        internal BicepValueProxy() { }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [AspireExportIgnore(Reason = "Used by generated provisioning proxy code.")]
        public void AssignTo<T>(global::Azure.Provisioning.BicepValue<T> target) { }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [AspireExportIgnore(Reason = "Used by generated provisioning proxy code.")]
        public static global::Azure.Provisioning.BicepValue<T> Convert<T>(object value) { throw null; }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [AspireExportIgnore(Reason = "Used by generated provisioning proxy code.")]
        public static BicepValueProxy Create<T>(global::Azure.Provisioning.BicepValue<T> value) { throw null; }
    }

    [AspireExport]
    public partial class ProvisionableResourceProxy
    {
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        protected ProvisionableResourceProxy(global::Azure.Provisioning.Primitives.ProvisionableResource value) { }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [AspireExportIgnore(Reason = "Used by generated provisioning proxy code.")]
        public global::Azure.Provisioning.Primitives.ProvisionableResource Inner { get { throw null; } }
    }
}