// This script runs inside a Docker build stage during publish mode. The Aspire hosting
// integration copies it into the project's obj/ folder and invokes it in a Dockerfile
// RUN step after `dotnet publish` completes.
//
// It reads the static web assets endpoints manifest (*.staticwebassets.endpoints.json)
// generated by the .NET SDK's GenerateStaticWebAssetEndpointsManifest MSBuild target
// (see: https://github.com/dotnet/sdk/blob/main/src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets)
// and consumed by ASP.NET Core's MapStaticAssets() endpoint routing middleware
// (see: https://github.com/dotnet/aspnetcore/blob/main/src/StaticAssets/src/StaticAssetEndpointRouteBuilderExtensions.cs).
//
// The script prefixes every AssetFile path with the app's URL segment so the gateway
// can serve multiple WASM apps under distinct path prefixes, and adds a SPA catch-all
// fallback endpoint cloned from index.html unless the manifest already defines its own
// {**path:nonfile} fallback (as the hosted Blazor Web App shape does).
//
// TEMPORARY: this is interim scaffolding for the experimental Blazor gateway and will be
// removed once the .NET gateway CLI package and the SDK static-web-assets fallback feature
// (StaticWebAssetSpaFallbackEnabled, https://github.com/dotnet/aspnetcore/issues/64828) own
// SPA fallback routing directly.
//
// Usage: dotnet run PrefixEndpoints.cs -- <manifest-path> <prefix> <output-path>

using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;

if (args.Length < 3)
{
    Console.Error.WriteLine("Usage: dotnet run PrefixEndpoints.cs -- <manifest-path> <prefix> <output-path>");
    return 1;
}

var manifestPath = args[0];
var prefix = args[1];
var outputPath = args[2];

var manifest = JsonSerializer.Deserialize(
    File.ReadAllText(manifestPath),
    ManifestJsonContext.Default.EndpointsManifest)!;

var fallbackEndpoints = new List<EndpointEntry>();

// TEMPORARY: this whole script is interim scaffolding for the experimental Blazor gateway
// (ASPIREBLAZOR001) and is expected to be deleted, not evolved. It will be replaced by two
// proper mechanisms:
//   1. The .NET gateway CLI package (the .NET 11 gateway), which owns SPA fallback routing
//      correctly instead of us rewriting each app's endpoints manifest.
//      See: https://github.com/dotnet/aspnetcore/pull/67599.
//   2. The SDK static-web-assets fallback feature (StaticWebAssetSpaFallbackEnabled), which
//      emits the fallback endpoint at build time so hosts don't have to synthesize it.
//      See: https://github.com/dotnet/aspnetcore/issues/64828.
// Because it is temporary, we keep the detection dumb: only skip injection when the manifest
// already contains the exact "{**path:nonfile}" route (the same literal the SDK emits and that
// we would otherwise clone). We do NOT parse routes with RoutePattern.Parse — that would pull
// the ASP.NET Core routing framework reference into this plain-SDK Docker-build script just to
// inspect one string, which isn't worth it for code on its way out.
//
// In the hosted Blazor Web App shape the server already owns request routing (Razor components
// plus its own fallback), so a second {**path:nonfile} catch-all collides with the existing
// routing and causes the app to return HTTP 500. Skipping injection when a fallback is already
// present keeps us correct for both the standalone-WASM-plus-gateway shape (none present, so we
// add one) and the hosted-Web-App shape (already present, so we leave it alone).
var hasExistingFallback = manifest.Endpoints.Any(e => string.Equals(e.Route, "{**path:nonfile}", StringComparison.OrdinalIgnoreCase));

foreach (var ep in manifest.Endpoints)
{
    ep.AssetFile = $"{prefix}/{ep.AssetFile}";

    // Clone only the identity (uncompressed) index.html endpoint as a catch-all SPA fallback.
    // Skip compressed variants (those with Content-Encoding selectors) because the
    // ContentEncodingNegotiationMatcherPolicy would otherwise prefer the catch-all over
    // literal routes (like _blazor/_configuration) that lack encoding metadata.
    if (!hasExistingFallback && string.Equals(ep.Route, "index.html", StringComparison.OrdinalIgnoreCase))
    {
        var hasContentEncoding = ep.Selectors?.Any(s => s.Name == "Content-Encoding") == true;

        if (!hasContentEncoding)
        {
            // Deep-clone via round-trip serialization, then patch route and cache header
            var fallbackJson = JsonSerializer.Serialize(ep, ManifestJsonContext.Default.EndpointEntry);
            var fallback = JsonSerializer.Deserialize(fallbackJson, ManifestJsonContext.Default.EndpointEntry)!;
            fallback.Route = "{**path:nonfile}";
            if (fallback.ResponseHeaders is not null)
            {
                foreach (var header in fallback.ResponseHeaders)
                {
                    if (header.Name == "Cache-Control")
                    {
                        header.Value = "no-store";
                    }
                }
            }
            fallbackEndpoints.Add(fallback);
        }
    }
}

manifest.Endpoints = [.. manifest.Endpoints, .. fallbackEndpoints];

var dir = Path.GetDirectoryName(outputPath);
if (dir is not null)
{
    Directory.CreateDirectory(dir);
}

File.WriteAllText(outputPath, JsonSerializer.Serialize(manifest, ManifestJsonContext.Relaxed.EndpointsManifest));

return 0;

// Same typed model used by the Hosting library's EndpointsManifestTransformer
class EndpointsManifest
{
    public EndpointEntry[] Endpoints { get; set; } = [];

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}

class EndpointEntry
{
    public string Route { get; set; } = "";
    public string AssetFile { get; set; } = "";
    public EndpointSelector[]? Selectors { get; set; }
    public EndpointResponseHeader[]? ResponseHeaders { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}

class EndpointSelector
{
    public string Name { get; set; } = "";

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}

class EndpointResponseHeader
{
    public string Name { get; set; } = "";
    public string Value { get; set; } = "";

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}

[JsonSerializable(typeof(EndpointsManifest))]
[JsonSerializable(typeof(EndpointEntry))]
[JsonSourceGenerationOptions(
    WriteIndented = true)]
partial class ManifestJsonContext : JsonSerializerContext
{
    internal static ManifestJsonContext Relaxed { get; } = new(new JsonSerializerOptions
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    });
}
