//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recordings, viewing {0}.
        /// </summary>
        public static string DashboardRunSelectAccessibleLabel {
            get {
                return ResourceManager.GetString("DashboardRunSelectAccessibleLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Live view.
        /// </summary>
        public static string DashboardRunSelectCurrent {
            get {
                return ResourceManager.GetString("DashboardRunSelectCurrent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        public static string DashboardRunSelectDayAgo {
            get {
                return ResourceManager.GetString("DashboardRunSelectDayAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string DashboardRunSelectDaysAgo {
            get {
                return ResourceManager.GetString("DashboardRunSelectDaysAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn about recordings.
        /// </summary>
        public static string DashboardRunSelectHelp {
            get {
                return ResourceManager.GetString("DashboardRunSelectHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch between the live view and read-only recordings of previous runs. Protect a recording from deletion to keep it when older recordings are automatically removed..
        /// </summary>
        public static string DashboardRunSelectHelpTooltip {
            get {
                return ResourceManager.GetString("DashboardRunSelectHelpTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}h ago.
        /// </summary>
        public static string DashboardRunSelectHoursAgo {
            get {
                return ResourceManager.GetString("DashboardRunSelectHoursAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This recording can't be viewed because it was created by an incompatible version of the dashboard..
        /// </summary>
        public static string DashboardRunSelectIncompatibleTooltip {
            get {
                return ResourceManager.GetString("DashboardRunSelectIncompatibleTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        public static string DashboardRunSelectMinuteAgo {
            get {
                return ResourceManager.GetString("DashboardRunSelectMinuteAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string DashboardRunSelectMinutesAgo {
            get {
                return ResourceManager.GetString("DashboardRunSelectMinutesAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to a moment ago.
        /// </summary>
        public static string DashboardRunSelectMomentAgo {
            get {
                return ResourceManager.GetString("DashboardRunSelectMomentAgo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No existing recordings.
        /// </summary>
        public static string DashboardRunSelectNoRecordings {
            get {
                return ResourceManager.GetString("DashboardRunSelectNoRecordings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Protect from deletion.
        /// </summary>
        public static string DashboardRunSelectPin {
            get {
                return ResourceManager.GetString("DashboardRunSelectPin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Past recordings.
        /// </summary>
        public static string DashboardRunSelectRecordings {
            get {
                return ResourceManager.GetString("DashboardRunSelectRecordings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Live view and recordings.
        /// </summary>
        public static string DashboardRunSelectTitle {
            get {
                return ResourceManager.GetString("DashboardRunSelectTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow deletion.
        /// </summary>
        public static string DashboardRunSelectUnpin {
            get {
                return ResourceManager.GetString("DashboardRunSelectUnpin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extend the dashboard with views and tools for your app..
        /// </summary>
        public static string ExtensionsPageDescription {
            get {
                return ResourceManager.GetString("ExtensionsPageDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire.
        /// </summary>
        public static string MainLayoutAspire {
            get {
                return ResourceManager.GetString("MainLayoutAspire", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainLayoutAspireDashboardHelpLink {
            get {
                return ResourceManager.GetString("MainLayoutAspireDashboardHelpLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire repo.
        /// </summary>
        public static string MainLayoutAspireRepoLink {
            get {
                return ResourceManager.GetString("MainLayoutAspireRepoLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI agents.
        /// </summary>
        public static string MainLayoutLaunchAIAgents {
            get {
                return ResourceManager.GetString("MainLayoutLaunchAIAgents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string MainLayoutLaunchNotifications {
            get {
                return ResourceManager.GetString("MainLayoutLaunchNotifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainLayoutLaunchSettings {
            get {
                return ResourceManager.GetString("MainLayoutLaunchSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string MainLayoutNotificationCenterTitle {
            get {
                return ResourceManager.GetString("MainLayoutNotificationCenterTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MainLayoutSettingsDialogClose {
            get {
                return ResourceManager.GetString("MainLayoutSettingsDialogClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainLayoutSettingsDialogTitle {
            get {
                return ResourceManager.GetString("MainLayoutSettingsDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred..
        /// </summary>
        public static string MainLayoutUnhandledErrorMessage {
            get {
                return ResourceManager.GetString("MainLayoutUnhandledErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string MainLayoutUnhandledErrorReload {
            get {
                return ResourceManager.GetString("MainLayoutUnhandledErrorReload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Untrusted apps can access telemetry data via the API..
        /// </summary>
        public static string MessageUnsecuredEndpointApiBody {
            get {
                return ResourceManager.GetString("MessageUnsecuredEndpointApiBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string MessageUnsecuredEndpointLink {
            get {
                return ResourceManager.GetString("MessageUnsecuredEndpointLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Untrusted apps can send telemetry to the dashboard..
        /// </summary>
        public static string MessageUnsecuredEndpointTelemetryBody {
            get {
                return ResourceManager.GetString("MessageUnsecuredEndpointTelemetryBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endpoint is unsecured.
        /// </summary>
        public static string MessageUnsecuredEndpointTitle {
            get {
                return ResourceManager.GetString("MessageUnsecuredEndpointTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string NavMenuConsoleLogsTab {
            get {
                return ResourceManager.GetString("NavMenuConsoleLogsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string NavMenuExtensionsTab {
            get {
                return ResourceManager.GetString("NavMenuExtensionsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telemetry sources.
        /// </summary>
        public static string NavMenuTelemetrySourcesTab {
            get {
                return ResourceManager.GetString("NavMenuTelemetrySourcesTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string NavMenuGraphTab {
            get {
                return ResourceManager.GetString("NavMenuGraphTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavMenuHomeTab {
            get {
                return ResourceManager.GetString("NavMenuHomeTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main navigation.
        /// </summary>
        public static string NavMenuLandmark {
            get {
                return ResourceManager.GetString("NavMenuLandmark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string NavMenuMetricsTab {
            get {
                return ResourceManager.GetString("NavMenuMetricsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string NavMenuParametersTab {
            get {
                return ResourceManager.GetString("NavMenuParametersTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string NavMenuResourcesTab {
            get {
                return ResourceManager.GetString("NavMenuResourcesTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Structured.
        /// </summary>
        public static string NavMenuStructuredLogsTab {
            get {
                return ResourceManager.GetString("NavMenuStructuredLogsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string NavMenuTagsTab {
            get {
                return ResourceManager.GetString("NavMenuTagsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        public static string NavMenuTerminalsTab {
            get {
                return ResourceManager.GetString("NavMenuTerminalsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Traces.
        /// </summary>
        public static string NavMenuTracesTab {
            get {
                return ResourceManager.GetString("NavMenuTracesTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View filters.
        /// </summary>
        public static string PageLayoutViewFilters {
            get {
                return ResourceManager.GetString("PageLayoutViewFilters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string PlaceholderPageComingSoon {
            get {
                return ResourceManager.GetString("PlaceholderPageComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All resources.
        /// </summary>
        public static string ResourceHeaderAllResources {
            get {
                return ResourceManager.GetString("ResourceHeaderAllResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All sources.
        /// </summary>
        public static string TelemetryHeaderAllSources {
            get {
                return ResourceManager.GetString("TelemetryHeaderAllSources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data from every telemetry source is shown. Select sources in the list to filter it..
        /// </summary>
        public static string TelemetryHeaderAllSourcesDescription {
            get {
                return ResourceManager.GetString("TelemetryHeaderAllSourcesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} sources selected.
        /// </summary>
        public static string TelemetryHeaderSelectedSources {
            get {
                return ResourceManager.GetString("TelemetryHeaderSelectedSources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} source.
        /// </summary>
        public static string TelemetryPaneCountSingular {
            get {
                return ResourceManager.GetString("TelemetryPaneCountSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} sources.
        /// </summary>
        public static string TelemetryPaneCountPlural {
            get {
                return ResourceManager.GetString("TelemetryPaneCountPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No telemetry sources.
        /// </summary>
        public static string TelemetryPaneNoSources {
            get {
                return ResourceManager.GetString("TelemetryPaneNoSources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No resource is selected, so data from every resource is shown. Select resources in the list to filter it..
        /// </summary>
        public static string ResourceHeaderAllResourcesDescription {
            get {
                return ResourceManager.GetString("ResourceHeaderAllResourcesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ResourceHeaderNotFound {
            get {
                return ResourceManager.GetString("ResourceHeaderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} selected resources.
        /// </summary>
        public static string ResourceHeaderSelectedResources {
            get {
                return ResourceManager.GetString("ResourceHeaderSelectedResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string ResourceHeaderStarted {
            get {
                return ResourceManager.GetString("ResourceHeaderStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide resource list.
        /// </summary>
        public static string ResourcePaneClose {
            get {
                return ResourceManager.GetString("ResourcePaneClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collapse resource list.
        /// </summary>
        public static string ResourcePaneCollapse {
            get {
                return ResourceManager.GetString("ResourcePaneCollapse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} resources.
        /// </summary>
        public static string ResourcePaneCountPlural {
            get {
                return ResourceManager.GetString("ResourcePaneCountPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} resource.
        /// </summary>
        public static string ResourcePaneCountSingular {
            get {
                return ResourceManager.GetString("ResourcePaneCountSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expand resource list.
        /// </summary>
        public static string ResourcePaneExpand {
            get {
                return ResourceManager.GetString("ResourcePaneExpand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string ResourcePaneLandmark {
            get {
                return ResourceManager.GetString("ResourcePaneLandmark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add tags to a resource from its overview to group related resources here..
        /// </summary>
        public static string ResourcePaneNoTagsDescription {
            get {
                return ResourceManager.GetString("ResourcePaneNoTagsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No tags yet.
        /// </summary>
        public static string ResourcePaneNoTagsTitle {
            get {
                return ResourceManager.GetString("ResourcePaneNoTagsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show resource list.
        /// </summary>
        public static string ResourcePaneOpen {
            get {
                return ResourceManager.GetString("ResourcePaneOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resize resource list.
        /// </summary>
        public static string ResourcePaneResize {
            get {
                return ResourceManager.GetString("ResourcePaneResize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter by state.
        /// </summary>
        public static string ResourcePaneStateFilters {
            get {
                return ResourceManager.GetString("ResourcePaneStateFilters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string ResourcePaneTagGroupLabel {
            get {
                return ResourceManager.GetString("ResourcePaneTagGroupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expand or collapse {0}.
        /// </summary>
        public static string ResourcePaneTagGroupToggle {
            get {
                return ResourceManager.GetString("ResourcePaneTagGroupToggle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sends telemetry, not part of the app model.
        /// </summary>
        public static string ResourcePaneTelemetryOnly {
            get {
                return ResourceManager.GetString("ResourcePaneTelemetryOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telemetry only.
        /// </summary>
        public static string ResourcePaneTelemetryOnlyGroup {
            get {
                return ResourceManager.GetString("ResourcePaneTelemetryOnlyGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Untagged.
        /// </summary>
        public static string ResourcePaneUntaggedGroup {
            get {
                return ResourceManager.GetString("ResourcePaneUntaggedGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} unviewed error logs.
        /// </summary>
        public static string ResourcePaneUnviewedErrors {
            get {
                return ResourceManager.GetString("ResourcePaneUnviewedErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string ResourceTabOverview {
            get {
                return ResourceManager.GetString("ResourceTabOverview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not available for this resource.
        /// </summary>
        public static string ResourceTabUnavailable {
            get {
                return ResourceManager.GetString("ResourceTabUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource views.
        /// </summary>
        public static string ResourceTabsLandmark {
            get {
                return ResourceManager.GetString("ResourceTabsLandmark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open and switch between the terminals of your resources from one place..
        /// </summary>
        public static string TerminalsPageDescription {
            get {
                return ResourceManager.GetString("TerminalsPageDescription", resourceCulture);
            }
        }
    }
}
