//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string GraphPageTitle {
            get {
                return ResourceManager.GetString("GraphPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} (just now).
        /// </summary>
        public static string HealthCheckStatusJustNowFormat {
            get {
                return ResourceManager.GetString("HealthCheckStatusJustNowFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} ago).
        /// </summary>
        public static string HealthCheckStatusWithTimeFormat {
            get {
                return ResourceManager.GetString("HealthCheckStatusWithTimeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} (last run at {1}).
        /// </summary>
        public static string HealthCheckStatusWithTimeTooltipFormat {
            get {
                return ResourceManager.GetString("HealthCheckStatusWithTimeTooltipFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All {0} resources are running.
        /// </summary>
        public static string HomeHeadlineAllRunning {
            get {
                return ResourceManager.GetString("HomeHeadlineAllRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} resources need attention.
        /// </summary>
        public static string HomeHeadlineAttention {
            get {
                return ResourceManager.GetString("HomeHeadlineAttention", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No resources need attention.
        /// </summary>
        public static string HomeHeadlineHealthy {
            get {
                return ResourceManager.GetString("HomeHeadlineHealthy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} resources are pending.
        /// </summary>
        public static string HomeHeadlinePending {
            get {
                return ResourceManager.GetString("HomeHeadlinePending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string HomeInactiveLabel {
            get {
                return ResourceManager.GetString("HomeInactiveLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Need attention.
        /// </summary>
        public static string HomeNeedsAttentionLabel {
            get {
                return ResourceManager.GetString("HomeNeedsAttentionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No failed traces.
        /// </summary>
        public static string HomeNoFailedTraces {
            get {
                return ResourceManager.GetString("HomeNoFailedTraces", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No errors logged.
        /// </summary>
        public static string HomeNoRecentErrors {
            get {
                return ResourceManager.GetString("HomeNoRecentErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string HomePendingLabel {
            get {
                return ResourceManager.GetString("HomePendingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent errors.
        /// </summary>
        public static string HomeRecentErrorsTitle {
            get {
                return ResourceManager.GetString("HomeRecentErrorsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent failed traces.
        /// </summary>
        public static string HomeRecentFailedTracesTitle {
            get {
                return ResourceManager.GetString("HomeRecentFailedTracesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource states.
        /// </summary>
        public static string HomeResourceStatesLabel {
            get {
                return ResourceManager.GetString("HomeResourceStatesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string HomeResourcesLabel {
            get {
                return ResourceManager.GetString("HomeResourcesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string HomeRunningLabel {
            get {
                return ResourceManager.GetString("HomeRunningLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Started {0}.
        /// </summary>
        public static string HomeStartedAt {
            get {
                return ResourceManager.GetString("HomeStartedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string HomeSummaryLandmark {
            get {
                return ResourceManager.GetString("HomeSummaryLandmark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telemetry.
        /// </summary>
        public static string HomeTelemetryLandmark {
            get {
                return ResourceManager.GetString("HomeTelemetryLandmark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} unviewed error logs.
        /// </summary>
        public static string HomeUnviewedErrors {
            get {
                return ResourceManager.GetString("HomeUnviewedErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string ParametersPageTitle {
            get {
                return ResourceManager.GetString("ParametersPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string ResourceActionCommandsText {
            get {
                return ResourceManager.GetString("ResourceActionCommandsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Console logs.
        /// </summary>
        public static string ResourceActionConsoleLogsText {
            get {
                return ResourceManager.GetString("ResourceActionConsoleLogsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string ResourceActionMetricsText {
            get {
                return ResourceManager.GetString("ResourceActionMetricsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Structured logs.
        /// </summary>
        public static string ResourceActionStructuredLogsText {
            get {
                return ResourceManager.GetString("ResourceActionStructuredLogsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Traces.
        /// </summary>
        public static string ResourceActionTracesText {
            get {
                return ResourceManager.GetString("ResourceActionTracesText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URLs.
        /// </summary>
        public static string ResourceActionUrlsText {
            get {
                return ResourceManager.GetString("ResourceActionUrlsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collapse child resources.
        /// </summary>
        public static string ResourceCollapseAllChildren {
            get {
                return ResourceManager.GetString("ResourceCollapseAllChildren", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The AppHost disconnected while executing the command. Restart the AppHost and try again..
        /// </summary>
        public static string ResourceCommandAppHostDisconnected {
            get {
                return ResourceManager.GetString("ResourceCommandAppHostDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ResourceCommandCancel {
            get {
                return ResourceManager.GetString("ResourceCommandCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; canceled.
        /// </summary>
        public static string ResourceCommandCanceled {
            get {
                return ResourceManager.GetString("ResourceCommandCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; canceling....
        /// </summary>
        public static string ResourceCommandCanceling {
            get {
                return ResourceManager.GetString("ResourceCommandCanceling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; failed.
        /// </summary>
        public static string ResourceCommandFailed {
            get {
                return ResourceManager.GetString("ResourceCommandFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; starting.
        /// </summary>
        public static string ResourceCommandStarting {
            get {
                return ResourceManager.GetString("ResourceCommandStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; succeeded.
        /// </summary>
        public static string ResourceCommandSuccess {
            get {
                return ResourceManager.GetString("ResourceCommandSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View console logs.
        /// </summary>
        public static string ResourceCommandToastViewLogs {
            get {
                return ResourceManager.GetString("ResourceCommandToastViewLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View response.
        /// </summary>
        public static string ResourceCommandViewResponse {
            get {
                return ResourceManager.GetString("ResourceCommandViewResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View console logs.
        /// </summary>
        public static string ResourceDetailsViewConsoleLogs {
            get {
                return ResourceManager.GetString("ResourceDetailsViewConsoleLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expand child resources.
        /// </summary>
        public static string ResourceExpandAllChildren {
            get {
                return ResourceManager.GetString("ResourceExpandAllChildren", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (Unset).
        /// </summary>
        public static string ResourceFilterOptionEmpty {
            get {
                return ResourceManager.GetString("ResourceFilterOptionEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string ResourceOverviewConsoleTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewConsoleTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string ResourceOverviewCountOfTotal {
            get {
                return ResourceManager.GetString("ResourceOverviewCountOfTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endpoints.
        /// </summary>
        public static string ResourceOverviewEndpointsTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewEndpointsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ResourceOverviewErrors {
            get {
                return ResourceManager.GetString("ResourceOverviewErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit code.
        /// </summary>
        public static string ResourceOverviewExitCode {
            get {
                return ResourceManager.GetString("ResourceOverviewExitCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string ResourceOverviewFailed {
            get {
                return ResourceManager.GetString("ResourceOverviewFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter environment variables.
        /// </summary>
        public static string ResourceOverviewFilterEnvironmentVariables {
            get {
                return ResourceManager.GetString("ResourceOverviewFilterEnvironmentVariables", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Instruments.
        /// </summary>
        public static string ResourceOverviewInstruments {
            get {
                return ResourceManager.GetString("ResourceOverviewInstruments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string ResourceOverviewInternalEndpoint {
            get {
                return ResourceManager.GetString("ResourceOverviewInternalEndpoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Structured logs.
        /// </summary>
        public static string ResourceOverviewLogsTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewLogsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string ResourceOverviewMeters {
            get {
                return ResourceManager.GetString("ResourceOverviewMeters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string ResourceOverviewMetricsTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewMetricsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No warnings or errors.
        /// </summary>
        public static string ResourceOverviewNoAttentionLogs {
            get {
                return ResourceManager.GetString("ResourceOverviewNoAttentionLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No console output.
        /// </summary>
        public static string ResourceOverviewNoConsoleLogs {
            get {
                return ResourceManager.GetString("ResourceOverviewNoConsoleLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No endpoints.
        /// </summary>
        public static string ResourceOverviewNoEndpoints {
            get {
                return ResourceManager.GetString("ResourceOverviewNoEndpoints", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No environment variables.
        /// </summary>
        public static string ResourceOverviewNoEnvironmentVariables {
            get {
                return ResourceManager.GetString("ResourceOverviewNoEnvironmentVariables", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No health checks.
        /// </summary>
        public static string ResourceOverviewNoHealthChecks {
            get {
                return ResourceManager.GetString("ResourceOverviewNoHealthChecks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No environment variables match the filter.
        /// </summary>
        public static string ResourceOverviewNoMatchingEnvironmentVariables {
            get {
                return ResourceManager.GetString("ResourceOverviewNoMatchingEnvironmentVariables", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No metrics.
        /// </summary>
        public static string ResourceOverviewNoMetrics {
            get {
                return ResourceManager.GetString("ResourceOverviewNoMetrics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No properties.
        /// </summary>
        public static string ResourceOverviewNoProperties {
            get {
                return ResourceManager.GetString("ResourceOverviewNoProperties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No relationships.
        /// </summary>
        public static string ResourceOverviewNoRelationships {
            get {
                return ResourceManager.GetString("ResourceOverviewNoRelationships", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This resource hasn't sent telemetry.
        /// </summary>
        public static string ResourceOverviewNoTelemetry {
            get {
                return ResourceManager.GetString("ResourceOverviewNoTelemetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No traces.
        /// </summary>
        public static string ResourceOverviewNoTraces {
            get {
                return ResourceManager.GetString("ResourceOverviewNoTraces", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource '{0}' was not found..
        /// </summary>
        public static string ResourceOverviewNotFound {
            get {
                return ResourceManager.GetString("ResourceOverviewNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open console.
        /// </summary>
        public static string ResourceOverviewOpenConsole {
            get {
                return ResourceManager.GetString("ResourceOverviewOpenConsole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource overview.
        /// </summary>
        public static string ResourceOverviewPageTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ResourceOverviewPropertiesTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewPropertiesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relationship graph.
        /// </summary>
        public static string ResourceOverviewRelationshipGraph {
            get {
                return ResourceManager.GetString("ResourceOverviewRelationshipGraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string ResourceOverviewRelationshipsTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewRelationshipsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Summary of the selected resources.
        /// </summary>
        public static string ResourceOverviewSelectionSummary {
            get {
                return ResourceManager.GetString("ResourceOverviewSelectionSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show all environment variables.
        /// </summary>
        public static string ResourceOverviewShowAllEnvironmentVariables {
            get {
                return ResourceManager.GetString("ResourceOverviewShowAllEnvironmentVariables", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only environment variables from the app model.
        /// </summary>
        public static string ResourceOverviewShowAppModelEnvironmentVariables {
            get {
                return ResourceManager.GetString("ResourceOverviewShowAppModelEnvironmentVariables", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show less.
        /// </summary>
        public static string ResourceOverviewShowLess {
            get {
                return ResourceManager.GetString("ResourceOverviewShowLess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} more.
        /// </summary>
        public static string ResourceOverviewShowMore {
            get {
                return ResourceManager.GetString("ResourceOverviewShowMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ResourceOverviewStatusTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewStatusTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop time.
        /// </summary>
        public static string ResourceOverviewStopTime {
            get {
                return ResourceManager.GetString("ResourceOverviewStopTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ResourceOverviewTotal {
            get {
                return ResourceManager.GetString("ResourceOverviewTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Traces.
        /// </summary>
        public static string ResourceOverviewTracesTitle {
            get {
                return ResourceManager.GetString("ResourceOverviewTracesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ResourceOverviewViewAll {
            get {
                return ResourceManager.GetString("ResourceOverviewViewAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string ResourceOverviewWarnings {
            get {
                return ResourceManager.GetString("ResourceOverviewWarnings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        public static string ResourceTagsAdd {
            get {
                return ResourceManager.GetString("ResourceTagsAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create tag "{0}".
        /// </summary>
        public static string ResourceTagsCreate {
            get {
                return ResourceManager.GetString("ResourceTagsCreate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a tag to {0}.
        /// </summary>
        public static string ResourceTagsInputLabel {
            get {
                return ResourceManager.GetString("ResourceTagsInputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tag name.
        /// </summary>
        public static string ResourceTagsInputPlaceholder {
            get {
                return ResourceManager.GetString("ResourceTagsInputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string ResourceTagsLabel {
            get {
                return ResourceManager.GetString("ResourceTagsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove tag {0}.
        /// </summary>
        public static string ResourceTagsRemove {
            get {
                return ResourceManager.GetString("ResourceTagsRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string ResourceTagsSuggestions {
            get {
                return ResourceManager.GetString("ResourceTagsSuggestions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ResourcesActionsColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesActionsColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View options.
        /// </summary>
        public static string ResourcesChangeViewOptions {
            get {
                return ResourceManager.GetString("ResourcesChangeViewOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string ResourcesDetailsConnectionStringProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsConnectionStringProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Container arguments.
        /// </summary>
        public static string ResourcesDetailsContainerArgumentsProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerArgumentsProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Container command.
        /// </summary>
        public static string ResourcesDetailsContainerCommandProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerCommandProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Container ID.
        /// </summary>
        public static string ResourcesDetailsContainerIdProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerIdProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Container image.
        /// </summary>
        public static string ResourcesDetailsContainerImageProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerImageProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Container lifetime.
        /// </summary>
        public static string ResourcesDetailsContainerLifetimeProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerLifetimeProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Container ports.
        /// </summary>
        public static string ResourcesDetailsContainerPortsProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerPortsProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string ResourcesDetailsDisplayNameProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsDisplayNameProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executable arguments.
        /// </summary>
        public static string ResourcesDetailsExecutableArgumentsProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExecutableArgumentsProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        public static string ResourcesDetailsExecutablePathProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExecutablePathProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string ResourcesDetailsExecutableProcessIdProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExecutableProcessIdProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Working directory.
        /// </summary>
        public static string ResourcesDetailsExecutableWorkingDirectoryProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExecutableWorkingDirectoryProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit code.
        /// </summary>
        public static string ResourcesDetailsExitCodeProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExitCodeProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Health state.
        /// </summary>
        public static string ResourcesDetailsHealthStateProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsHealthStateProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ResourcesDetailsParameterValueProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsParameterValueProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch profile.
        /// </summary>
        public static string ResourcesDetailsProjectLaunchProfileProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsProjectLaunchProfileProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project path.
        /// </summary>
        public static string ResourcesDetailsProjectPathProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsProjectPathProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string ResourcesDetailsStartTimeProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsStartTimeProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ResourcesDetailsStateProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsStateProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop time.
        /// </summary>
        public static string ResourcesDetailsStopTimeProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsStopTimeProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Has filters.
        /// </summary>
        public static string ResourcesFiltered {
            get {
                return ResourceManager.GetString("ResourcesFiltered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export as Mermaid.
        /// </summary>
        public static string ResourcesGraphExportMermaidButton {
            get {
                return ResourceManager.GetString("ResourcesGraphExportMermaidButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResourcesGraphResetButton {
            get {
                return ResourceManager.GetString("ResourcesGraphResetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource actions for {0}.
        /// </summary>
        public static string ResourcesGraphResourceActionsButton {
            get {
                return ResourceManager.GetString("ResourcesGraphResourceActionsButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string ResourcesGraphZoomInButton {
            get {
                return ResourceManager.GetString("ResourcesGraphZoomInButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string ResourcesGraphZoomOutButton {
            get {
                return ResourceManager.GetString("ResourcesGraphZoomOutButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string ResourcesHeader {
            get {
                return ResourceManager.GetString("ResourcesHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide resource types.
        /// </summary>
        public static string ResourcesHideTypes {
            get {
                return ResourceManager.GetString("ResourcesHideTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No parameters found.
        /// </summary>
        public static string ResourcesNoParameters {
            get {
                return ResourceManager.GetString("ResourcesNoParameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No resources found.
        /// </summary>
        public static string ResourcesNoResources {
            get {
                return ResourceManager.GetString("ResourcesNoResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No filters.
        /// </summary>
        public static string ResourcesNotFiltered {
            get {
                return ResourceManager.GetString("ResourcesNotFiltered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} resources.
        /// </summary>
        public static string ResourcesPageTitle {
            get {
                return ResourceManager.GetString("ResourcesPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ResourcesResourceStatesHeader {
            get {
                return ResourceManager.GetString("ResourcesResourceStatesHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource types.
        /// </summary>
        public static string ResourcesResourceTypesHeader {
            get {
                return ResourceManager.GetString("ResourcesResourceTypesHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show resource types.
        /// </summary>
        public static string ResourcesShowTypes {
            get {
                return ResourceManager.GetString("ResourcesShowTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string ResourcesSourceColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesSourceColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string ResourcesStartTimeColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesStartTimeColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ResourcesStateColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesStateColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ResourcesTypeColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesTypeColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URLs.
        /// </summary>
        public static string ResourcesUrlsColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesUrlsColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing &lt;strong&gt;{0} parameters&lt;/strong&gt;.
        /// </summary>
        public static string TotalItemsFooterParametersPluralText {
            get {
                return ResourceManager.GetString("TotalItemsFooterParametersPluralText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing &lt;strong&gt;{0} parameter&lt;/strong&gt;.
        /// </summary>
        public static string TotalItemsFooterParametersSingularText {
            get {
                return ResourceManager.GetString("TotalItemsFooterParametersSingularText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing &lt;strong&gt;{0} resources&lt;/strong&gt;.
        /// </summary>
        public static string TotalItemsFooterPluralText {
            get {
                return ResourceManager.GetString("TotalItemsFooterPluralText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing &lt;strong&gt;{0} resource&lt;/strong&gt;.
        /// </summary>
        public static string TotalItemsFooterSingularText {
            get {
                return ResourceManager.GetString("TotalItemsFooterSingularText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting for health data....
        /// </summary>
        public static string WaitingForHealthDataMessage {
            get {
                return ResourceManager.GetString("WaitingForHealthDataMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string WaitingHealthDataStatusMessage {
            get {
                return ResourceManager.GetString("WaitingHealthDataStatusMessage", resourceCulture);
            }
        }
    }
}
