//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Dashboard.Resources.TerminalStrings", typeof(TerminalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string TerminalTitle {
            get {
                return ResourceManager.GetString("TerminalTitle", resourceCulture);
            }
        }

        public static string TerminalToolbarDecreaseFontSize {
            get {
                return ResourceManager.GetString("TerminalToolbarDecreaseFontSize", resourceCulture);
            }
        }

        public static string TerminalInputLabel {
            get {
                return ResourceManager.GetString("TerminalInputLabel", resourceCulture);
            }
        }

        public static string TerminalMountFailed {
            get {
                return ResourceManager.GetString("TerminalMountFailed", resourceCulture);
            }
        }

        public static string TerminalDisconnected {
            get {
                return ResourceManager.GetString("TerminalDisconnected", resourceCulture);
            }
        }

        public static string TerminalInputFailed {
            get {
                return ResourceManager.GetString("TerminalInputFailed", resourceCulture);
            }
        }

        public static string TerminalSizingFailed {
            get {
                return ResourceManager.GetString("TerminalSizingFailed", resourceCulture);
            }
        }

        public static string TerminalRetry {
            get {
                return ResourceManager.GetString("TerminalRetry", resourceCulture);
            }
        }

        public static string TerminalDismissError {
            get {
                return ResourceManager.GetString("TerminalDismissError", resourceCulture);
            }
        }

        public static string TerminalToolbarIncreaseFontSize {
            get {
                return ResourceManager.GetString("TerminalToolbarIncreaseFontSize", resourceCulture);
            }
        }

        public static string TerminalToolbarGridSize {
            get {
                return ResourceManager.GetString("TerminalToolbarGridSize", resourceCulture);
            }
        }

        public static string TerminalToolbarGridSizeAuto {
            get {
                return ResourceManager.GetString("TerminalToolbarGridSizeAuto", resourceCulture);
            }
        }

        public static string TerminalToolbarOpenInWindow {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindow", resourceCulture);
            }
        }

        public static string TerminalToolbarOpenInWindowBlocked {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindowBlocked", resourceCulture);
            }
        }

        public static string TerminalToolbarOpenInWindowFailed {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindowFailed", resourceCulture);
            }
        }

        public static string TerminalFocusControlsHint {
            get {
                return ResourceManager.GetString("TerminalFocusControlsHint", resourceCulture);
            }
        }
    }
}
