<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="StreamJsonRpc" />
    <ProjectReference Include="../../src/Aspire.Hosting.Native.Server/Aspire.Hosting.Native.Server.csproj" />
    <ProjectReference Include="AotSmoke/Aspire.Hosting.Native.Core.AotSmoke.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../playground/NativeHosting/AtsServer/NativeHosting.AtsServer.csproj" Aliases="NativeLegacyServer" />
    <ProjectReference Include="../../playground/NativeHosting/Ats/NativeHosting.Ats.csproj" Aliases="NativeLegacy" />
    <ProjectReference Include="../../playground/NativeHosting/Core/NativeHosting.Core.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../playground/NativeHosting/AtsCodegen/NativeHosting.AtsCodegen.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../playground/NativeHosting/ManagedAdapter/NativeHosting.ManagedAdapter.csproj" ReferenceOutputAssembly="false" />
    <Compile Remove="AotSmoke/**/*.cs" />
  </ItemGroup>
</Project>
