// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Aspire.Hosting.Azure.Provisioning.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class AspireProvisioningProxyGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Aspire.Hosting.Azure.Provisioning.GenerateAspireProvisioningProxyAttribute";
    private const string BicepDictionaryMetadataName = "Azure.Provisioning.BicepDictionary<T>";
    private const string BicepListMetadataName = "Azure.Provisioning.BicepList<T>";
    private const string BicepValueBaseMetadataName = "Azure.Provisioning.BicepValue";
    private const string BicepValueMetadataName = "Azure.Provisioning.BicepValue<T>";
    private const string ProvisionableResourceMetadataName = "Azure.Provisioning.Primitives.ProvisionableResource";
    private const string BicepValueProxyTypeName = "global::Aspire.Hosting.Azure.Provisioning.BicepValueProxy";
    private const string ProvisionableResourceProxyTypeName = "global::Aspire.Hosting.Azure.Provisioning.ProvisionableResourceProxy";
    private const string AzureResourceInfrastructureTypeName = "global::Aspire.Hosting.Azure.AzureResourceInfrastructure";
    private const string FactoryClassName = "AzureResourceInfrastructureProvisioningExtensions";

    private static readonly SymbolDisplayFormat s_typeDisplayFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static sourceContext =>
            sourceContext.AddSource(
                "GenerateAspireProvisioningProxyAttribute.g.cs",
                SourceText.From(
                    """
                    // <auto-generated/>
                    namespace Aspire.Hosting.Azure.Provisioning
                    {
                        #pragma warning disable ASPIREEXPORT018
                        [global::Aspire.Hosting.AspireExportProvider]
                        #pragma warning restore ASPIREEXPORT018
                        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
                        internal sealed class GenerateAspireProvisioningProxyAttribute : global::System.Attribute
                        {
                            public GenerateAspireProvisioningProxyAttribute(global::System.Type type)
                            {
                            }

                            public bool IsInfrastructureRoot { get; set; } = true;
                        }
                    }
                    """,
                    Encoding.UTF8)));

        var rootTypeGroups = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (_, _) => true,
                static (attributeContext, _) => GetRootTypes(attributeContext));

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(rootTypeGroups.Collect()),
            static (sourceContext, input) => Generate(
                sourceContext,
                GetGeneratedNamespace(input.Left.AssemblyName),
                input.Right.SelectMany(static roots => roots).ToImmutableArray()));
    }

    private static ImmutableArray<ProxyRoot> GetRootTypes(GeneratorAttributeSyntaxContext context)
    {
        var roots = ImmutableArray.CreateBuilder<ProxyRoot>();

        foreach (var attribute in context.Attributes)
        {
            if (attribute.ConstructorArguments.Length == 1 &&
                attribute.ConstructorArguments[0] is { Kind: TypedConstantKind.Type, Value: INamedTypeSymbol type })
            {
                var isInfrastructureRoot = true;
                foreach (var namedArgument in attribute.NamedArguments)
                {
                    if (namedArgument.Key == "IsInfrastructureRoot" &&
                        namedArgument.Value.Value is bool value)
                    {
                        isInfrastructureRoot = value;
                        break;
                    }
                }

                roots.Add(new ProxyRoot(type, isInfrastructureRoot));
            }
        }

        return roots.ToImmutable();
    }

    private static void Generate(
        SourceProductionContext context,
        string generatedNamespace,
        ImmutableArray<ProxyRoot> roots)
    {
        if (roots.IsDefaultOrEmpty)
        {
            return;
        }

        var normalizedRoots = roots
            .GroupBy(static root => root.Type, SymbolEqualityComparer.Default)
            .Select(static group => new ProxyRoot(
                (INamedTypeSymbol)group.Key,
                group.Any(static root => root.IsInfrastructureRoot)))
            .ToImmutableArray();
        var rootTypes = normalizedRoots.Select(static root => root.Type).ToImmutableArray();
        var discovery = DiscoverProxyTypes(rootTypes);
        if (discovery.Types.Count == 0)
        {
            return;
        }

        var proxyNames = CreateProxyNames(discovery.Types);
        var collectionNames = CreateCollectionNames(discovery.Collections, proxyNames, generatedNamespace);
        var source = new StringBuilder(
            """
            // <auto-generated/>
            #nullable enable

            """);
        source.Append("namespace ").Append(generatedNamespace).AppendLine();
        source.AppendLine("{");
        source.AppendLine();

        foreach (var type in discovery.Types.OrderBy(static type => type.ToDisplayString(), StringComparer.Ordinal))
        {
            GenerateProxy(source, type, proxyNames, collectionNames);
        }

        foreach (var collection in discovery.Collections
            .Where(collection => collectionNames.ContainsKey(collection.Type))
            .OrderBy(collection => collection.Type.ToDisplayString(), StringComparer.Ordinal))
        {
            GenerateCollectionProxy(source, collection, proxyNames, collectionNames);
        }

        GenerateFactoryClass(
            source,
            normalizedRoots,
            discovery.Types,
            proxyNames,
            collectionNames);

        source.AppendLine("}");
        context.AddSource("AspireProvisioningProxies.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string GetGeneratedNamespace(string? assemblyName)
    {
        if (string.IsNullOrEmpty(assemblyName))
        {
            return "Aspire.Hosting.Provisioning.Generated";
        }

        var namespaceName = new StringBuilder(assemblyName.Length + ".Generated".Length);
        foreach (var character in assemblyName)
        {
            namespaceName.Append(char.IsLetterOrDigit(character) || character is '_' or '.'
                ? character
                : '_');
        }
        namespaceName.Append(".Generated");
        return namespaceName.ToString();
    }

    private static DiscoveryResult DiscoverProxyTypes(ImmutableArray<INamedTypeSymbol> roots)
    {
        var types = new List<INamedTypeSymbol>();
        var collections = new List<CollectionShape>();
        var seenTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var seenCollections = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var rootNamespaces = new HashSet<string>(StringComparer.Ordinal);

        foreach (var root in roots)
        {
            rootNamespaces.Add(root.ContainingNamespace.ToDisplayString());
            AddType(root);
        }

        for (var index = 0; index < types.Count; index++)
        {
            var type = types[index];

            foreach (var property in GetExportableProperties(type))
            {
                DiscoverMappedType(property.Type);
            }

            foreach (var method in GetExportableMethods(type))
            {
                DiscoverMappedType(method.ReturnType);
                foreach (var parameter in method.Parameters)
                {
                    DiscoverMappedType(parameter.Type);
                }
            }
        }

        return new DiscoveryResult(types, collections);

        void DiscoverMappedType(ITypeSymbol type)
        {
            if (TryGetBicepValueArgument(type, out var valueType))
            {
                type = valueType;
            }

            type = type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);

            if (TryGetCollection(type, out var collectionKind, out var elementType, out var collectionType))
            {
                if (seenCollections.Add(collectionType))
                {
                    collections.Add(new CollectionShape(collectionType, elementType, collectionKind));
                    DiscoverMappedType(elementType);
                }

                return;
            }

            if (type is INamedTypeSymbol namedType &&
                namedType.TypeKind == TypeKind.Class &&
                !IsProvisionableResourceBase(namedType) &&
                namedType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat) != BicepValueBaseMetadataName &&
                IsInRootNamespace(namedType) &&
                !IsSimpleType(namedType))
            {
                AddType(namedType);
            }
        }

        bool IsInRootNamespace(INamedTypeSymbol type)
        {
            var namespaceName = type.ContainingNamespace.ToDisplayString();
            foreach (var rootNamespace in rootNamespaces)
            {
                if (namespaceName == rootNamespace ||
                    namespaceName.StartsWith(rootNamespace + ".", StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        void AddType(INamedTypeSymbol type)
        {
            type = (INamedTypeSymbol)type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
            if (type.TypeKind == TypeKind.Class &&
                !type.IsGenericType &&
                !type.IsStatic &&
                seenTypes.Add(type))
            {
                types.Add(type);
            }
        }
    }

    private static Dictionary<INamedTypeSymbol, string> CreateProxyNames(List<INamedTypeSymbol> types)
    {
        var names = new Dictionary<INamedTypeSymbol, string>(SymbolEqualityComparer.Default);

        foreach (var group in types.GroupBy(static type => type.Name, StringComparer.Ordinal))
        {
            if (group.Count() == 1)
            {
                var type = group.Single();
                names.Add(type, type.Name + "Proxy");
                continue;
            }

            var index = 0;
            foreach (var type in group.OrderBy(static type => type.ToDisplayString(), StringComparer.Ordinal))
            {
                var qualifiedName = SanitizeIdentifier(type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat));
                names.Add(type, qualifiedName + "_" + (++index).ToString(System.Globalization.CultureInfo.InvariantCulture) + "Proxy");
            }
        }

        return names;
    }

    private static Dictionary<INamedTypeSymbol, string> CreateCollectionNames(
        List<CollectionShape> collections,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        string generatedNamespace)
    {
        var supportedCollections = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var addedCollection = true;

        while (addedCollection)
        {
            addedCollection = false;
            foreach (var collection in collections)
            {
                if (!supportedCollections.Contains(collection.Type) &&
                    CanMapCollectionElement(collection.ElementType, proxyNames, supportedCollections))
                {
                    supportedCollections.Add(collection.Type);
                    addedCollection = true;
                }
            }
        }

        var names = new Dictionary<INamedTypeSymbol, string>(SymbolEqualityComparer.Default);
        var supportedShapes = collections.Where(collection => supportedCollections.Contains(collection.Type));
        var namePrefix = SanitizeIdentifier(generatedNamespace) + "_";
        foreach (var group in supportedShapes.GroupBy(
            collection => namePrefix + collection.Kind + "Of" + GetFriendlyTypeIdentifier(collection.ElementType) + "Proxy",
            StringComparer.Ordinal))
        {
            if (group.Count() == 1)
            {
                var collection = group.Single();
                names.Add(collection.Type, group.Key);
                continue;
            }

            var index = 0;
            foreach (var collection in group.OrderBy(
                static collection => collection.Type.ToDisplayString(),
                StringComparer.Ordinal))
            {
                var qualifiedElementName = SanitizeIdentifier(
                    collection.ElementType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat));
                names.Add(
                    collection.Type,
                    group.Key.Substring(0, group.Key.Length - "Proxy".Length) +
                    qualifiedElementName +
                    "_" +
                    (++index).ToString(System.Globalization.CultureInfo.InvariantCulture) +
                    "Proxy");
            }
        }

        return names;
    }

    private static bool CanMapCollectionElement(
        ITypeSymbol elementType,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        HashSet<INamedTypeSymbol> supportedCollections)
    {
        if (IsSimpleType(elementType))
        {
            return true;
        }

        if (elementType is not INamedTypeSymbol namedType)
        {
            return false;
        }

        return IsProvisionableResourceBase(namedType) ||
            proxyNames.ContainsKey(namedType) ||
            supportedCollections.Contains(namedType);
    }

    private static string GetFriendlyTypeIdentifier(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType || !namedType.IsGenericType)
        {
            return SanitizeIdentifier(type.Name);
        }

        var name = new StringBuilder(namedType.Name);
        foreach (var argument in namedType.TypeArguments)
        {
            name.Append("Of").Append(GetFriendlyTypeIdentifier(argument));
        }

        return SanitizeIdentifier(name.ToString());
    }

    private static string SanitizeIdentifier(string value)
    {
        var identifier = new StringBuilder(value.Length + 1);
        foreach (var character in value)
        {
            identifier.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (identifier.Length == 0 || char.IsDigit(identifier[0]))
        {
            identifier.Insert(0, '_');
        }

        return identifier.ToString();
    }

    private static void GenerateProxy(
        StringBuilder source,
        INamedTypeSymbol type,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        Dictionary<INamedTypeSymbol, string> collectionNames)
    {
        var proxyName = proxyNames[type];
        var underlyingTypeName = type.ToDisplayString(s_typeDisplayFormat);
        var isProvisionableResource = IsProvisionableResource(type);
        var proxyBaseType = GetProxyBaseType(type, proxyNames);

        source.AppendLine("    [global::Aspire.Hosting.AspireExportAttribute]");
        source.Append("    internal class ").Append(proxyName);
        if (proxyBaseType is not null)
        {
            source.Append(" : ").Append(proxyNames[proxyBaseType]);
        }
        else if (isProvisionableResource)
        {
            source.Append(" : ").Append(ProvisionableResourceProxyTypeName);
        }
        source.AppendLine();
        source.AppendLine("    {");
        source.Append("        internal ").Append(proxyName).Append('(').Append(underlyingTypeName).Append(" value)");
        if (proxyBaseType is not null || isProvisionableResource)
        {
            source.Append(" : base(value)");
        }
        source.AppendLine();
        source.AppendLine("        {");
        if (proxyBaseType is null && !isProvisionableResource)
        {
            source.AppendLine("            Inner = value ?? throw new global::System.ArgumentNullException(nameof(value));");
        }
        source.AppendLine("        }");
        source.AppendLine();
        if (proxyBaseType is not null || isProvisionableResource)
        {
            source.Append("        internal new ").Append(underlyingTypeName)
                .AppendLine(" Inner => (" + underlyingTypeName + ")base.Inner;");
        }
        else
        {
            source.Append("        internal ").Append(underlyingTypeName).AppendLine(" Inner { get; }");
        }

        foreach (var property in GetExportableProperties(type, includeInherited: proxyBaseType is null))
        {
            if (isProvisionableResource && property.Name == "BicepIdentifier")
            {
                continue;
            }

            if (TryMapType(property.Type, proxyNames, collectionNames, out var mappedType))
            {
                GenerateProperty(source, property, mappedType, proxyName);
            }
        }

        var mappedMethods = GetMappedMethods(type, proxyNames, collectionNames, includeInherited: proxyBaseType is null);
        foreach (var methodGroup in mappedMethods.GroupBy(static method => method.Method.Name, StringComparer.Ordinal))
        {
            var overloads = methodGroup.OrderBy(static method => method.Signature, StringComparer.Ordinal).ToList();
            for (var index = 0; index < overloads.Count; index++)
            {
                GenerateMethod(source, overloads[index], proxyName, index, overloads.Count);
            }
        }

        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void GenerateProperty(
        StringBuilder source,
        IPropertySymbol property,
        MappedType mappedType,
        string proxyName)
    {
        var canRead = property.GetMethod?.DeclaredAccessibility == Accessibility.Public;
        var canWrite = property.SetMethod is { DeclaredAccessibility: Accessibility.Public, IsInitOnly: false };
        if (!canRead && !canWrite)
        {
            return;
        }

        source.AppendLine();
        source.AppendLine("        [global::Aspire.Hosting.AspireExportAttribute]");
        if (mappedType is { Kind: MappedTypeKind.BicepValue, LiteralTypeName: not null })
        {
            AppendUnionAttribute(source, mappedType, "        ");
            source.AppendLine();
        }
        source.Append("        internal ").Append(mappedType.ExposedTypeName).Append(" @").Append(property.Name).AppendLine();
        source.AppendLine("        {");

        if (canRead)
        {
            source.Append("            get => ");
            AppendMappedFromUnderlying(source, "Inner.@" + property.Name, mappedType);
            source.AppendLine(";");
        }

        if (canWrite)
        {
            if (mappedType.Kind == MappedTypeKind.BicepValue)
            {
                GenerateBicepValueSetter(source, property, mappedType);
            }
            else
            {
                source.Append("            set => Inner.@").Append(property.Name).Append(" = ");
                AppendMappedToUnderlying(source, "value", mappedType);
                source.AppendLine(";");
            }
        }

        source.AppendLine("        }");

        if (canWrite && mappedType.Kind == MappedTypeKind.BicepValue)
        {
            source.AppendLine();
            AppendMethodExportAttribute(source, proxyName + ".clear" + property.Name, "Clear" + property.Name);
            source.Append("        internal void Clear").Append(property.Name).AppendLine("()");
            source.AppendLine("        {");
            source.Append("            Inner.@").Append(property.Name).AppendLine(".ClearValue();");
            source.AppendLine("        }");
        }
    }

    private static void GenerateBicepValueSetter(
        StringBuilder source,
        IPropertySymbol property,
        MappedType mappedType)
    {
        source.AppendLine("            set");
        source.AppendLine("            {");

        if (mappedType.LiteralTypeName is not null)
        {
            source.Append("                if (value is ").Append(mappedType.LiteralTypeName).AppendLine(" literal)");
            source.AppendLine("                {");
            source.Append("                    Inner.@").Append(property.Name).AppendLine(" = literal;");
            source.AppendLine("                }");
            source.Append("                else if (value is ").Append(BicepValueProxyTypeName).AppendLine(" bicepValue)");
        }
        else
        {
            source.AppendLine("                if (value is not null)");
        }

        source.AppendLine("                {");
        if (mappedType.LiteralTypeName is not null)
        {
            source.Append("                    bicepValue.AssignTo(Inner.@").Append(property.Name).AppendLine(");");
        }
        else
        {
            source.Append("                    value.AssignTo(Inner.@").Append(property.Name).AppendLine(");");
        }
        source.AppendLine("                }");
        source.AppendLine("                else");
        source.AppendLine("                {");
        source.Append("                    throw new global::System.ArgumentException(\"Expected ");
        if (mappedType.LiteralTypeName is not null)
        {
            source.Append(mappedType.LiteralTypeName).Append(" or ");
        }
        source.Append(BicepValueProxyTypeName).AppendLine(".\", nameof(value));");
        source.AppendLine("                }");
        source.AppendLine("            }");
    }

    private static List<MappedMethod> GetMappedMethods(
        INamedTypeSymbol type,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        Dictionary<INamedTypeSymbol, string> collectionNames,
        bool includeInherited)
    {
        var mappedMethods = new List<MappedMethod>();
        var projectedSignatures = new HashSet<string>(StringComparer.Ordinal);

        foreach (var method in GetExportableMethods(type, includeInherited).OrderBy(GetMethodSignature, StringComparer.Ordinal))
        {
            if (!TryMapMethod(method, proxyNames, collectionNames, out var mappedMethod))
            {
                continue;
            }

            var projectedSignature = method.Name + "(" + string.Join(
                ",",
                mappedMethod.Parameters.Select(static parameter => parameter.Type.ExposedTypeName)) + ")";
            if (projectedSignatures.Add(projectedSignature))
            {
                mappedMethods.Add(mappedMethod);
            }
        }

        return mappedMethods;
    }

    private static bool TryMapMethod(
        IMethodSymbol method,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        Dictionary<INamedTypeSymbol, string> collectionNames,
        out MappedMethod mappedMethod)
    {
        if (method.ReturnsByRef ||
            method.ReturnsByRefReadonly ||
            !TryMapType(method.ReturnType, proxyNames, collectionNames, out var returnType))
        {
            mappedMethod = null!;
            return false;
        }

        var mappedParameters = new List<MappedParameter>();
        foreach (var parameter in method.Parameters)
        {
            if (parameter.RefKind != RefKind.None ||
                !TryMapType(parameter.Type, proxyNames, collectionNames, out var parameterType))
            {
                mappedMethod = null!;
                return false;
            }

            mappedParameters.Add(new MappedParameter(parameter, parameterType));
        }

        mappedMethod = new MappedMethod(method, returnType, mappedParameters, GetMethodSignature(method));
        return true;
    }

    private static void GenerateMethod(
        StringBuilder source,
        MappedMethod mappedMethod,
        string proxyName,
        int overloadIndex,
        int overloadCount)
    {
        var method = mappedMethod.Method;
        var methodName = ToCamelCase(method.Name);
        var capabilityId = proxyName + "." + methodName + ".method";
        if (overloadCount > 1)
        {
            capabilityId += ".overload" +
                (overloadIndex + 1).ToString(System.Globalization.CultureInfo.InvariantCulture) +
                "_" +
                GetProjectedSignatureSuffix(mappedMethod.Parameters);
        }

        source.AppendLine();
        AppendMethodExportAttribute(source, capabilityId, method.Name);
        source.Append("        internal ").Append(mappedMethod.ReturnType.ExposedTypeName).Append(" @").Append(method.Name).Append('(');

        for (var index = 0; index < mappedMethod.Parameters.Count; index++)
        {
            if (index > 0)
            {
                source.Append(", ");
            }

            AppendMappedParameter(source, mappedMethod.Parameters[index], includeDefaultValue: false);
        }

        source.AppendLine(")");
        source.AppendLine("        {");

        var invocation = new StringBuilder();
        invocation.Append("Inner.@").Append(method.Name).Append('(');
        for (var index = 0; index < mappedMethod.Parameters.Count; index++)
        {
            if (index > 0)
            {
                invocation.Append(", ");
            }

            var mappedParameter = mappedMethod.Parameters[index];
            AppendMappedToUnderlying(invocation, "@" + GetParameterName(mappedParameter.Parameter), mappedParameter.Type);
        }
        invocation.Append(')');

        if (method.ReturnsVoid)
        {
            source.Append("            ").Append(invocation).AppendLine(";");
        }
        else
        {
            source.Append("            return ");
            AppendMappedFromUnderlying(source, invocation.ToString(), mappedMethod.ReturnType);
            source.AppendLine(";");
        }

        source.AppendLine("        }");
    }

    private static string GetProjectedSignatureSuffix(List<MappedParameter> parameters)
    {
        return parameters.Count == 0
            ? "none"
            : SanitizeIdentifier(string.Join("_", parameters.Select(static parameter => parameter.Type.ExposedTypeName)));
    }

    private static void GenerateCollectionProxy(
        StringBuilder source,
        CollectionShape collection,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        Dictionary<INamedTypeSymbol, string> collectionNames)
    {
        var proxyName = collectionNames[collection.Type];
        var underlyingTypeName = collection.Type.ToDisplayString(s_typeDisplayFormat);
        var elementTypeName = collection.ElementType
            .WithNullableAnnotation(NullableAnnotation.NotAnnotated)
            .ToDisplayString(s_typeDisplayFormat);
        var simpleElement = IsSimpleType(collection.ElementType);
        TryMapType(collection.ElementType, proxyNames, collectionNames, out var mappedElementType);

        source.AppendLine("    [global::Aspire.Hosting.AspireExportAttribute]");
        source.Append("    internal sealed class ").Append(proxyName).AppendLine();
        source.AppendLine("    {");
        source.Append("        internal ").Append(proxyName).Append('(').Append(underlyingTypeName).AppendLine(" value)");
        source.AppendLine("        {");
        source.AppendLine("            Inner = value ?? throw new global::System.ArgumentNullException(nameof(value));");
        source.AppendLine("        }");
        source.AppendLine();
        source.Append("        internal ").Append(underlyingTypeName).AppendLine(" Inner { get; }");
        source.AppendLine();
        source.AppendLine("        [global::Aspire.Hosting.AspireExportAttribute]");
        source.AppendLine("        internal int Count => Inner.Count;");

        if (collection.Kind == CollectionKind.Dictionary)
        {
            source.AppendLine();
            source.AppendLine("        [global::Aspire.Hosting.AspireExportAttribute]");
            source.AppendLine("        internal string[] Keys => new global::System.Collections.Generic.List<string>(Inner.Keys).ToArray();");
        }

        GenerateCollectionGetMethod(source, collection, proxyName, simpleElement, mappedElementType);
        GenerateCollectionSetMethod(source, collection, proxyName, elementTypeName, simpleElement, mappedElementType);

        if (collection.Kind == CollectionKind.List)
        {
            GenerateListMutationMethods(source, proxyName, elementTypeName, simpleElement, mappedElementType);
        }
        else
        {
            GenerateDictionaryMutationMethods(source, proxyName);
        }

        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void GenerateCollectionGetMethod(
        StringBuilder source,
        CollectionShape collection,
        string proxyName,
        bool simpleElement,
        MappedType mappedElementType)
    {
        source.AppendLine();
        if (!simpleElement)
        {
            source.AppendLine("        // Expression-backed complex elements cannot be materialized as model proxies because");
            source.AppendLine("        // Azure.Provisioning does not expose a literal model instance for those values.");
        }
        AppendMethodExportAttribute(source, proxyName + ".get.method", "Get");
        source.Append("        internal ")
            .Append(simpleElement ? BicepValueProxyTypeName : mappedElementType.ExposedTypeName)
            .Append(" Get(")
            .Append(collection.Kind == CollectionKind.List ? "int index" : "string key")
            .AppendLine(")");
        source.AppendLine("        {");

        var indexExpression = collection.Kind == CollectionKind.List ? "index" : "key";
        if (simpleElement)
        {
            source.Append("            return ").Append(BicepValueProxyTypeName)
                .Append(".Create(Inner[").Append(indexExpression).AppendLine("]);");
        }
        else
        {
            source.Append("            var literal = Inner[").Append(indexExpression).AppendLine("].Value;");
            source.AppendLine("            if (literal is null)");
            source.AppendLine("            {");
            source.AppendLine("                throw new global::System.InvalidOperationException(\"Expression-backed complex collection elements cannot be returned as model proxies.\");");
            source.AppendLine("            }");
            source.AppendLine();
            source.Append("            return ");
            AppendMappedFromUnderlying(source, "literal", mappedElementType);
            source.AppendLine(";");
        }

        source.AppendLine("        }");
    }

    private static void GenerateCollectionSetMethod(
        StringBuilder source,
        CollectionShape collection,
        string proxyName,
        string elementTypeName,
        bool simpleElement,
        MappedType mappedElementType)
    {
        source.AppendLine();
        AppendMethodExportAttribute(source, proxyName + ".set.method", "Set");
        source.Append("        internal void Set(")
            .Append(collection.Kind == CollectionKind.List ? "int index, " : "string key, ");
        AppendCollectionValueParameter(source, elementTypeName, simpleElement, mappedElementType);
        source.AppendLine(")");
        source.AppendLine("        {");
        source.Append("            Inner[")
            .Append(collection.Kind == CollectionKind.List ? "index" : "key")
            .Append("] = ");
        AppendCollectionValueToUnderlying(source, elementTypeName, simpleElement, mappedElementType);
        source.AppendLine(";");
        source.AppendLine("        }");
    }

    private static void GenerateListMutationMethods(
        StringBuilder source,
        string proxyName,
        string elementTypeName,
        bool simpleElement,
        MappedType mappedElementType)
    {
        source.AppendLine();
        AppendMethodExportAttribute(source, proxyName + ".add.method", "Add");
        source.Append("        internal void Add(");
        AppendCollectionValueParameter(source, elementTypeName, simpleElement, mappedElementType);
        source.AppendLine(")");
        source.AppendLine("        {");
        source.Append("            Inner.Add(");
        AppendCollectionValueToUnderlying(source, elementTypeName, simpleElement, mappedElementType);
        source.AppendLine(");");
        source.AppendLine("        }");

        source.AppendLine();
        AppendMethodExportAttribute(source, proxyName + ".insert.method", "Insert");
        source.Append("        internal void Insert(int index, ");
        AppendCollectionValueParameter(source, elementTypeName, simpleElement, mappedElementType);
        source.AppendLine(")");
        source.AppendLine("        {");
        source.Append("            Inner.Insert(index, ");
        AppendCollectionValueToUnderlying(source, elementTypeName, simpleElement, mappedElementType);
        source.AppendLine(");");
        source.AppendLine("        }");

        source.AppendLine();
        AppendMethodExportAttribute(source, proxyName + ".removeAt.method", "RemoveAt");
        source.AppendLine("        internal void RemoveAt(int index)");
        source.AppendLine("        {");
        source.AppendLine("            Inner.RemoveAt(index);");
        source.AppendLine("        }");

        source.AppendLine();
        AppendMethodExportAttribute(source, proxyName + ".clear.method", "Clear");
        source.AppendLine("        internal void Clear()");
        source.AppendLine("        {");
        source.AppendLine("            Inner.Clear();");
        source.AppendLine("        }");
    }

    private static void GenerateDictionaryMutationMethods(StringBuilder source, string proxyName)
    {
        source.AppendLine();
        AppendMethodExportAttribute(source, proxyName + ".remove.method", "Remove");
        source.AppendLine("        internal bool Remove(string key)");
        source.AppendLine("        {");
        source.AppendLine("            return Inner.Remove(key);");
        source.AppendLine("        }");

        source.AppendLine();
        AppendMethodExportAttribute(source, proxyName + ".clear.method", "Clear");
        source.AppendLine("        internal void Clear()");
        source.AppendLine("        {");
        source.AppendLine("            Inner.Clear();");
        source.AppendLine("        }");
    }

    private static void AppendCollectionValueParameter(
        StringBuilder source,
        string elementTypeName,
        bool simpleElement,
        MappedType mappedElementType)
    {
        if (simpleElement)
        {
            source.Append("[global::Aspire.Hosting.AspireUnionAttribute(typeof(")
                .Append(BicepValueProxyTypeName)
                .Append("), typeof(")
                .Append(elementTypeName)
                .Append("))] object value");
        }
        else
        {
            source.Append(mappedElementType.ExposedTypeName).Append(" value");
        }
    }

    private static void AppendCollectionValueToUnderlying(
        StringBuilder source,
        string elementTypeName,
        bool simpleElement,
        MappedType mappedElementType)
    {
        if (simpleElement)
        {
            source.Append(BicepValueProxyTypeName).Append(".Convert<").Append(elementTypeName).Append(">(value)");
        }
        else
        {
            AppendMappedToUnderlying(source, "value", mappedElementType);
        }
    }

    private static void GenerateFactoryClass(
        StringBuilder source,
        ImmutableArray<ProxyRoot> roots,
        List<INamedTypeSymbol> types,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        Dictionary<INamedTypeSymbol, string> collectionNames)
    {
        var concreteTypes = types
            .Where(static type => !type.IsAbstract)
            .OrderBy(static type => type.ToDisplayString(), StringComparer.Ordinal)
            .ToList();
        var factoryTypeNames = CreateFactoryTypeNames(types, proxyNames);

        source.AppendLine("    [global::Aspire.Hosting.AspireExportAttribute]");
        source.Append("    internal static class ").Append(FactoryClassName).AppendLine();
        source.AppendLine("    {");

        foreach (var root in roots
            .Where(root => root.IsInfrastructureRoot &&
                IsProvisionableResource(root.Type) &&
                proxyNames.ContainsKey(root.Type))
            .OrderBy(static root => root.Type.ToDisplayString(), StringComparer.Ordinal))
        {
            GenerateRootLookupMethod(
                source,
                root.Type,
                proxyNames[root.Type],
                factoryTypeNames[root.Type]);
        }

        foreach (var type in concreteTypes)
        {
            var proxyName = proxyNames[type];
            var factoryTypeName = factoryTypeNames[type];
            if (IsProvisionableResource(type))
            {
                GenerateResourceLookupMethods(source, type, proxyName, factoryTypeName);

                if (SelectConstructor(type, isProvisionableResource: true, proxyNames, collectionNames) is { } constructor)
                {
                    GenerateCreationMethod(source, type, proxyName, factoryTypeName, constructor, isProvisionableResource: true);
                }
            }
            else if (SelectConstructor(type, isProvisionableResource: false, proxyNames, collectionNames) is { } constructor)
            {
                GenerateCreationMethod(source, type, proxyName, factoryTypeName, constructor, isProvisionableResource: false);
            }
        }

        source.AppendLine("    }");
        source.AppendLine();
    }

    private static Dictionary<INamedTypeSymbol, string> CreateFactoryTypeNames(
        List<INamedTypeSymbol> types,
        Dictionary<INamedTypeSymbol, string> proxyNames)
    {
        var names = new Dictionary<INamedTypeSymbol, string>(SymbolEqualityComparer.Default);
        foreach (var group in types.GroupBy(static type => type.Name, StringComparer.Ordinal))
        {
            foreach (var type in group)
            {
                names.Add(
                    type,
                    group.Count() == 1
                        ? type.Name
                        : proxyNames[type].Substring(0, proxyNames[type].Length - "Proxy".Length));
            }
        }

        return names;
    }

    private static void GenerateRootLookupMethod(
        StringBuilder source,
        INamedTypeSymbol type,
        string proxyName,
        string factoryTypeName)
    {
        var methodName = "Get" + factoryTypeName;
        var underlyingTypeName = type.ToDisplayString(s_typeDisplayFormat);
        source.AppendLine();
        AppendFactoryExportAttribute(source, proxyName, methodName, "root");
        source.Append("        internal static ").Append(proxyName).Append(' ').Append(methodName)
            .Append("(this ").Append(AzureResourceInfrastructureTypeName).AppendLine(" infrastructure)");
        source.AppendLine("        {");
        AppendInfrastructureNullCheck(source);
        source.AppendLine("            var bicepIdentifier = global::Aspire.Hosting.AzureResourceExtensions.GetBicepIdentifier(infrastructure.AspireResource);");
        source.Append("            var value = global::System.Linq.Enumerable.Single(")
            .Append("global::System.Linq.Enumerable.OfType<").Append(underlyingTypeName)
            .Append(">(infrastructure.GetProvisionableResources()), ")
            .AppendLine("value => value.BicepIdentifier == bicepIdentifier);");
        source.Append("            return new ").Append(proxyName).AppendLine("(value);");
        source.AppendLine("        }");
    }

    private static void GenerateResourceLookupMethods(
        StringBuilder source,
        INamedTypeSymbol type,
        string proxyName,
        string factoryTypeName)
    {
        var underlyingTypeName = type.ToDisplayString(s_typeDisplayFormat);
        var getMethodName = "Get" + factoryTypeName + "ByIdentifier";
        source.AppendLine();
        AppendFactoryExportAttribute(source, proxyName, getMethodName, "byIdentifier");
        source.Append("        internal static ").Append(proxyName).Append(' ').Append(getMethodName)
            .Append("(this ").Append(AzureResourceInfrastructureTypeName)
            .AppendLine(" infrastructure, string bicepIdentifier)");
        source.AppendLine("        {");
        AppendInfrastructureNullCheck(source);
        source.Append("            var value = global::System.Linq.Enumerable.Single(")
            .Append("global::System.Linq.Enumerable.OfType<").Append(underlyingTypeName)
            .Append(">(infrastructure.GetProvisionableResources()), ")
            .AppendLine("value => value.BicepIdentifier == bicepIdentifier);");
        source.Append("            return new ").Append(proxyName).AppendLine("(value);");
        source.AppendLine("        }");

        var getAllMethodName = "Get" + PluralizeIdentifier(factoryTypeName);
        source.AppendLine();
        AppendFactoryExportAttribute(source, proxyName, getAllMethodName, "all");
        source.Append("        internal static ").Append(proxyName).Append("[] ").Append(getAllMethodName)
            .Append("(this ").Append(AzureResourceInfrastructureTypeName).AppendLine(" infrastructure)");
        source.AppendLine("        {");
        AppendInfrastructureNullCheck(source);
        source.Append("            var values = new global::System.Collections.Generic.List<").Append(proxyName).AppendLine(">();");
        source.AppendLine("            foreach (var resource in infrastructure.GetProvisionableResources())");
        source.AppendLine("            {");
        source.Append("                if (resource is ").Append(underlyingTypeName).AppendLine(" value)");
        source.AppendLine("                {");
        source.Append("                    values.Add(new ").Append(proxyName).AppendLine("(value));");
        source.AppendLine("                }");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            return values.ToArray();");
        source.AppendLine("        }");
    }

    private static void GenerateCreationMethod(
        StringBuilder source,
        INamedTypeSymbol type,
        string proxyName,
        string factoryTypeName,
        SelectedConstructor constructor,
        bool isProvisionableResource)
    {
        var methodName = (isProvisionableResource ? "Add" : "Create") + factoryTypeName;
        var underlyingTypeName = type.ToDisplayString(s_typeDisplayFormat);
        source.AppendLine();
        AppendFactoryExportAttribute(source, proxyName, methodName, "factory");
        source.Append("        internal static ").Append(proxyName).Append(' ').Append(methodName)
            .Append("(this ").Append(AzureResourceInfrastructureTypeName).Append(" infrastructure");

        foreach (var parameter in constructor.Parameters)
        {
            source.Append(", ");
            AppendMappedParameter(source, parameter, includeDefaultValue: true);
        }

        source.AppendLine(")");
        source.AppendLine("        {");
        AppendInfrastructureNullCheck(source);
        source.Append("            var value = new ").Append(underlyingTypeName).Append('(');
        for (var index = 0; index < constructor.Parameters.Count; index++)
        {
            if (index > 0)
            {
                source.Append(", ");
            }

            var parameter = constructor.Parameters[index];
            if (IsNullableFactoryProxyParameter(parameter))
            {
                source.Append('@').Append(parameter.Parameter.Name)
                    .Append(" is null ? null : @").Append(GetParameterName(parameter.Parameter)).Append(".Inner");
            }
            else
            {
                AppendMappedToUnderlying(source, "@" + GetParameterName(parameter.Parameter), parameter.Type);
            }
        }
        source.AppendLine(");");
        if (isProvisionableResource)
        {
            source.AppendLine("            infrastructure.Add(value);");
        }
        source.AppendLine();
        source.Append("            return new ").Append(proxyName).AppendLine("(value);");
        source.AppendLine("        }");
    }

    private static SelectedConstructor? SelectConstructor(
        INamedTypeSymbol type,
        bool isProvisionableResource,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        Dictionary<INamedTypeSymbol, string> collectionNames)
    {
        var constructors = new List<SelectedConstructor>();
        foreach (var constructor in type.InstanceConstructors.Where(
            static constructor => constructor.DeclaredAccessibility == Accessibility.Public))
        {
            var mappedParameters = new List<MappedParameter>();
            var canMap = true;
            foreach (var parameter in constructor.Parameters)
            {
                if (parameter.RefKind != RefKind.None ||
                    !TryMapType(parameter.Type, proxyNames, collectionNames, out var mappedType) ||
                    mappedType.Kind is MappedTypeKind.BicepValue or MappedTypeKind.Collection)
                {
                    canMap = false;
                    break;
                }

                mappedParameters.Add(new MappedParameter(parameter, mappedType));
            }

            if (canMap)
            {
                constructors.Add(new SelectedConstructor(constructor, mappedParameters));
            }
        }

        if (constructors.Count == 0)
        {
            return null;
        }

        if (!isProvisionableResource)
        {
            var parameterless = constructors.FirstOrDefault(static constructor => constructor.Parameters.Count == 0);
            if (parameterless is not null)
            {
                return parameterless;
            }
        }
        else
        {
            var resourceConstructors = constructors.Where(static constructor =>
                constructor.Parameters.Count > 0 &&
                constructor.Parameters[0].Parameter.Name == "bicepIdentifier" &&
                constructor.Parameters[0].Parameter.Type.SpecialType == SpecialType.System_String).ToList();
            if (resourceConstructors.Count > 0)
            {
                constructors = resourceConstructors;
            }
        }

        return constructors
            .OrderBy(static constructor => constructor.Parameters.Count(
                static parameter => !parameter.Parameter.HasExplicitDefaultValue))
            .ThenBy(static constructor => constructor.Parameters.Count)
            .ThenBy(static constructor => constructor.Constructor.ToDisplayString(), StringComparer.Ordinal)
            .First();
    }

    private static void AppendMappedParameter(
        StringBuilder source,
        MappedParameter mappedParameter,
        bool includeDefaultValue)
    {
        AppendUnionAttribute(source, mappedParameter.Type, string.Empty);
        source.Append(mappedParameter.Type.ExposedTypeName);
        if (includeDefaultValue && IsNullableFactoryProxyParameter(mappedParameter))
        {
            source.Append('?');
        }
        source.Append(" @").Append(GetParameterName(mappedParameter.Parameter));
        if (includeDefaultValue &&
            mappedParameter.Parameter.HasExplicitDefaultValue &&
            TryRenderDefaultValue(mappedParameter.Parameter, out var defaultValue))
        {
            source.Append(" = ").Append(defaultValue);
        }

    }

    private static string GetParameterName(IParameterSymbol parameter)
    {
        return parameter.Name == "arguments" ? "args" : parameter.Name;
    }

    private static bool IsNullableFactoryProxyParameter(MappedParameter parameter)
    {
        return parameter.Type.Kind is MappedTypeKind.Proxy or MappedTypeKind.ProvisionableResource &&
            (parameter.Parameter.Type.NullableAnnotation == NullableAnnotation.Annotated ||
                parameter.Parameter is { HasExplicitDefaultValue: true, ExplicitDefaultValue: null });
    }

    private static bool TryRenderDefaultValue(IParameterSymbol parameter, out string value)
    {
        var defaultValue = parameter.ExplicitDefaultValue;
        if (defaultValue is null)
        {
            value = parameter.Type.IsValueType &&
                !(parameter.Type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T })
                    ? "default(" + parameter.Type.ToDisplayString(s_typeDisplayFormat) + ")"
                    : "null";
            return true;
        }

        if (parameter.Type.TypeKind == TypeKind.Enum)
        {
            value = "(" + parameter.Type.ToDisplayString(s_typeDisplayFormat) + ")" +
                Convert.ToString(defaultValue, System.Globalization.CultureInfo.InvariantCulture);
            return true;
        }

        switch (defaultValue)
        {
            case string stringValue:
                value = SymbolDisplay.FormatLiteral(stringValue, quote: true);
                return true;
            case char charValue:
                value = SymbolDisplay.FormatLiteral(charValue, quote: true);
                return true;
            case bool boolValue:
                value = boolValue ? "true" : "false";
                return true;
            case sbyte or byte or short or ushort or int:
                value = Convert.ToString(defaultValue, System.Globalization.CultureInfo.InvariantCulture)!;
                return true;
            case uint uintValue:
                value = uintValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "U";
                return true;
            case long longValue:
                value = longValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "L";
                return true;
            case ulong ulongValue:
                value = ulongValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "UL";
                return true;
            case float floatValue when float.IsNaN(floatValue):
                value = "global::System.Single.NaN";
                return true;
            case float floatValue when float.IsPositiveInfinity(floatValue):
                value = "global::System.Single.PositiveInfinity";
                return true;
            case float floatValue when float.IsNegativeInfinity(floatValue):
                value = "global::System.Single.NegativeInfinity";
                return true;
            case float floatValue:
                value = floatValue.ToString("G9", System.Globalization.CultureInfo.InvariantCulture) + "F";
                return true;
            case double doubleValue when double.IsNaN(doubleValue):
                value = "global::System.Double.NaN";
                return true;
            case double doubleValue when double.IsPositiveInfinity(doubleValue):
                value = "global::System.Double.PositiveInfinity";
                return true;
            case double doubleValue when double.IsNegativeInfinity(doubleValue):
                value = "global::System.Double.NegativeInfinity";
                return true;
            case double doubleValue:
                value = doubleValue.ToString("G17", System.Globalization.CultureInfo.InvariantCulture) + "D";
                return true;
            case decimal decimalValue:
                value = decimalValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "M";
                return true;
            default:
                value = string.Empty;
                return false;
        }
    }

    private static void AppendInfrastructureNullCheck(StringBuilder source)
    {
        source.AppendLine("            if (infrastructure is null)");
        source.AppendLine("            {");
        source.AppendLine("                throw new global::System.ArgumentNullException(nameof(infrastructure));");
        source.AppendLine("            }");
        source.AppendLine();
    }

    private static void AppendFactoryExportAttribute(
        StringBuilder source,
        string proxyName,
        string methodName,
        string suffix)
    {
        AppendMethodExportAttribute(
            source,
            FactoryClassName + "." + proxyName + "." + ToCamelCase(methodName) + "." + suffix,
            methodName);
    }

    private static void AppendMethodExportAttribute(StringBuilder source, string capabilityId, string methodName)
    {
        source.Append("        [global::Aspire.Hosting.AspireExportAttribute(\"")
            .Append(capabilityId)
            .Append("\", MethodName = \"")
            .Append(ToCamelCase(methodName))
            .AppendLine("\")]");
    }

    private static void AppendUnionAttribute(StringBuilder source, MappedType mappedType, string indentation)
    {
        if (mappedType is { Kind: MappedTypeKind.BicepValue, LiteralTypeName: not null })
        {
            source.Append(indentation)
                .Append("[global::Aspire.Hosting.AspireUnionAttribute(typeof(")
                .Append(BicepValueProxyTypeName)
                .Append("), typeof(")
                .Append(mappedType.LiteralTypeName)
                .Append("))] ");
        }
    }

    private static string ToCamelCase(string value)
    {
        return value.Length == 0
            ? value
            : char.ToLowerInvariant(value[0]) + value.Substring(1);
    }

    private static string PluralizeIdentifier(string value)
    {
        if (value.Length > 1 &&
            value.EndsWith("y", StringComparison.Ordinal) &&
            "aeiouAEIOU".IndexOf(value[value.Length - 2]) < 0)
        {
            return value.Substring(0, value.Length - 1) + "ies";
        }

        return value + "s";
    }

    private static INamedTypeSymbol? GetProxyBaseType(
        INamedTypeSymbol type,
        Dictionary<INamedTypeSymbol, string> proxyNames)
    {
        for (var current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (proxyNames.ContainsKey(current))
            {
                return current;
            }
        }

        return null;
    }

    private static IEnumerable<IPropertySymbol> GetExportableProperties(
        INamedTypeSymbol type,
        bool includeInherited = true)
    {
        var seenPropertyNames = new HashSet<string>(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = type;
            current is not null && current.SpecialType != SpecialType.System_Object;
            current = includeInherited ? current.BaseType : null)
        {
            foreach (var property in current.GetMembers().OfType<IPropertySymbol>())
            {
                if (!property.IsStatic &&
                    !property.IsIndexer &&
                    property.DeclaredAccessibility == Accessibility.Public &&
                    seenPropertyNames.Add(property.Name))
                {
                    yield return property;
                }
            }

            if (IsProvisionableResourceBase(current))
            {
                yield break;
            }
        }
    }

    private static IEnumerable<IMethodSymbol> GetExportableMethods(
        INamedTypeSymbol type,
        bool includeInherited = true)
    {
        var seenSignatures = new HashSet<string>(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = type;
            current is not null && current.SpecialType != SpecialType.System_Object;
            current = includeInherited ? current.BaseType : null)
        {
            foreach (var method in current.GetMembers().OfType<IMethodSymbol>())
            {
                if (!method.IsStatic &&
                    !method.IsGenericMethod &&
                    method.MethodKind == MethodKind.Ordinary &&
                    method.Name != nameof(ToString) &&
                    method.DeclaredAccessibility == Accessibility.Public &&
                    seenSignatures.Add(GetMethodSignature(method)))
                {
                    yield return method;
                }
            }

            if (IsProvisionableResourceBase(current))
            {
                yield break;
            }
        }
    }

    private static string GetMethodSignature(IMethodSymbol method)
    {
        return method.Name + "(" + string.Join(
            ",",
            method.Parameters.Select(static parameter =>
                parameter.RefKind + ":" +
                parameter.Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat))) + ")";
    }

    private static bool TryMapType(
        ITypeSymbol type,
        Dictionary<INamedTypeSymbol, string> proxyNames,
        Dictionary<INamedTypeSymbol, string> collectionNames,
        out MappedType mappedType)
    {
        if (type.SpecialType == SpecialType.System_Void)
        {
            mappedType = new MappedType("void", MappedTypeKind.Direct);
            return true;
        }

        if (TryGetBicepValueArgument(type, out var bicepValueType))
        {
            var literalType = bicepValueType is INamedTypeSymbol
                {
                    OriginalDefinition.SpecialType: SpecialType.System_Nullable_T,
                    TypeArguments.Length: 1
                } nullableValueType
                    ? nullableValueType.TypeArguments[0]
                    : bicepValueType.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
            var literalTypeName = IsSimpleType(bicepValueType)
                ? literalType.ToDisplayString(s_typeDisplayFormat).TrimEnd('?')
                : null;

            mappedType = new MappedType(
                literalTypeName is null ? BicepValueProxyTypeName : "object",
                MappedTypeKind.BicepValue,
                literalTypeName,
                bicepValueType.ToDisplayString(s_typeDisplayFormat));
            return true;
        }

        if (IsSimpleType(type))
        {
            mappedType = new MappedType(type.ToDisplayString(s_typeDisplayFormat), MappedTypeKind.Direct);
            return true;
        }

        if (type is INamedTypeSymbol namedType)
        {
            if (proxyNames.TryGetValue(namedType, out var proxyName))
            {
                var isNullable = type.NullableAnnotation == NullableAnnotation.Annotated;
                mappedType = new MappedType(proxyName + (isNullable ? "?" : string.Empty), MappedTypeKind.Proxy, isNullable: isNullable);
                return true;
            }

            if (collectionNames.TryGetValue(namedType, out var collectionProxyName))
            {
                var isNullable = type.NullableAnnotation == NullableAnnotation.Annotated;
                mappedType = new MappedType(collectionProxyName + (isNullable ? "?" : string.Empty), MappedTypeKind.Collection, isNullable: isNullable);
                return true;
            }

            if (IsProvisionableResourceBase(namedType))
            {
                var isNullable = type.NullableAnnotation == NullableAnnotation.Annotated;
                mappedType = new MappedType(
                    ProvisionableResourceProxyTypeName + (isNullable ? "?" : string.Empty),
                    MappedTypeKind.ProvisionableResource,
                    isNullable: isNullable);
                return true;
            }
        }

        mappedType = default;
        return false;
    }

    private static bool TryGetBicepValueArgument(ITypeSymbol type, out ITypeSymbol valueType)
    {
        if (type is INamedTypeSymbol { IsGenericType: true, TypeArguments.Length: 1 } namedType &&
            namedType.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat) == BicepValueMetadataName)
        {
            valueType = namedType.TypeArguments[0];
            return true;
        }

        valueType = null!;
        return false;
    }

    private static bool TryGetCollection(
        ITypeSymbol type,
        out CollectionKind kind,
        out ITypeSymbol elementType,
        out INamedTypeSymbol collectionType)
    {
        if (type is INamedTypeSymbol { IsGenericType: true, TypeArguments.Length: 1 } namedType)
        {
            var metadataName = namedType.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
            if (metadataName == BicepListMetadataName)
            {
                kind = CollectionKind.List;
                elementType = namedType.TypeArguments[0];
                collectionType = namedType;
                return true;
            }

            if (metadataName == BicepDictionaryMetadataName)
            {
                kind = CollectionKind.Dictionary;
                elementType = namedType.TypeArguments[0];
                collectionType = namedType;
                return true;
            }
        }

        kind = default;
        elementType = null!;
        collectionType = null!;
        return false;
    }

    private static bool IsProvisionableResourceBase(INamedTypeSymbol type)
    {
        return type.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
            .ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat) == ProvisionableResourceMetadataName;
    }

    private static bool IsProvisionableResource(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType)
        {
            if (IsProvisionableResourceBase(current))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsSimpleType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullableType)
        {
            return IsSimpleType(nullableType.TypeArguments[0]);
        }

        if (type.TypeKind == TypeKind.Enum)
        {
            return true;
        }

        if (type.SpecialType is
            SpecialType.System_String or
            SpecialType.System_Char or
            SpecialType.System_Boolean or
            SpecialType.System_SByte or
            SpecialType.System_Byte or
            SpecialType.System_Int16 or
            SpecialType.System_UInt16 or
            SpecialType.System_Int32 or
            SpecialType.System_UInt32 or
            SpecialType.System_Int64 or
            SpecialType.System_UInt64 or
            SpecialType.System_Single or
            SpecialType.System_Double or
            SpecialType.System_Decimal)
        {
            return true;
        }

        var metadataName = type.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
            .ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
        return metadataName is
            "System.DateTime" or
            "System.DateTimeOffset" or
            "System.DateOnly" or
            "System.TimeOnly" or
            "System.TimeSpan" or
            "System.Guid" or
            "System.Uri";
    }

    private static void AppendMappedFromUnderlying(StringBuilder source, string expression, MappedType mappedType)
    {
        switch (mappedType.Kind)
        {
            case MappedTypeKind.Direct:
                source.Append(expression);
                break;
            case MappedTypeKind.BicepValue:
                source.Append(BicepValueProxyTypeName).Append(".Create(").Append(expression).Append(')');
                break;
            case MappedTypeKind.Proxy:
            case MappedTypeKind.Collection:
            case MappedTypeKind.ProvisionableResource:
                if (mappedType.IsNullable)
                {
                    source.Append(expression).Append(" is null ? null : new ")
                        .Append(mappedType.ExposedTypeName.TrimEnd('?')).Append('(').Append(expression).Append(')');
                }
                else
                {
                    source.Append("new ").Append(mappedType.ExposedTypeName).Append('(').Append(expression).Append(')');
                }
                break;
        }
    }

    private static void AppendMappedToUnderlying(StringBuilder source, string expression, MappedType mappedType)
    {
        if (mappedType.Kind is MappedTypeKind.Proxy or MappedTypeKind.Collection or MappedTypeKind.ProvisionableResource)
        {
            source.Append(expression).Append(mappedType.IsNullable ? "?.Inner" : ".Inner");
        }
        else if (mappedType.Kind == MappedTypeKind.BicepValue)
        {
            source.Append(BicepValueProxyTypeName)
                .Append(".Convert<")
                .Append(mappedType.ValueTypeName)
                .Append(">(")
                .Append(expression)
                .Append(')');
        }
        else
        {
            source.Append(expression);
        }
    }

    private enum CollectionKind
    {
        List,
        Dictionary
    }

    private enum MappedTypeKind
    {
        Direct,
        BicepValue,
        Proxy,
        Collection,
        ProvisionableResource
    }

    private sealed class DiscoveryResult
    {
        public DiscoveryResult(List<INamedTypeSymbol> types, List<CollectionShape> collections)
        {
            Types = types;
            Collections = collections;
        }

        public List<INamedTypeSymbol> Types { get; }

        public List<CollectionShape> Collections { get; }
    }

    private readonly struct ProxyRoot
    {
        public ProxyRoot(INamedTypeSymbol type, bool isInfrastructureRoot)
        {
            Type = type;
            IsInfrastructureRoot = isInfrastructureRoot;
        }

        public INamedTypeSymbol Type { get; }

        public bool IsInfrastructureRoot { get; }
    }

    private readonly struct CollectionShape
    {
        public CollectionShape(INamedTypeSymbol type, ITypeSymbol elementType, CollectionKind kind)
        {
            Type = type;
            ElementType = elementType;
            Kind = kind;
        }

        public INamedTypeSymbol Type { get; }

        public ITypeSymbol ElementType { get; }

        public CollectionKind Kind { get; }
    }

    private sealed class MappedMethod
    {
        public MappedMethod(
            IMethodSymbol method,
            MappedType returnType,
            List<MappedParameter> parameters,
            string signature)
        {
            Method = method;
            ReturnType = returnType;
            Parameters = parameters;
            Signature = signature;
        }

        public IMethodSymbol Method { get; }

        public MappedType ReturnType { get; }

        public List<MappedParameter> Parameters { get; }

        public string Signature { get; }
    }

    private sealed class SelectedConstructor
    {
        public SelectedConstructor(IMethodSymbol constructor, List<MappedParameter> parameters)
        {
            Constructor = constructor;
            Parameters = parameters;
        }

        public IMethodSymbol Constructor { get; }

        public List<MappedParameter> Parameters { get; }
    }

    private readonly struct MappedParameter
    {
        public MappedParameter(IParameterSymbol parameter, MappedType type)
        {
            Parameter = parameter;
            Type = type;
        }

        public IParameterSymbol Parameter { get; }

        public MappedType Type { get; }
    }

    private readonly struct MappedType
    {
        public MappedType(
            string exposedTypeName,
            MappedTypeKind kind,
            string? literalTypeName = null,
            string? valueTypeName = null,
            bool isNullable = false)
        {
            ExposedTypeName = exposedTypeName;
            Kind = kind;
            LiteralTypeName = literalTypeName;
            ValueTypeName = valueTypeName;
            IsNullable = isNullable;
        }

        public string ExposedTypeName { get; }

        public MappedTypeKind Kind { get; }

        public string? LiteralTypeName { get; }

        public string? ValueTypeName { get; }

        public bool IsNullable { get; }
    }
}
