// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Aspire.Shared;
using Aspire.TypeSystem;
using Microsoft.Extensions.Logging;
using System.Xml;
using System.Xml.Linq;

namespace Aspire.Cli.Projects;

/// <summary>
/// The build tool that owns a Java AppHost project.
/// </summary>
internal enum JavaAppHostToolchain
{
    /// <summary>
    /// No build tool. The AppHost is a single file compiled directly with <c>javac</c>.
    /// </summary>
    Javac,

    /// <summary>
    /// A Maven project, identified by <c>pom.xml</c>.
    /// </summary>
    Maven,

    /// <summary>
    /// A Gradle project, identified by <c>build.gradle</c> or <c>build.gradle.kts</c>.
    /// </summary>
    Gradle
}

/// <summary>
/// Selects the build tool for a Java AppHost from the files on disk and rewrites the runtime spec to
/// match, mirroring what <see cref="TypeScriptAppHostToolchainResolver"/> does for package managers.
/// </summary>
/// <remarks>
/// <para>
/// Java AppHosts started life as a single <c>AppHost.java</c> compiled with <c>javac</c>, which needs
/// nothing but a JDK. That remains the default and the fallback: adopting a build tool is opt-in, and
/// is done by adding a <c>pom.xml</c> or <c>build.gradle</c>. A project model is what unlocks
/// third-party dependencies and full IDE support, because the Java language server derives its
/// classpath from build files.
/// </para>
/// <para>
/// Under a build tool the AppHost is still launched with a plain <c>java</c> command rather than
/// through <c>mvn exec:java</c> or <c>gradle run</c>. Those run the application inside, or as a child
/// of, the build tool's own JVM, so console signals reach the build tool instead of the AppHost and an
/// orderly shutdown never happens. Launching directly also means the arguments the CLI appends arrive
/// as real argv entries instead of being spliced into a shell string.
/// </para>
/// </remarks>
internal static class JavaAppHostToolchainResolver
{
    private const string MavenPomFileName = "pom.xml";
    private const string GradleBuildFileName = "build.gradle";
    private const string GradleKotlinBuildFileName = "build.gradle.kts";
    private const string GradleSettingsFileName = "settings.gradle";
    private const string GradleKotlinSettingsFileName = "settings.gradle.kts";

    /// <summary>
    /// Directory the resolved runtime dependencies are copied into, relative to the build output.
    /// A directory of JARs is used rather than a classpath string because the JVM expands a
    /// <c>dir/*</c> classpath entry itself, so no shell and no generated argument file is needed.
    /// </summary>
    private const string DependencyDirectoryName = "aspire-deps";

    /// <summary>
    /// Gradle init script that adds a dependency-copying task to whatever project is being built.
    /// </summary>
    /// <remarks>
    /// An init script is used so a Gradle AppHost needs no cooperation from the user's build file.
    /// Maven ships <c>dependency:copy-dependencies</c> out of the box, but Gradle has no built-in
    /// equivalent, and requiring an edit to <c>build.gradle</c> would make adopting Gradle a worse
    /// experience than Maven for no reason.
    /// See https://docs.gradle.org/current/userguide/init_scripts.html.
    /// </remarks>
    private const string GradleInitScript = $$"""
        // Generated by Aspire. Adds the task that stages the AppHost's runtime classpath so the
        // AppHost can be launched with a plain `java` command instead of through Gradle.
        //
        // Sync rather than Copy: the classpath is the whole directory, so a JAR left behind by a
        // dependency that was upgraded or removed would still be loaded. Sync deletes whatever is
        // in the destination but not in the configuration, and stays incremental while doing it.
        // https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Sync.html
        allprojects {
            tasks.register("aspireCopyDependencies", Sync) {
                from configurations.named("runtimeClasspath")
                into layout.buildDirectory.dir("{{DependencyDirectoryName}}")
            }
        }
        """;

    internal const string GradleInitScriptRelativePath = ".aspire/aspire-gradle-init.gradle";

    /// <summary>
    /// <see cref="GradleInitScriptRelativePath"/> with the separators this platform uses.
    /// </summary>
    private static string GradleInitScriptPath => GradleInitScriptRelativePath.Replace('/', Path.DirectorySeparatorChar);

    public static bool IsJavaLanguage(LanguageInfo? language)
    {
        return language is not null &&
            language.LanguageId.Value.Equals(KnownLanguageId.Java, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Conventional source root a build tool compiles from. When the AppHost lives here the build
    /// file is at the project root, three directories up.
    /// https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
    /// </summary>
    private static readonly string[] s_conventionalSourceRootSegments = ["src", "main", "java"];

    public static JavaAppHostToolchainResolution Resolve(DirectoryInfo appHostDirectory, ILogger? logger = null)
    {
        var resolution = ResolveWithReason(appHostDirectory);
        logger?.LogDebug(
            "Selected Java AppHost build tool '{BuildTool}' rooted at '{ProjectDirectory}' because {Reason}.",
            resolution.Toolchain,
            resolution.ProjectDirectory.FullName,
            resolution.Reason);

        return resolution;
    }

    internal static JavaAppHostToolchainResolution ResolveWithReason(DirectoryInfo appHostDirectory)
    {
        // The AppHost directory is checked first, then the project root implied by the conventional
        // source layout. An unbounded walk up the tree is deliberately avoided: a pom.xml in some
        // arbitrary ancestor usually belongs to an unrelated project that happens to contain the
        // AppHost folder, whereas src/main/java is only ever a build tool's source root.
        foreach (var candidate in GetCandidateProjectDirectories(appHostDirectory))
        {
            if (File.Exists(Path.Combine(candidate.FullName, MavenPomFileName)))
            {
                return new(JavaAppHostToolchain.Maven, candidate, $"{MavenPomFileName} found in {candidate.FullName}");
            }

            foreach (var gradleBuildFileName in new[] { GradleBuildFileName, GradleKotlinBuildFileName })
            {
                if (File.Exists(Path.Combine(candidate.FullName, gradleBuildFileName)))
                {
                    return new(JavaAppHostToolchain.Gradle, candidate, $"{gradleBuildFileName} found in {candidate.FullName}");
                }
            }
        }

        return new(JavaAppHostToolchain.Javac, appHostDirectory, $"no build file found in {appHostDirectory.FullName}");
    }

    private static IEnumerable<DirectoryInfo> GetCandidateProjectDirectories(DirectoryInfo appHostDirectory)
    {
        yield return appHostDirectory;

        // Walk back out of src/main/java only when the directory names actually match, so an AppHost
        // that merely sits three levels deep is not mistaken for a conventional project layout.
        var candidate = appHostDirectory;
        foreach (var segment in s_conventionalSourceRootSegments.Reverse())
        {
            if (!string.Equals(candidate.Name, segment, PathComparison) || candidate.Parent is null)
            {
                yield break;
            }

            candidate = candidate.Parent;
        }

        yield return candidate;
    }

    private static StringComparison PathComparison =>
        OperatingSystem.IsLinux() ? StringComparison.Ordinal : StringComparison.OrdinalIgnoreCase;

    private static StringComparer PathComparer =>
        OperatingSystem.IsLinux() ? StringComparer.Ordinal : StringComparer.OrdinalIgnoreCase;

    public static string GetDisplayName(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Javac => "Java",
            JavaAppHostToolchain.Maven => "Java (Maven)",
            JavaAppHostToolchain.Gradle => "Java (Gradle)",
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    /// <summary>
    /// Returns how the build tool should be invoked. The wrapper checked into the project is required,
    /// so the AppHost always builds with the tool version the project pins.
    /// </summary>
    /// <param name="projectDirectory">Directory holding the build file and the wrapper.</param>
    /// <param name="appHostDirectory">Directory the command runs in, which the wrapper path is relative to.</param>
    /// <param name="toolchain">The resolved build tool.</param>
    internal static JavaToolInvocation GetToolInvocation(
        DirectoryInfo projectDirectory,
        DirectoryInfo appHostDirectory,
        JavaAppHostToolchain toolchain)
    {
        var (wrapperName, generateCommand, wrapperTool) = toolchain switch
        {
            // -N keeps the goal from recursing into the modules of a multi-module build.
            JavaAppHostToolchain.Maven => (OperatingSystem.IsWindows() ? "mvnw.cmd" : "mvnw", "mvn -N wrapper:wrapper", JavaWrapperTool.Maven),
            JavaAppHostToolchain.Gradle => (OperatingSystem.IsWindows() ? "gradlew.bat" : "gradlew", "gradle wrapper", JavaWrapperTool.Gradle),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };

        var wrapperPath = JavaWrapper.Find(projectDirectory.FullName, wrapperName, wrapperTool);

        // A globally installed Maven or Gradle is deliberately not used as a fallback: the wrapper pins the
        // tool version in the repository, so every machine builds the AppHost with the same one. Falling
        // back silently would make the AppHost build depend on whatever the developer happens to have.
        if (wrapperPath is null)
        {
            throw new InvalidOperationException(
                $"The Java AppHost project in '{projectDirectory.FullName}' declares a {GetDisplayName(toolchain)} " +
                $"build but ships no {wrapperName}, and none was found at an enclosing build root. Generate one " +
                $"with '{generateCommand}', or remove the build file to build the AppHost with javac instead.");
        }

        var wrapperDirectory = new DirectoryInfo(Path.GetDirectoryName(wrapperPath)!);

        var (command, prefixArgs) = JavaWrapper.GetInvocation(wrapperPath, appHostDirectory.FullName, OperatingSystem.IsWindows());

        return new JavaToolInvocation(command, prefixArgs, wrapperDirectory);
    }

    /// <summary>
    /// Rewrites the runtime spec for the resolved build tool. The <see cref="JavaAppHostToolchain.Javac"/>
    /// spec is returned unchanged so an AppHost without build files behaves exactly as before.
    /// </summary>
    public static RuntimeSpec ApplyToRuntimeSpec(RuntimeSpec baseRuntimeSpec, JavaAppHostToolchainResolution resolution, DirectoryInfo appHostDirectory)
        => ApplyToRuntimeSpec(baseRuntimeSpec, resolution, appHostDirectory, out _);

    /// <summary>
    /// Rewrites the runtime spec and returns the dependency installation commands required by the
    /// selected Java build layout.
    /// </summary>
    public static RuntimeSpec ApplyToRuntimeSpec(
        RuntimeSpec baseRuntimeSpec,
        JavaAppHostToolchainResolution resolution,
        DirectoryInfo appHostDirectory,
        out CommandSpec[]? installDependencies)
    {
        var toolchain = resolution.Toolchain;
        if (toolchain == JavaAppHostToolchain.Javac)
        {
            installDependencies = baseRuntimeSpec.InstallDependencies is null
                ? null
                : [baseRuntimeSpec.InstallDependencies];
            return baseRuntimeSpec;
        }

        var invocation = GetToolInvocation(resolution.ProjectDirectory, appHostDirectory, toolchain);

        // Commands run with the AppHost directory as their working directory, which is not the project
        // directory in the src/main/java layout, so every path below is rewritten relative to it.
        var projectPath = GetRelativeProjectPath(resolution.ProjectDirectory, appHostDirectory);
        var classesDirectory = CombineProjectPath(projectPath, GetClassesDirectory(toolchain));
        var dependencyDirectory = CombineProjectPath(projectPath, GetDependencyDirectory(toolchain));
        var usesMavenReactor = toolchain == JavaAppHostToolchain.Maven
            && !string.Equals(invocation.WrapperDirectory.FullName, resolution.ProjectDirectory.FullName, PathComparison)
            && IsMavenReactorModule(invocation.WrapperDirectory, resolution.ProjectDirectory);
        installDependencies = CreateInstallCommands(
            toolchain,
            invocation,
            resolution.ProjectDirectory,
            appHostDirectory,
            projectPath,
            usesMavenReactor);

        return new RuntimeSpec
        {
            Language = baseRuntimeSpec.Language,
            DisplayName = GetDisplayName(toolchain),
            CodeGenLanguage = baseRuntimeSpec.CodeGenLanguage,
            DetectionPatterns = baseRuntimeSpec.DetectionPatterns,
            Initialize = baseRuntimeSpec.Initialize,
            // RuntimeSpec has a single-command public contract. GuestRuntime receives the full internal
            // sequence above; keeping the first command here preserves the spec's diagnostic shape.
            InstallDependencies = installDependencies[0],
            PreExecute = [CreateCompileCommand(toolchain, baseRuntimeSpec, projectPath, classesDirectory, dependencyDirectory)],
            Execute = CreateExecuteCommand(classesDirectory, dependencyDirectory),
            WatchExecute = baseRuntimeSpec.WatchExecute,
            PublishExecute = baseRuntimeSpec.PublishExecute,
            ExtensionLaunchCapability = baseRuntimeSpec.ExtensionLaunchCapability,
            CertificateBundleEnvironmentVariable = baseRuntimeSpec.CertificateBundleEnvironmentVariable,
            MigrationFiles = baseRuntimeSpec.MigrationFiles
        };
    }

    /// <summary>
    /// Writes the Gradle init script when the resolved toolchain needs it.
    /// </summary>
    /// <remarks>
    /// This is not done through <see cref="RuntimeSpec.MigrationFiles"/> because those are written
    /// with a plain file write that fails when the parent directory does not exist yet, and the
    /// script lives under <c>.aspire</c>.
    /// </remarks>
    public static async Task EnsureToolchainFilesExistAsync(
        JavaAppHostToolchainResolution resolution,
        CancellationToken cancellationToken)
    {
        if (resolution.Toolchain != JavaAppHostToolchain.Gradle)
        {
            return;
        }

        // Written into the project directory rather than the AppHost directory so it sits alongside
        // the build file it augments, which is where the --init-script argument points.
        var scriptPath = Path.Combine(resolution.ProjectDirectory.FullName, GradleInitScriptPath);

        Directory.CreateDirectory(Path.GetDirectoryName(scriptPath)!);

        // Rewritten every run rather than only when missing, so a script left behind by an older
        // Aspire version cannot silently keep staging dependencies the wrong way.
        //
        // Written through a temporary sibling and moved into place because writing directly truncates
        // first: a second `aspire run` starting while this one is mid-write leaves Gradle reading a
        // half-written script, which fails with a syntax error that points at the generated file rather
        // than at the race. File.Move within a directory is atomic on every platform we support.
        var temporaryPath = $"{scriptPath}.{Environment.ProcessId}.tmp";

        try
        {
            await File.WriteAllTextAsync(temporaryPath, GradleInitScript, cancellationToken).ConfigureAwait(false);
            File.Move(temporaryPath, scriptPath, overwrite: true);
        }
        catch
        {
            try
            {
                File.Delete(temporaryPath);
            }
            catch
            {
                // Losing a temp file matters far less than the original failure, which is rethrown.
            }

            throw;
        }
    }

    /// <summary>
    /// Removes staged dependencies that the build tool will not remove itself, immediately before it
    /// restages them.
    /// </summary>
    /// <remarks>
    /// The AppHost is launched with the whole staging directory on its classpath as <c>dir/*</c>, and
    /// <c>dependency:copy-dependencies</c> only ever adds to that directory. Upgrading a dependency
    /// changes the file name, so the old JAR stays behind and both versions end up on the classpath,
    /// where which one wins is left to directory order.
    /// <para>
    /// Gradle needs nothing here because its staging task is a <c>Sync</c>, which prunes the destination
    /// itself and stays incremental while doing it. Maven has no equivalent.
    /// </para>
    /// <para>
    /// This is called from the install path rather than when the toolchain is resolved so that clearing
    /// and restaging cannot be separated. Clearing without restaging would leave the AppHost with an
    /// empty classpath.
    /// </para>
    /// </remarks>
    public static void ClearStagedDependencies(JavaAppHostToolchainResolution resolution)
    {
        if (resolution.Toolchain != JavaAppHostToolchain.Maven)
        {
            return;
        }

        var dependencyDirectory = Path.Combine(
            resolution.ProjectDirectory.FullName,
            GetDependencyDirectory(resolution.Toolchain));

        try
        {
            if (Directory.Exists(dependencyDirectory))
            {
                Directory.Delete(dependencyDirectory, recursive: true);
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Continuing here would defeat the only reason this method exists. Maven adds the new
            // versioned JAR beside the stale one, both end up on the "dir/*" classpath, and which one
            // the JVM loads is left to directory order — a failure that surfaces later as an unrelated
            // NoSuchMethodError. Better to stop now with a message that names the directory.
            throw new InvalidOperationException(
                $"The staged dependency directory '{dependencyDirectory}' could not be cleared, so the " +
                "AppHost would run with both the old and new versions of any upgraded dependency on its " +
                "classpath. Close anything holding files in that directory, or delete it manually, then " +
                "run the command again.",
                ex);
        }
    }

    /// <summary>
    /// Path from the AppHost directory to the project directory, or <see langword="null"/> when they are
    /// the same. Null rather than "." so the common flat layout keeps clean, unprefixed relative paths.
    /// </summary>
    private static string? GetRelativeProjectPath(DirectoryInfo projectDirectory, DirectoryInfo appHostDirectory)
    {
        var relativePath = Path.GetRelativePath(appHostDirectory.FullName, projectDirectory.FullName);

        return relativePath == "." ? null : relativePath;
    }

    private static string CombineProjectPath(string? projectPath, string path)
    {
        return projectPath is null ? path : Path.Combine(projectPath, path);
    }

    /// <summary>
    /// Arguments that point the build tool at a project other than its working directory. Both tools
    /// need this because the AppHost is launched from its own directory, not the project root.
    /// </summary>
    private static string[] GetProjectSelectionArgs(JavaAppHostToolchain toolchain, string? projectPath)
    {
        if (projectPath is null)
        {
            return [];
        }

        return toolchain switch
        {
            // https://maven.apache.org/ref/current/maven-embedder/cli.html
            JavaAppHostToolchain.Maven => ["-f", Path.Combine(projectPath, MavenPomFileName)],
            // https://docs.gradle.org/current/userguide/command_line_interface.html
            JavaAppHostToolchain.Gradle => ["-p", projectPath],
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static string[] GetMavenProjectSelectionArgs(
        JavaToolInvocation invocation,
        DirectoryInfo projectDirectory,
        DirectoryInfo appHostDirectory,
        string? projectPath,
        bool usesMavenReactor,
        bool upstreamOnly)
    {
        if (!usesMavenReactor)
        {
            return GetProjectSelectionArgs(JavaAppHostToolchain.Maven, projectPath);
        }

        var reactorPath = Path.GetRelativePath(appHostDirectory.FullName, invocation.WrapperDirectory.FullName);
        var modulePath = Path.GetRelativePath(invocation.WrapperDirectory.FullName, projectDirectory.FullName);

        return
        [
            "-f", Path.Combine(reactorPath, MavenPomFileName),
            // Maven expands -am, removes the selected module, and retains the aggregator so an
            // independent module performs a successful POM-only install instead of leaving an empty reactor.
            "-pl", upstreamOnly ? $"{modulePath},!{modulePath},." : modulePath,
            .. (upstreamOnly ? (string[])["-am"] : [])
        ];
    }

    private static bool IsMavenReactorModule(DirectoryInfo reactorDirectory, DirectoryInfo projectDirectory)
    {
        var visited = new HashSet<string>(PathComparer);
        return IsMavenReactorModule(reactorDirectory, projectDirectory.FullName, visited);
    }

    private static bool IsMavenReactorModule(
        DirectoryInfo aggregatorDirectory,
        string projectDirectory,
        HashSet<string> visited)
    {
        if (!visited.Add(aggregatorDirectory.FullName))
        {
            return false;
        }

        try
        {
            var document = XDocument.Load(Path.Combine(aggregatorDirectory.FullName, MavenPomFileName));
            var modules = document.Root?
                .Elements()
                .FirstOrDefault(static element => element.Name.LocalName == "modules")?
                .Elements()
                .Where(static element => element.Name.LocalName == "module")
                ?? [];

            foreach (var module in modules)
            {
                var modulePath = module.Value.Trim();
                if (modulePath.Length == 0 || modulePath.Contains("${", StringComparison.Ordinal))
                {
                    continue;
                }

                var moduleDirectory = new DirectoryInfo(Path.GetFullPath(Path.Combine(aggregatorDirectory.FullName, modulePath)));
                if (string.Equals(moduleDirectory.FullName, projectDirectory, PathComparison)
                    || (File.Exists(Path.Combine(moduleDirectory.FullName, MavenPomFileName))
                        && IsMavenReactorModule(moduleDirectory, projectDirectory, visited)))
                {
                    return true;
                }
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or XmlException)
        {
            return false;
        }

        return false;
    }

    private static string GetClassesDirectory(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            // Both are the build tool's conventional output for main classes.
            // https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
            // https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_project_layout
            JavaAppHostToolchain.Maven => Path.Combine("target", "classes"),
            JavaAppHostToolchain.Gradle => Path.Combine("build", "classes", "java", "main"),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static string GetDependencyDirectory(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Maven => Path.Combine("target", DependencyDirectoryName),
            JavaAppHostToolchain.Gradle => Path.Combine("build", DependencyDirectoryName),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static CommandSpec[] CreateInstallCommands(
        JavaAppHostToolchain toolchain,
        JavaToolInvocation invocation,
        DirectoryInfo projectDirectory,
        DirectoryInfo appHostDirectory,
        string? projectPath,
        bool usesMavenReactor)
    {
        if (toolchain == JavaAppHostToolchain.Maven && usesMavenReactor)
        {
            // The AppHost cannot be compiled before Aspire generates .aspire/modules. Install only its
            // upstream reactor projects first, then stage the selected module's runtime classpath. Both
            // commands stay in dependency installation so restore and --no-build cannot skip staging.
            // Install rather than package because the second Maven invocation resolves those sibling
            // artifacts from the local repository after the first reactor session has ended.
            return
            [
                invocation.CreateCommand(
                [
                    "-B", "-q",
                    .. GetMavenProjectSelectionArgs(
                        invocation,
                        projectDirectory,
                        appHostDirectory,
                        projectPath,
                        usesMavenReactor: true,
                        upstreamOnly: true),
                    "install",
                    "-Dmaven.test.skip=true"
                ]),
                invocation.CreateCommand(
                [
                    "-B", "-q",
                    .. GetMavenProjectSelectionArgs(
                        invocation,
                        projectDirectory,
                        appHostDirectory,
                        projectPath,
                        usesMavenReactor: true,
                        upstreamOnly: false),
                    "dependency:copy-dependencies",
                    $"-DoutputDirectory={GetDependencyDirectory(toolchain)}",
                    "-DincludeScope=runtime"
                ])
            ];
        }

        string[] toolArgs = toolchain switch
        {
            // Batch mode keeps the transfer progress spinner out of the CLI's captured output.
            // Only runtime-scoped dependencies are staged: test and provided dependencies are not
            // on the application's runtime classpath and staging them can shadow real versions.
            JavaAppHostToolchain.Maven =>
            [
                "-B", "-q",
                .. GetProjectSelectionArgs(JavaAppHostToolchain.Maven, projectPath),
                "dependency:copy-dependencies",
                // Maven resolves a relative outputDirectory against the project's base directory, so
                // the path is expressed relative to the project rather than the working directory.
                $"-DoutputDirectory={GetDependencyDirectory(toolchain)}",
                "-DincludeScope=runtime"
            ],
            JavaAppHostToolchain.Gradle =>
            [
                "-q",
                .. GetProjectSelectionArgs(toolchain, projectPath),
                "--init-script", CombineProjectPath(projectPath, GradleInitScriptPath),
                "aspireCopyDependencies"
            ],
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };

        return [invocation.CreateCommand(toolArgs)];
    }

    /// <summary>
    /// Compiles the AppHost with javac, against the dependency classpath the build tool staged.
    /// </summary>
    /// <remarks>
    /// The build tool resolves dependencies but does not compile, because neither Maven nor Gradle can
    /// be told from the command line about the generated SDK under <c>.aspire/modules</c>. Maven has no
    /// user property for an extra source root or compiler argument — <c>compilerArgs</c>,
    /// <c>compilerArgument</c>, and the source roots are all pom-only — so <c>mvnw compile</c> fails with
    /// "package aspire does not exist" no matter what is passed after the goal. Editing the user's
    /// <c>pom.xml</c> to add a source root is not an option either: the build file belongs to them.
    /// <para>
    /// Compiling with javac instead keeps the AppHost building the same way under all three toolchains,
    /// and the build tool keeps the two jobs it is actually needed for: resolving third-party
    /// dependencies, and giving the IDE a real project model.
    /// </para>
    /// <para>
    /// The consequence, which is worth knowing: compiler configuration in <c>pom.xml</c> or
    /// <c>build.gradle</c> — annotation processors such as Lombok, custom lint settings, an alternative
    /// compiler — does not apply to <c>AppHost.java</c>.
    /// </para>
    /// </remarks>
    /// <summary>
    /// Inputs that decide what the AppHost is compiled <em>against</em>, as opposed to what it is
    /// compiled <em>from</em>.
    /// </summary>
    /// <remarks>
    /// A dependency bump changes no Java source at all: the build descriptor changes, and the build
    /// tool then stages a differently-named JAR. Without these the cached bytecode is reused and the
    /// AppHost runs against an API that is no longer on its classpath, usually surfacing as a
    /// NoSuchMethodError at the point of use rather than anything that names the real cause.
    /// <para>
    /// The staged dependency directory is listed non-recursively and its JARs are outside the check's
    /// source extensions on purpose. Staging runs on every launch and can rewrite the JARs in place,
    /// so only the directory's own timestamp is meaningful — and that moves exactly when the resolved
    /// set changes, which is the question being asked.
    /// </para>
    /// </remarks>
    private static string[] GetDependencyInputs(JavaAppHostToolchain toolchain, string? projectPath, string dependencyDirectory)
    {
        string[] buildDescriptors = toolchain switch
        {
            JavaAppHostToolchain.Maven => [MavenPomFileName],
            // The version catalog is Gradle's other place for dependency coordinates, and it is
            // conventionally a sibling of the settings file rather than of the build file.
            // https://docs.gradle.org/current/userguide/version_catalogs.html
            JavaAppHostToolchain.Gradle =>
            [
                GradleBuildFileName,
                GradleKotlinBuildFileName,
                GradleSettingsFileName,
                GradleKotlinSettingsFileName,
                Path.Combine("gradle", "libs.versions.toml")
            ],
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };

        return
        [
            .. buildDescriptors.Select(descriptor => CombineProjectPath(projectPath, descriptor)),
            dependencyDirectory
        ];
    }

    private static CommandSpec CreateCompileCommand(JavaAppHostToolchain toolchain, RuntimeSpec baseRuntimeSpec, string? projectPath, string classesDirectory, string dependencyDirectory)
    {
        var baseCompile = baseRuntimeSpec.PreExecute?.FirstOrDefault()
            ?? throw new InvalidOperationException("The Java runtime spec has no compile step to adapt for a build tool.");

        var baseArgs = baseCompile.Args ?? [];

        // "dir/*" is expanded by the JVM's own launcher rather than the shell, so it needs no shell and
        // stays correct when the directory is empty.
        // https://docs.oracle.com/en/java/javase/25/docs/specs/man/javac.html#standard-options
        string[] addedArgs =
        [
            "-classpath", Path.Combine(dependencyDirectory, "*"),
            // The AppHost directory is the working directory and is also a source root under both
            // supported layouts, so this is what lets the AppHost reference the project's own classes.
            // It has to be set explicitly because javac otherwise defaults the source path to the class
            // path, which -classpath has just replaced.
            //
            // src/main/java is included as well for the flat layout, where AppHost.java sits beside
            // pom.xml at the project root and the project's own sources are one source root down. The
            // build tool only stages dependencies here - it never compiles - so without this entry a
            // reference to the project's own class fails with "cannot find symbol". Under the
            // conventional layout the working directory already is src/main/java, which makes the extra
            // entry a path that does not exist; javac ignores those, so it costs nothing.
            "-sourcepath", string.Join(Path.PathSeparator, ".", Path.Combine("src", "main", "java")),
            // Output goes to the build tool's own directory rather than the javac toolchain's
            // .java-build, so that `mvn clean` / `gradle clean` removes it and it is already ignored by
            // any Maven or Gradle .gitignore.
            "-d", classesDirectory
        ];

        // The javac options and the source arguments are reused from the base spec rather than repeated
        // here, so the two toolchains cannot drift apart. The output directory is the one thing replaced.
        var outputIndex = Array.IndexOf(baseArgs, "-d");

        var args = outputIndex >= 0 && outputIndex + 1 < baseArgs.Length
            ? (string[])[.. baseArgs[..outputIndex], .. addedArgs, .. baseArgs[(outputIndex + 2)..]]
            : [.. addedArgs, .. baseArgs];

        return new CommandSpec
        {
            Command = baseCompile.Command,
            Args = args,
            // The stamp has to move with the output directory. Left in .java-build it would survive a
            // `mvn clean`, and the next launch would skip a compile whose classes had just been deleted.
            UpToDateCheck = baseCompile.UpToDateCheck is null
                ? null
                : new CommandUpToDateCheck
                {
                    // The base spec guesses at "src/main/java" relative to the AppHost directory, which
                    // is only right for the flat layout. Here the project's real source root is known,
                    // so it replaces the guess: under the conventional layout that root *is* the AppHost
                    // directory, and it has to be scanned recursively for the packages beneath it.
                    Inputs =
                    [
                        .. baseCompile.UpToDateCheck.Inputs.Where(static input => !input.StartsWith("src/main/java", StringComparison.Ordinal)),
                        $"{CombineProjectPath(projectPath, Path.Combine("src", "main", "java"))}/**",
                        .. GetDependencyInputs(toolchain, projectPath, dependencyDirectory)
                    ],
                    Outputs = baseCompile.UpToDateCheck.Outputs?
                        .Select(output => Path.Combine(classesDirectory, Path.GetFileName(output)))
                        .ToArray(),
                    FileExtensions = baseCompile.UpToDateCheck.FileExtensions,
                    StampFile = Path.Combine(classesDirectory, Path.GetFileName(baseCompile.UpToDateCheck.StampFile))
                }
        };
    }

    private static CommandSpec CreateExecuteCommand(string classesDirectory, string dependencyDirectory)
    {
        // "dir/*" is expanded by the JVM into every JAR in that directory. It is not a shell glob, so
        // it works with no shell involved and stays correct when the directory is empty.
        // https://docs.oracle.com/en/java/javase/25/docs/specs/man/java.html#standard-options-for-java
        var classPath = string.Join(Path.PathSeparator, [classesDirectory, Path.Combine(dependencyDirectory, "*")]);

        return new CommandSpec
        {
            Command = "java",
            // {args} is deliberately absent. When no argument contains that placeholder the CLI
            // appends its arguments as separate argv entries, whereas substituting the placeholder
            // joins them into one space-separated string that the AppHost then has to re-split.
            Args = ["-cp", classPath, "AppHost"]
        };
    }
}

/// <summary>
/// How a build tool wrapper is launched: the executable, arguments that must precede the tool's own,
/// and the directory containing the wrapper. Windows needs a command interpreter in front of the
/// batch wrapper, while other platforms invoke it through <c>sh</c>.
/// </summary>
internal readonly record struct JavaToolInvocation(string Command, string[] PrefixArgs, DirectoryInfo WrapperDirectory)
{
    public CommandSpec CreateCommand(string[] args)
    {
        return new CommandSpec
        {
            Command = Command,
            Args = [.. PrefixArgs, .. args]
        };
    }
}

/// <summary>
/// The build tool selected for a Java AppHost, the directory its build file lives in, and why it was chosen.
/// </summary>
/// <remarks>
/// <see cref="ProjectDirectory"/> is not always the AppHost's own directory: with the conventional
/// <c>src/main/java/AppHost.java</c> layout the build file is at the project root. Commands are still
/// launched from the AppHost directory, so paths are made relative to it rather than to the project.
/// </remarks>
internal readonly record struct JavaAppHostToolchainResolution(
    JavaAppHostToolchain Toolchain,
    DirectoryInfo ProjectDirectory,
    string Reason);
