// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Aspire.Hosting.ApplicationModel;

namespace Aspire.Hosting.Azure;

/// <summary>
/// Identifies the container registry that was generated by a compute environment.
/// </summary>
internal sealed class GeneratedContainerRegistryAnnotation(AzureContainerRegistryResource registry) : IResourceAnnotation
{
    public AzureContainerRegistryResource Registry { get; } = registry;
}
