<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>d0c8ad57-03aa-477f-8137-62c0b4c496ed</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\KnownResourceNames.cs" Link="KnownResourceNames.cs" />
  </ItemGroup>

  <ItemGroup>
    <AspireProjectOrPackageReference Include="Aspire.Hosting.AppHost" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Azure.EntraId" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.JavaScript" />
    <ProjectReference Include="..\EntraId.Web\EntraId.Web.csproj" />
  </ItemGroup>

</Project>
