<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <NoWarn>$(NoWarn);ASPIREAZUREPROVISIONING001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Aspire.Hosting.Azure.Provisioning\Aspire.Hosting.Azure.Provisioning.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

</Project>
