//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class JavaScriptHostingExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.BunAppResource> AddBunApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string scriptPath) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> AddDenoApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string scriptPath) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.JavaScriptAppResource> AddJavaScriptApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string runScriptName = "dev") { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREJAVASCRIPT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.NextJsAppResource> AddNextJsApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string runScriptName = "dev") { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.NodeAppResource> AddNodeApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string scriptPath) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.ViteAppResource> AddViteApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string runScriptName = "dev") { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREJAVASCRIPT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.NextJsAppResource> DisableBuildValidation(this ApplicationModel.IResourceBuilder<JavaScript.NextJsAppResource> builder) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREJAVASCRIPT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> PublishAsNodeServer<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder, string entryPoint, string outputPath = ".")
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREJAVASCRIPT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> PublishAsPackageScript<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder, string scriptName = "start", string? runScriptArguments = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREJAVASCRIPT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Use the polyglot-compatible overload instead.")]
        public static ApplicationModel.IResourceBuilder<TResource> PublishAsStaticWebsite<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder, System.Action<JavaScript.PublishAsStaticWebsiteOptions>? configure = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREJAVASCRIPT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Use the polyglot-compatible overload instead.")]
        public static ApplicationModel.IResourceBuilder<TResource> PublishAsStaticWebsite<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder, string apiPath, ApplicationModel.IResourceBuilder<IResourceWithServiceDiscovery> apiTarget, System.Action<JavaScript.PublishAsStaticWebsiteOptions>? configure = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREEXTENSION001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithBrowserDebugger<T>(this ApplicationModel.IResourceBuilder<T> builder, string browser = "msedge")
            where T : JavaScript.JavaScriptAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> WithBuildScript<TResource>(this ApplicationModel.IResourceBuilder<TResource> resource, string scriptName, string[]? args = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> WithBun<TResource>(this ApplicationModel.IResourceBuilder<TResource> resource, bool install = true, string[]? installArgs = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> WithDeno<TResource>(this ApplicationModel.IResourceBuilder<TResource> resource, bool install = false, string[]? installArgs = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoAllowAll(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, bool enabled = true) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoAllowEnv(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] variables) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoAllowFfi(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] libraries) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoAllowNet(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] hosts) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoAllowRead(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] paths) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoAllowRun(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] programs) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoAllowSys(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] apis) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoAllowWrite(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] paths) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoConfig(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, string configFile) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoDenyEnv(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] variables) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoDenyFfi(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] libraries) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoDenyNet(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] hosts) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoDenyRead(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] paths) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoDenyRun(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] programs) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoDenySys(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] apis) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoDenyWrite(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] paths) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoImportMap(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, string importMapFile) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoInspect(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, string? hostPort = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoInspectBrk(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, string? hostPort = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoInspectWait(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, string? hostPort = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoLock(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, string lockFile) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoNodeModulesDir(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, string? mode = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoNoLock(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoRun(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoRuntimeArgs(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] args) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoScriptArgs(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] args) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoServe(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoTask(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, string taskName) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoUnstable(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, params string[] features) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> WithDenoWatch(this ApplicationModel.IResourceBuilder<JavaScript.DenoAppResource> builder, bool hmr = false) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> WithNpm<TResource>(this ApplicationModel.IResourceBuilder<TResource> resource, bool install = true, string? installCommand = null, string[]? installArgs = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> WithPnpm<TResource>(this ApplicationModel.IResourceBuilder<TResource> resource, bool install = true, string[]? installArgs = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> WithRunScript<TResource>(this ApplicationModel.IResourceBuilder<TResource> resource, string scriptName, string[]? args = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<JavaScript.ViteAppResource> WithViteConfig(this ApplicationModel.IResourceBuilder<JavaScript.ViteAppResource> builder, string configPath) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<TResource> WithYarn<TResource>(this ApplicationModel.IResourceBuilder<TResource> resource, bool install = true, string[]? installArgs = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }
    }
}

namespace Aspire.Hosting.JavaScript
{
    [AspireExport(ExposeProperties = true)]
    public sealed partial class BunAppResource : JavaScriptAppResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public BunAppResource(string name, string command, string workingDirectory) : base(default!, default!, default!) { }
    }

    public sealed partial record CopyFilePattern(string Source, string Destination)
    {
    }

    [AspireExport(ExposeProperties = true)]
    public sealed partial class DenoAppResource : JavaScriptAppResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public DenoAppResource(string name, string command, string workingDirectory) : base(default!, default!, default!) { }
    }

    [AspireExport(ExposeProperties = true)]
    public partial class JavaScriptAppResource : ApplicationModel.ExecutableResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, IResourceWithContainerFiles
    {
        public JavaScriptAppResource(string name, string command, string workingDirectory) : base(default!, default!, default!) { }
    }

    public sealed partial class JavaScriptBuildScriptAnnotation : ApplicationModel.IResourceAnnotation
    {
        public JavaScriptBuildScriptAnnotation(string scriptName, string[]? args) { }

        public string[] Args { get { throw null; } }

        public string ScriptName { get { throw null; } }
    }

    public sealed partial class JavaScriptInstallCommandAnnotation : ApplicationModel.IResourceAnnotation
    {
        public JavaScriptInstallCommandAnnotation(string[] args) { }

        public string[] Args { get { throw null; } }

        public string? ProductionInstallArgs { get { throw null; } init { } }
    }

    public partial class JavaScriptInstallerResource : ApplicationModel.ExecutableResource
    {
        public JavaScriptInstallerResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }

    public sealed partial class JavaScriptPackageInstallerAnnotation : ApplicationModel.IResourceAnnotation
    {
        public JavaScriptPackageInstallerAnnotation(ApplicationModel.ExecutableResource installerResource) { }

        public ApplicationModel.ExecutableResource Resource { get { throw null; } }
    }

    public sealed partial class JavaScriptPackageManagerAnnotation : ApplicationModel.IResourceAnnotation
    {
        public JavaScriptPackageManagerAnnotation(string executableName, string? runScriptCommand, string? cacheMount = null) { }

        public string? CacheMount { get { throw null; } }

        public string? CommandSeparator { get { throw null; } init { } }

        public string ExecutableName { get { throw null; } }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREDOCKERFILEBUILDER001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public System.Action<ApplicationModel.Docker.DockerfileStage>? InitializeDockerBuildStage { get { throw null; } init { } }

        public System.Collections.Generic.List<CopyFilePattern> PackageFilesPatterns { get { throw null; } }

        public string? ScriptCommand { get { throw null; } }
    }

    public sealed partial class JavaScriptRunScriptAnnotation : ApplicationModel.IResourceAnnotation
    {
        public JavaScriptRunScriptAnnotation(string scriptName, string[]? args) { }

        public string[] Args { get { throw null; } }

        public string ScriptName { get { throw null; } }
    }

    [AspireExport(ExposeProperties = true)]
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREJAVASCRIPT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public partial class NextJsAppResource : JavaScriptAppResource
    {
        public NextJsAppResource(string name, string command, string workingDirectory) : base(default!, default!, default!) { }
    }

    [AspireExport(ExposeProperties = true)]
    public partial class NodeAppResource : JavaScriptAppResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public NodeAppResource(string name, string command, string workingDirectory) : base(default!, default!, default!) { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIREJAVASCRIPT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public partial class PublishAsStaticWebsiteOptions
    {
        public string OutputPath { get { throw null; } set { } }

        public bool StripPrefix { get { throw null; } set { } }

        public string? TargetEndpointName { get { throw null; } set { } }
    }

    [AspireExport(ExposeProperties = true)]
    public partial class ViteAppResource : JavaScriptAppResource
    {
        public ViteAppResource(string name, string command, string workingDirectory) : base(default!, default!, default!) { }
    }
}