//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class GoHostingExtensions
    {
        [AspireExport(Description = "Adds a Go application resource")]
        public static ApplicationModel.IResourceBuilder<Go.GoAppResource> AddGoApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string packagePath = ".", string[]? buildTags = null, string? ldFlags = null, string? gcFlags = null, bool raceDetector = false) { throw null; }

        [AspireExport(Description = "Passes extra arguments to the Go program at runtime (after go run . in normal mode, or after -- in Delve mode)")]
        public static ApplicationModel.IResourceBuilder<T> WithAppArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, params string[] args)
            where T : Go.GoAppResource { throw null; }

        [AspireExport(Description = "Starts a headless Delve server for remote debugging (GoLand, VS Code attach, any DAP client)")]
        public static ApplicationModel.IResourceBuilder<T> WithDelveServer<T>(this ApplicationModel.IResourceBuilder<T> builder, int port = 2345)
            where T : Go.GoAppResource { throw null; }

        [AspireExport(Description = "Runs go mod tidy before starting the application to ensure go.sum is up to date")]
        public static ApplicationModel.IResourceBuilder<T> WithModTidy<T>(this ApplicationModel.IResourceBuilder<T> builder)
            where T : Go.GoAppResource { throw null; }

        [AspireExport(Description = "Runs go mod vendor before starting the application to cache module dependencies locally")]
        public static ApplicationModel.IResourceBuilder<T> WithModVendor<T>(this ApplicationModel.IResourceBuilder<T> builder)
            where T : Go.GoAppResource { throw null; }

        [AspireExport(Description = "Runs go mod download before starting the application to pre-fetch module dependencies into the local cache")]
        public static ApplicationModel.IResourceBuilder<T> WithModDownload<T>(this ApplicationModel.IResourceBuilder<T> builder)
            where T : Go.GoAppResource { throw null; }

        [AspireExport(Description = "Runs go vet ./... before starting the application to catch static analysis issues")]
        public static ApplicationModel.IResourceBuilder<T> WithVetTool<T>(this ApplicationModel.IResourceBuilder<T> builder)
            where T : Go.GoAppResource { throw null; }

        [AspireExport(Description = "Configures private Go module authentication for publish-time Dockerfile generation")]
        public static ApplicationModel.IResourceBuilder<T> WithGoPrivate<T>(this ApplicationModel.IResourceBuilder<T> builder, string[] privatePatterns, string authHost, string usernameArgName = "GIT_USER", string tokenSecretId = "gittoken")
            where T : Go.GoAppResource { throw null; }
    }
}

namespace Aspire.Hosting.Go
{
    [AspireExport(ExposeProperties = true)]
    public partial class GoAppResource : ApplicationModel.ExecutableResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public GoAppResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }
}
