// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Diagnostics;
using System.Text.RegularExpressions;
using Aspire.TestUtilities;
using Xunit;
using YamlDotNet.RepresentationModel;

namespace Infrastructure.Tests;

/// <summary>
/// Guards the always-on PR merge gate that keeps the VS Code extension changelog check red until
/// generated placeholder release notes are replaced with finalized content.
/// </summary>
public sealed class ExtensionChangelogFinalizedWorkflowTests(ITestOutputHelper output) : IDisposable
{
    private const string WorkflowRelativePath = ".github/workflows/extension-changelog-finalized.yml";
    private const string ScriptRelativePath = ".github/workflows/check-extension-changelog-finalized.sh";

    private readonly TemporaryWorkspace _workspace = TemporaryWorkspace.Create(output);

    public void Dispose() => _workspace.Dispose();

    [Fact]
    public void WorkflowRunsOnEveryPullRequestWithLeastPrivilegeAndStableCheckName()
    {
        var workflowText = ReadWorkflowText();
        var trigger = GetTopLevelSection(workflowText, "on");

        Assert.Equal(
            "  pull_request:\n",
            trigger.ReplaceLineEndings("\n"));

        var workflow = LoadWorkflow();
        var root = (YamlMappingNode)workflow.Documents[0].RootNode;
        var permissions = (YamlMappingNode)root.Children[new YamlScalarNode("permissions")];

        Assert.Collection(
            permissions.Children,
            entry =>
            {
                Assert.Equal("contents", ((YamlScalarNode)entry.Key).Value);
                Assert.Equal("read", ((YamlScalarNode)entry.Value).Value);
            });

        var jobs = (YamlMappingNode)root.Children[new YamlScalarNode("jobs")];
        var gateJob = Assert.IsType<YamlMappingNode>(Assert.Single(jobs.Children).Value);

        Assert.Equal("Extension changelog finalized", Scalar(gateJob, "name"));

        var steps = ((YamlSequenceNode)gateJob.Children[new YamlScalarNode("steps")]).Cast<YamlMappingNode>();
        Assert.Contains(
            steps,
            step => Scalar(step, "run")?.Contains("bash .github/workflows/check-extension-changelog-finalized.sh", StringComparison.Ordinal) == true);
    }

    [Theory]
    [InlineData("<!-- aspire-ext-changelog from=123 to=456 base=1.2.3 -->", "pending release-notes marker", 3)]
    [InlineData("_Release notes are being generated automatically and will replace this placeholder shortly._", "autogenerated placeholder prose", 3)]
    [RequiresTools(["bash"])]
    public async Task PlaceholderContentFailsWithActionableAnnotation(string placeholder, string expectedReason, int expectedLine)
    {
        await WriteChangelogAsync($"""
            # Aspire VS Code Extension Changelog

            {placeholder}
            """);

        var result = await RunGateScriptAsync();

        Assert.NotEqual(0, result.ExitCode);
        Assert.Contains(
            $"::error file=extension/CHANGELOG.md,line={expectedLine},title=Finalize VS Code extension changelog::",
            result.Output,
            StringComparison.Ordinal);
        Assert.Contains(expectedReason, result.Output, StringComparison.Ordinal);
        Assert.Contains(
            "Replace the placeholder with finalized release notes before merging.",
            result.Output,
            StringComparison.Ordinal);
    }

    [Fact]
    [RequiresTools(["bash"])]
    public async Task FinalizedChangelogPasses()
    {
        await WriteChangelogAsync("""
            # Aspire VS Code Extension Changelog

            ## v1.99.0

            ### Features

            - Ship finalized extension release notes.
            """);

        var result = await RunGateScriptAsync();

        Assert.Equal(0, result.ExitCode);
        Assert.Equal("extension/CHANGELOG.md is finalized.\n", result.Output.ReplaceLineEndings("\n"));
    }

    private async Task WriteChangelogAsync(string content)
    {
        var changelogPath = Path.Combine(_workspace.Path, "extension", "CHANGELOG.md");
        Directory.CreateDirectory(Path.GetDirectoryName(changelogPath)!);

        await File.WriteAllTextAsync(changelogPath, content.ReplaceLineEndings("\n"));
    }

    private async Task<CommandResult> RunGateScriptAsync()
    {
        var scriptPath = Path.Combine(RepoRoot.Path, ScriptRelativePath);
        Assert.True(File.Exists(scriptPath), $"Expected helper script at '{ScriptRelativePath}'.");

        using var process = new Process();
        process.StartInfo.FileName = "bash";
        process.StartInfo.ArgumentList.Add(scriptPath);
        process.StartInfo.WorkingDirectory = _workspace.Path;
        process.StartInfo.RedirectStandardError = true;
        process.StartInfo.RedirectStandardOutput = true;
        process.StartInfo.UseShellExecute = false;

        process.Start();

        // Read both streams concurrently to avoid deadlock when the shell emits an annotation.
        var stdoutTask = process.StandardOutput.ReadToEndAsync();
        var stderrTask = process.StandardError.ReadToEndAsync();
        using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(30));
        await process.WaitForExitAsync(timeout.Token);

        return new CommandResult(process.ExitCode, await stdoutTask + await stderrTask);
    }

    private static YamlStream LoadWorkflow()
    {
        var yaml = new YamlStream();
        using var reader = new StringReader(ReadWorkflowText());
        yaml.Load(reader);

        return yaml;
    }

    private static string ReadWorkflowText()
    {
        var workflowPath = Path.Combine(RepoRoot.Path, WorkflowRelativePath);
        Assert.True(File.Exists(workflowPath), $"Expected workflow file at '{WorkflowRelativePath}'.");

        return File.ReadAllText(workflowPath);
    }

    private static string GetTopLevelSection(string text, string key)
    {
        var match = Regex.Match(
            text,
            $"(?m)^{Regex.Escape(key)}:\\r?\\n(?<value>(?:^[ ].*\\r?\\n)*)",
            RegexOptions.CultureInvariant);

        Assert.True(match.Success, $"Could not find top-level workflow section '{key}'.");
        return match.Groups["value"].Value;
    }

    private static string? Scalar(YamlMappingNode node, string key)
        => node.Children.TryGetValue(new YamlScalarNode(key), out var value) && value is YamlScalarNode scalar
            ? scalar.Value
            : null;

    private sealed record CommandResult(int ExitCode, string Output);
}
