<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Size</OptimizationPreference>
    <AssemblyName>aspire-tray</AssemblyName>
    <ApplicationIcon>$(SharedDir)Aspire.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="$(SharedDir)Aspire.ico" Link="Aspire.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
