<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageTags>aspire integration hosting rust framework runtime</PackageTags>
    <Description>Rust support for Aspire.</Description>
    <SuppressFinalPackageVersion>true</SuppressFinalPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire.Hosting\Aspire.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Aspire.Hosting.Rust.Tests" />
  </ItemGroup>

</Project>
