<Project>
  <PropertyGroup>
    <RepoRoot>$([MSBuild]::NormalizeDirectory('$(MSBuildThisFileDirectory)', '..', '..'))</RepoRoot>
    <RepositoryEngineeringDir>$(RepoRoot)eng\</RepositoryEngineeringDir>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />
</Project>
