#!/usr/bin/env bash
set -euo pipefail

display_path="extension/CHANGELOG.md"
changelog_path="${1:-$display_path}"

if [[ ! -f "$changelog_path" ]]; then
  printf '%s\n' "::error file=$display_path,title=Finalize VS Code extension changelog::Expected $display_path to exist."
  exit 1
fi

find_placeholder_line() {
  local placeholder="$1"
  local file="$2"
  local match

  match="$(grep -Fn -m 1 "$placeholder" "$file" || true)"
  if [[ -z "$match" ]]; then
    return 1
  fi

  printf '%s' "${match%%:*}"
}

emit_placeholder_error() {
  local line="$1"
  local reason="$2"

  printf '%s\n' "::error file=$display_path,line=$line,title=Finalize VS Code extension changelog::$display_path still contains $reason. Replace the placeholder with finalized release notes before merging."
}

# The release workflow drafts the changelog with:
#   <!-- aspire-ext-changelog from=<sha> to=<sha> base=<version> -->
#   _Release notes are being generated automatically and will replace this placeholder shortly._
if line="$(find_placeholder_line '<!-- aspire-ext-changelog' "$changelog_path")"; then
  emit_placeholder_error "$line" "the pending release-notes marker"
  exit 1
fi

if line="$(find_placeholder_line '_Release notes are being generated automatically' "$changelog_path")"; then
  emit_placeholder_error "$line" "autogenerated placeholder prose"
  exit 1
fi

printf '%s\n' "$display_path is finalized."
